<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Payment Success - Course Enrollment Complete">
    <meta name="author" content="">

    <title>Payment Successful - {{ ucfirst($checkout->item_type) }} Enrollment</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap"
        rel="stylesheet">
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ asset('css/templatemo-topic-listing.css') }}" rel="stylesheet">
    <link href="{{ asset('css/navbar.css') }}" rel="stylesheet">
    <link href="{{ asset('css/success.css') }}" rel="stylesheet">
</head>

<body id="top">
    <main>
        <!-- Navbar component -->
        <x-navbar></x-navbar>
        
        <!-- Confetti Animation -->
        <div class="confetti" id="confetti">
            <!-- Confetti pieces will be generated by JavaScript -->
        </div>

        <div class="success-container">
            <div class="success-card">
                <!-- Success Icon -->
                <div class="success-icon">
                    <i class="bi bi-check-lg"></i>
                </div>

                <!-- Main Messages -->
                <h1 class="main-title">
                    @if($checkout->status === 'trial')
                        Free Trial Started!
                    @else
                        Payment Successful!
                    @endif
                </h1>
                <p class="sub-title">
                    @if($checkout->status === 'trial')
                        Your 7-day free trial has begun!
                    @else
                        Welcome to your learning journey!
                    @endif
                </p>

                <!-- Email Confirmation -->
                <div class="email-confirmation">
                    <i class="bi bi-envelope-check me-2"></i>
                    Confirmation sent to {{ $checkout->user->email }}
                </div>

                <!-- Course/Item Information -->
                <div class="course-info">
                    @php
                        $itemDetails = $checkout->item_details;
                        $defaultImage = 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80';
                    @endphp
                    
                    <img src="{{ $itemDetails['image'] ?? $defaultImage }}" 
                         alt="{{ $itemDetails['name'] }}" class="course-image">
                    <div class="course-details">
                        <h4>{{ $itemDetails['name'] }}</h4>
                        <p>{{ $itemDetails['provider'] }} • {{ ucfirst($checkout->item_type) }} • Certificate included</p>
                        <small class="text-muted">
                            @if($checkout->item_type === 'course')
                                Professional course with hands-on learning experience
                            @elseif($checkout->item_type === 'career')
                                Comprehensive career development program
                            @else
                                Focused learning module for skill development
                            @endif
                        </small>
                    </div>
                </div>

                <!-- Transaction Details -->
                <div class="transaction-details">
                    <div class="detail-row">
                        <span class="detail-label">Order ID</span>
                        <span class="detail-value">
                            {{ $checkout->order_id }}
                            <button class="copy-btn" onclick="copyOrderId('{{ $checkout->order_id }}')" title="Copy Order ID">
                                <i class="bi bi-clipboard"></i>
                            </button>
                        </span>
                    </div>
                    <div class="detail-row">
                        <span class="detail-label">Payment Method</span>
                        <span class="detail-value">
                            @if($checkout->payment_method === 'card')
                                Credit Card (**** {{ substr($checkout->card_number, -4) }})
                            @else
                                {{ ucfirst($checkout->payment_method) }}
                            @endif
                        </span>
                    </div>
                    <div class="detail-row">
                        <span class="detail-label">Date</span>
                        <span class="detail-value">{{ $checkout->created_at->format('F j, Y') }}</span>
                    </div>
                    <div class="detail-row">
                        <span class="detail-label">Organization</span>
                        <span class="detail-value">
                            @if($checkout->organization_type === 'individual')
                                Individual
                            @elseif($checkout->organization_type === 'corporation')
                                {{ $checkout->corporation_name }}
                            @else
                                {{ $checkout->school_name }}
                            @endif
                        </span>
                    </div>
                    <div class="detail-row">
                        <span class="detail-label">Total Amount</span>
                        <span class="detail-value">{{ $checkout->formatted_amount }}</span>
                    </div>
                </div>

                <!-- Next Steps -->
                <div class="next-steps">
                    <h3>What's Next?</h3>
                    <div class="step-item">
                        <div class="step-icon">
                            <i class="bi bi-envelope"></i>
                        </div>
                        <div class="step-text">Check your email for {{ $checkout->item_type }} access details and welcome materials</div>
                    </div>
                    <div class="step-item">
                        <div class="step-icon">
                            <i class="bi bi-play-circle"></i>
                        </div>
                        <div class="step-text">
                            @if($checkout->status === 'trial')
                                Start learning immediately with your 7-day free trial access
                            @else
                                Start learning immediately with lifetime access to all content
                            @endif
                        </div>
                    </div>
                    <div class="step-item">
                        <div class="step-icon">
                            <i class="bi bi-people"></i>
                        </div>
                        <div class="step-text">Join our community of learners and connect with instructors</div>
                    </div>
                    <div class="step-item">
                        <div class="step-icon">
                            <i class="bi bi-award"></i>
                        </div>
                        <div class="step-text">
                            @if($checkout->item_type === 'course')
                                Complete the course to earn your professional certificate
                            @elseif($checkout->item_type === 'career')
                                Complete the program to advance your career prospects
                            @else
                                Complete the module to gain specialized skills
                            @endif
                        </div>
                    </div>
                </div>

                <!-- Action Buttons -->
         <div class="action-buttons">
    <a href="/" class="btn-primary-success">
        <i class="bi bi-house me-2"></i>Home
    </a>
   
    <!-- Updated Download Invoice Button -->
    <a href="{{ route('invoice.download', $checkout->order_id) }}" class="btn-secondary-outline" target="_blank">
        <i class="bi bi-download me-2"></i>Download Invoice
    </a>
    <!-- Alternative: View Invoice in Browser -->
    <a href="{{ route('invoice.view', $checkout->order_id) }}" class="btn-secondary-outline" target="_blank">
        <i class="bi bi-file-text me-2"></i>View Invoice
    </a>
</div>

                <!-- Support Information -->
                <div class="support-info">
                    Need help? Contact our support team at 
                    <a href="mailto:support@bridge.com">support@bridge.com</a> or 
                    <a href="tel:+62123456789">+62 123 456 789</a>
                </div>
            </div>
        </div>
    </main>
    
    <x-fotter></x-fotter>

    <!-- JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('js/jquery.sticky.js') }}"></script>
    <script src="{{ asset('js/click-scroll.js') }}"></script>
    <script src="{{ asset('js/custom.js') }}"></script>
    <script src="{{ asset('js/all.js') }}"></script>

    <script>
        // Confetti Animation
        function createConfetti() {
            const confetti = document.getElementById('confetti');
            const colors = ['#10B981', '#3B82F6', '#fbbf24', '#ef4444', '#8b5cf6'];
            
            for (let i = 0; i < 50; i++) {
                const piece = document.createElement('div');
                piece.className = 'confetti-piece';
                piece.style.left = Math.random() * 100 + 'vw';
                piece.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
                piece.style.animationDelay = Math.random() * 3 + 's';
                piece.style.animationDuration = (Math.random() * 3 + 2) + 's';
                confetti.appendChild(piece);
            }
            
            // Remove confetti after animation
            setTimeout(() => {
                confetti.innerHTML = '';
            }, 6000);
        }

        // Copy Order ID function
        function copyOrderId(orderId) {
            navigator.clipboard.writeText(orderId).then(() => {
                // Show copied feedback
                const copyBtn = event.target.closest('.copy-btn');
                const originalIcon = copyBtn.innerHTML;
                copyBtn.innerHTML = '<i class="bi bi-check2"></i>';
                copyBtn.style.color = '#10B981';
                
                setTimeout(() => {
                    copyBtn.innerHTML = originalIcon;
                    copyBtn.style.color = '#3B82F6';
                }, 2000);
            }).catch(() => {
                // Fallback for older browsers
                const textArea = document.createElement('textarea');
                textArea.value = orderId;
                document.body.appendChild(textArea);
                textArea.select();
                document.execCommand('copy');
                document.body.removeChild(textArea);
            });
        }

        // Initialize animations on page load
        document.addEventListener('DOMContentLoaded', function() {
            // Start confetti animation
            createConfetti();
            
            // Add smooth scroll behavior
            document.documentElement.style.scrollBehavior = 'smooth';
        });

        // Add some interactive effects
        document.querySelectorAll('.btn-primary-success, .btn-secondary-outline').forEach(button => {
            button.addEventListener('mouseenter', function() {
                this.style.transform = 'translateY(-2px)';
            });
            
            button.addEventListener('mouseleave', function() {
                this.style.transform = 'translateY(0)';
            });
        });

        // Animate success card on scroll (if needed)
        const observerOptions = {
            threshold: 0.1,
            rootMargin: '0px 0px -50px 0px'
        };

        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.style.opacity = '1';
                    entry.target.style.transform = 'translateY(0)';
                }
            });
        }, observerOptions);

        // Observe elements for animation
        document.querySelectorAll('.transaction-details, .next-steps, .action-buttons').forEach(el => {
            observer.observe(el);
        });
    </script>

    <script>
// Enhanced download function with loading state
function downloadInvoiceWithLoading(orderId) {
    const downloadBtn = document.querySelector('[href*="invoice/download"]');
    const originalText = downloadBtn.innerHTML;
    
    // Show loading state
    downloadBtn.innerHTML = '<i class="bi bi-hourglass-split me-2"></i>Generating PDF...';
    downloadBtn.style.pointerEvents = 'none';
    
    // Create a hidden link to trigger download
    const link = document.createElement('a');
    link.href = `/invoice/download/${orderId}`;
    link.target = '_blank';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Reset button after 3 seconds
    setTimeout(() => {
        downloadBtn.innerHTML = originalText;
        downloadBtn.style.pointerEvents = 'auto';
    }, 3000);
}

// Add click handler for enhanced download
document.addEventListener('DOMContentLoaded', function() {
    const downloadBtn = document.querySelector('[href*="invoice/download"]');
    if (downloadBtn) {
        downloadBtn.addEventListener('click', function(e) {
            e.preventDefault();
            downloadInvoiceWithLoading('{{ $checkout->order_id }}');
        });
    }
});
</script>
</body>
</html>