-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 16, 2025 at 03:19 PM
-- Server version: 8.0.30
-- PHP Version: 8.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bridge`
--

-- --------------------------------------------------------

--
-- Table structure for table `data_kampus`
--

CREATE TABLE `data_kampus` (
  `id` bigint UNSIGNED NOT NULL,
  `nama` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tanggal_berdiri` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lokasi` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `akreditas` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipe` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `logo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `deskripsi` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `website` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `data_kampus`
--

INSERT INTO `data_kampus` (`id`, `nama`, `tanggal_berdiri`, `lokasi`, `akreditas`, `tipe`, `logo`, `deskripsi`, `website`) VALUES
(1, 'Universitas Gadjah Mada', '19 Desember 1949', 'Daerah Istimewa Yogyakarta', 'Unggul', 'universitas', 'images/section2/logo univ/UGm.png', 'Universitas Gadjah Mada atau UGM memiliki jati diri sebagai universitas nasional, universitas perjuangan, universitas pancasila, universitas kerakyatan, dan universitas pusat kebudayaan. Nama UGM diambil dari nama Mahapatih Gadjah Mada yang berhasil mempersatukan Nusantara. Diharapkan UGM berkembang menjadi universitas teladan, universitas perjuangan, universitas kerakyatan, universitas nasional, dan pusat kebudayaan.', 'ugm.ac.id'),
(2, 'Universitas Indonesia', '2 Februari 1950', 'DKI Jakarta', 'Unggul', 'universitas', 'images/section2/logo univ/UI.png', 'Universitas Indonesia adalah kampus modern, komprehensif, terbuka, multi budaya, dan humanis yang mencakup disiplin ilmu yang luas. UI saat ini secara simultan selalu berusaha menjadi salah satu universitas riset atau institusi akademik terkemuka di dunia. Sebagai universitas riset, upaya-upaya pencapaian tertinggi dalam hal penemuan, pengembangan dan difusi pengetahuan secara regional dan global selalu dilakukan.', 'ui.ac.id'),
(3, 'Universitas Sumatera Utara', '20 Agustus 1952', 'Sumatera Utara', 'Unggul', 'universitas', 'images/section2/logo univ/USU.png', 'Universitas Sumatera Utara (USU) adalah perguruan tinggi negeri yang berlokasi di Medan, Sumatera Utara. USU awalnya berdiri dengan nama Yayasan Universitas Sumatera Utara pada 4 Juni 1952. Fakultas pertamanya adalah Fakultas Kedokteran yang didirikan pada tanggal 20 Agustus 1952. USU diresmikan sebagai Universitas Negeri ke-7 di Indonesia pada 20 November 1957 oleh Presiden Soekarno. Pada tahun 2018, USU berganti status perguruan tinggi menjadi Perguruan Tinggi Negeri Badan Hukum (PTN-BH) dan menjadi universitas PTN-BH ke-7 di Indonesia.', 'usu.ac.id'),
(4, 'Universitas Airlangga', '1 November 1954', 'Jawa Timur', 'Unggul', 'universitas', 'images/section2/logo univ/UNAIR.png', 'Universitas Airlangga, disingkat Unair, adalah sebuah perguruan tinggi negeri yang terletak di Surabaya, Jawa Timur. Universitas ini didirikan pada tanggal 10 November 1954 bertepatan dengan hari pahlawan yang ke-9. Berdasarkan peringkat dari QS World University Ranking 2021, Universitas Airlangga menduduki peringkat keempat sebagai perguruan tinggi terbaik di Indonesia.', 'unair.ac.id'),
(5, 'Universitas Hasanuddin', '10 September 1956', 'Sulawesi Selatan', 'Unggul', 'universitas', 'images/section2/logo univ/UNHAS.png', 'Universitas Hasanuddin atau yang sering disebut UNHAS merupakan salah satu perguruan tinggi negeri yang ada di Makassar, Sulawesi Selatan. Nama universitas ini diambil dari nama pahlawan nasional asal Makassar yang memiliki julukan ayam jantan dari timur, Sultan Hasanuddin.<br/><br/>Awalnya UNHAS hanya memiliki 3 fakultas yaitu Hukum, Kedokteran, dan FKIP. Seiring berjalannya waktu, kini UNHAS memiliki banyak fakultas dan program studi. UNHAS juga mengembangkan program pascasarjana untuk S2 dan S3.', 'unhas.ac.id'),
(6, 'Universitas Andalas', '13 September 1956', 'Sumatera Barat', 'Unggul', 'universitas', 'images/section2/logo univ/UNAND.jpeg', 'Universitas Andalas (biasa disingkat dengan UNAND) adalah perguruan tinggi negeri Indonesia yang terletak di Kota Padang, Sumatra Barat, Indonesia. Universitas ini merupakan universitas tertua di luar Pulau Jawa yang dibuka secara resmi pada tanggal 23 Desember 1955 oleh Wakil Presiden Mohammad Hatta. Pada saat itu, Unand adalah universitas keempat yang diresmikan oleh Pemerintah Indonesia. Universitas Andalas terdiri dari lima belas fakultas dengan kampus utama di Limau Manis, Padang. Terdapat pula kampus-kampus lain di Padang, Payakumbuh, dan Dharmasraya.', 'unand.ac.id'),
(7, 'Universitas Padjadjaran', '11 September 1957', 'Jawa Barat', 'Unggul', 'universitas', 'images/section2/logo univ/UNPAD.png', 'Universitas Padjadjaran (UNPAD) adalah perguruan tinggi negeri yang berdiri pada tanggal 11 September 1957 di Bandung, Jawa Barat. Pemilihan nama \"Padjadjaran\", diambil dari nama ibukota Kerajaan Sunda, yaitu Pakuan Pajajaran. Lahirnya Universitas Padjadjaran, merupakan puncak dari gerakan pencerdasan kehidupan masyarakat Jawa Barat yang dirintis oleh beberapa tokoh, antara lain Raden Dewi Sartika, Siti Jenab, Ayu Lasminingsih, K.H. Abdul Halim, dan K.H. Hasan Mustofa. Dalam perkembangannya, Universitas Padjadjaran pernah berhasil mendapatkan peringkat 751-800 kampus terbaik di dunia menurut QS World University Ranking 2023, dan menjadi peringkat ke-7 di tingkat nasional.', 'unpad.ac.id'),
(8, 'Universitas Diponegoro', '15 Oktober 1957', 'Jawa Tengah', 'Unggul', 'universitas', 'images/section2/logo univ/UNDIP.png', 'Universitas Diponegoro atau yang yang biasa dikenal dengan singkatan Undip adalah sebuah Perguruan Tinggi Negeri terkemuka di Indonesia yang berlokasi di Semarang, Jawa Tengah, Indonesia. Undip didirikan pada tahun 1956 sebagai salah satu Perguruan Tinggi Swasta di Indonesia. Kemudian pada tahun 1961 Undip baru mendapat status sebagai Perguruan Tinggi Negeri. Adapun kata “Diponegoro” diambil dari nama pahlawan nasional tanah Jawa, yaitu Pangeran Diponegoro yang merupakan seorang pemimpin perang Diponegoro.', 'undip.ac.id'),
(9, 'Universitas Sriwijaya', '29 Oktober 1960', 'Sumatera Selatan', 'Unggul', 'universitas', 'images/section2/logo univ/UNSRI.png', 'Universitas Sriwijaya (UNSRI) adalah Perguruan Tinggi Negeri yang berlokasi di Indralaya dan Palembang, Sumatera Selatan. Universitas ini didirikan pada tanggal 31 Oktober 1953. UNSRI juga dinobatkan sebagai kampus terluas di Indonesia sekaligus di Asia Tenggara dengan luas 712 hektare. Dari segi prestasi, UNSRI meraih peringkat ke-15 sebagai kampus terbaik di Indonesia versi Webometrics Ranking of World Universities 2022.', 'unsri.ac.id'),
(10, 'Universitas Lambung Mangkurat', '01 Januari 1960', 'Kalimantan Selatan', 'Baik', 'universitas', 'images/section2/logo univ/ULM.png', 'Universitas Lambung Mangkurat (ULM) adalah perguruan tinggi negeri yang berlokasi di Banjarmasin dan Banjarbaru, Kalimantan Selatan. ULM didirikan pada tanggal 21 September 1958, dan diresmikan pada tanggal 1 November 1960. Nama universitas ini diambil dari nama Lambung Mangkurat, yaitu seorang patih dari Kerajaan Negara Dipa, Banjar, Kalimantan Selatan. ULM mengusung visi yang mengandung 3 kata kunci utama, yaitu terkemuka, berdaya saing dan lingkungan lahan basah.', 'ulm.ac.id'),
(11, 'Universitas Syiah Kuala', '2 September 1961', 'Aceh', 'Unggul', 'universitas', 'images/section2/logo univ/USK.png', 'Universitas Syiah Kuala (UNSYIAH) adalah perguruan tinggi negeri yang berlokasi di Banda Aceh. Universitas ini berdiri pada tanggal 2 September 1961. Kampus yang dijuluki “Jantong Hatee Rakyat Aceh” ini merupakan universitas terbesar dan tertua di Banda Aceh. Berdasarkan publikasi yang dirilis oleh lembaga pemeringkatan perguruan tinggi dunia, yaitu Webometrics (2022), UNSYIAH masuk peringkat ke-8 kampus terbaik di Indonesia.', 'usk.ac.id'),
(12, 'Universitas Sam Ratulangi', '14 September 1961', 'Sulawesi Utara', 'Unggul', 'universitas', 'images/section2/logo univ/UNSRAT.png', 'Universitas Sam Ratulangi (UNSRAT) adalah salah satu Perguruan Tinggi Negeri di Indonesia yang berlokasi di Kota Manado, Provinsi Sulawesi Utara. Sejak didirikan hingga saat ini, UNSRAT telah memiiki 11 fakultas dan 1 program Pascasarjana. Kemudian, pada tanggal 27 Desember 2017, sesuai dengan Keputusan BAN-PT Nomor 5236/SK/BAN-PT/Akred/PT/XII/2017, UNSRAT berhasil mendapatkan Akreditas A.', 'unsrat.ac.id'),
(13, 'Universitas Udayana', '29 September 1962', 'Bali', 'Unggul', 'universitas', 'images/section2/logo univ/UNUD.png', 'Universitas Udayana merupakan perguruan tinggi negeri yang berada di pulau Bali. Universitas Udayana memiliki dua cabang kampus yang berada di Kabupaten Badung dan Kota Denpasar.<br/><br/>Universitas Udayana mempunyai tujuan untuk menghasilkan lulusan bermutu yang memilki kompetensi tinggi dalam penguasaan ilmu pengetahuan, teknologi dan seni.<br/><br/>Saat ini Universitas Udayana telah meluluskan sebanyak 716 orang dan total alumni sebanyak 120.129 orang.', 'unud.ac.id'),
(14, 'Universitas Nusa Cendana', '1 September 1962', 'Nusa Tenggara Timur', 'Unggul', 'universitas', 'images/section2/logo univ/UNDANA.png', 'Universitas Nusa Cendana (UNDANA) adalah perguruan tinggi negeri pertama di Provinsi Nusa Tenggara Timur (NTT). Universitas ini berdiri pada tanggal 1 September 1962, dan didirikan oleh Kementerian Perguran Tinggi dan Ilmu Pengetahuan, dengan menimbang aspirasi masyarakat NTT. Dalam perkembangannya, saat ini Undana telah menghasilkan lebih dari 45 ribu alumni yang menyebar di berbagai kawasan di Indonesia, terutama di NTT sendiri, dan mengisi lowongan birokrasi, bahkan mendominasi berbagai eselon di tingkat Provinsi dan Kabupaten/Kota di NTT.', 'undana.ac.id'),
(15, 'Universitas Mulawarman', '27 September 1962', 'Kalimantan Timur', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNMUL.png', 'Universitas Mulawarman (Unmul) adalah perguruan tinggi negeri yang berlokasi di Samarinda, Kalimantan Timur, Indonesia. Universitas ini berdiri pada tanggal 27 September 1962, dan menjadi universitas tertua di Kalimantan Timur. Oleh karena itu, Unmul merupakan perguruan tinggi dengan jumlah mahasiswa terbesar di Kalimantan, yaitu lebih dari 30.577 orang. Kampus utamanya terletak di Gunung Kelua, sedangkan kampus lainnya terdapat di Jalan Pahlawan, Jalan Banggeris dan Jalan Flores. Pada Tahun 2022, Unmul berhasil menempati peringkat 35 perguruan tinggi terbaik di Indonesia dan menjadi universitas terbaik di Pulau Kalimantan.', 'unmul.ac.id'),
(16, 'Universitas Mataram', '1 Oktober 1962', 'Nusa Tenggara Barat', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNRAM.png', 'Universitas Mataram (Unram) adalah perguruan tinggi negeri yang didirikan pada tanggal 1 Oktober 1962 di kota Mataram, Nusa Tenggara Barat. Proses berdirinya berawal dari pembentukan Panitia Persiapan Universitas Negeri di Mataram, yang diketuai oleh Gubernur Kepala Daerah Tingkat I NTB, yaitu R. Ar. Moh. Ruslan Tjakraningrat. Hingga saat ini, Unram masih terus berusaha mengembangkan pendidikannya. Salah satunya melalui kerja sama dengan berbagai lembaga dan perguruan tinggi, baik yang berasal dari dalam negeri maupun luar negeri.', 'unram.ac.id'),
(17, 'Universitas Riau', '1 Oktober 1962', 'Riau', 'Unggul', 'universitas', 'images/section2/logo univ/UNRI.png', 'Universitas Riau (UNRI) adalah Perguruan Tinggi Negeri yang berlokasi di Pekanbaru, Riau, Indonesia. Universitas ini didirikan pada tanggal 1 Oktober 1962, berdasarkan Surat Keputusan Yayasan UNRI Nomor 02/KPTS/JUR/62. UNRI memiliki beberapa kampus untuk mendukung penyelenggaraan kegiatan akademik dan non-akademik. Kampus utamanya berlokasi di daerah Bina Widya, Gobah, Pekanbaru. Mengusung visi “Menjadi Universitas Riset Unggul Bermartabat di Bidang Riset dan Teknologi di Kawasan Asia tenggara tahun 2035”, Universitas Riau terus memperkuat resources dan mengembangkan berbagai inovasi.', 'unri.ac.id'),
(18, 'Universitas Cenderawasih', '10 November 1962', 'Papua', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNCEN.jpeg', 'Universitas Cenderawasih Jayapura, didirikan oleh Presiden Republik Indonesia, Ir. Soekarno, pada Tanggal 10 November 1962, dengan tujuan untuk memberikan akses dan kesempatan serta pelayanan pendidikan tinggi bagi masyarakat di Tanah Papua.<br/><br/>Sejak berdiri, hingga saat ini, Universitas Cenderawasih terus berupaya meningkatkan kinerja dan mutu pelayanan pendidikan tinggi kepada masyarakat, dengan meningkatkan sarana dan prasarana pendidikan, inovasi media pembelajaran dan metode pembelajaran, serta meningkatkan akreditasi program studi di setiap Fakultas dan Program Pascasarjana.', 'uncen.ac.id'),
(19, 'Universitas Brawijaya', '5 Januari 1963', 'Jawa Timur', 'Unggul', 'universitas', 'images/section2/logo univ/UB.png', 'Universitas Brawijaya (UB) didirikan oleh Presiden Republik Indonesia melalui kawat no. 258/K/61 dikirim pada tanggal 11 Juli 1961. Nama Brawijaya ini diambil dari gelar Raja-Raja Majapahit, sebuah kerajaan besar di Indonesia dari abad ke-12 hingga ke-15.<br/><br/>Saat ini UB merupakan salah satu universitas terkemuka di Indonesia dengan lebih dari 60.000 mahasiswa, dalam berbagai program vokasi, sarjana, magister, doktor, profesi, dan dokter spesialis.', 'ub.ac.id'),
(20, 'Universitas Jambi', '23 Maret 1963', 'Jambi', 'Unggul', 'universitas', 'images/section2/logo univ/UNJA.png', 'Universitas Jambi (UNJA) adalah salah satu perguruan tinggi negeri unggulan yang berada di provinsi Jambi, Indonesia. Universitas ini didirikan pada 23 Maret 1963, yang dipimpin oleh Kolonel M. Joesoef Singedekane sebagai ketua presidium. Dengan mengusung visi World Entrepreneurship University, UNJA menyelenggarakan berbagai jenjang pendidikan tinggi, mulai dari program Diploma, Sarjana, hingga Pascasarjana.', 'unja.ac.id'),
(21, 'Universitas Pattimura', '20 Juli 1955', 'Maluku', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNPATTI.png', 'Universitas Pattimura (UNPATTI) adalah perguruan tinggi negeri tertua di Pulau Maluku, yang berdiri pada 8 Agustus 1962. UNPATTI menjadi satu dari banyak universitas negeri favorit yang berbasis riset modern yang ada di Indonesia. UNPATTI juga menjadi universitas pilihan nomor satu bagi sebagian besar masyarakat Indonesia Timur. Pada 2016, UNPATTI telah memiliki 57 program studi yang terbagi dalam 9 fakultas. Mayoritas program studinya juga telah mendapat akreditasi B dari Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).', 'unpatti.ac.id'),
(22, 'Universitas Tanjungpura', '20 Mei 1959', 'Kalimantan Barat', 'Unggul', 'universitas', 'images/section2/logo univ/UNTAN.png', 'Universitas Tanjungpura (UNTAN) adalah perguruan tinggi negeri yang berlokasi di Kota Pontianak, Kalimantan Barat. Nama Universitas Tanjungpura ini berasal dari nama Kerajaan Tanjungpura yang terletak di Kalimantan Barat. Hingga saat ini, UNTAN telah memiliki 9 fakultas dengan jenjang pendidikan hingga doktoral (S3). Pada tahun 2023, Universitas Tanjungpura menempati peringkat ke-69 universitas terbaik di Indonesia dan peringkat ke-3 universitas terbaik di Pulau Kalimantan versi Webometrics.', 'untan.ac.id'),
(23, 'Universitas Jenderal Soedirman', '23 September 1963', 'Jawa Tengah', 'Unggul', 'universitas', 'images/section2/logo univ/UNSOED.png', 'Universitas Jenderal Soedirman (Unsoed) adalah sebuah perguruan tinggi negeri di Indonesia yang terletak di Purwokerto, Kabupaten Banyumas, Jawa Tengah. Universitas ini berdiri pada tanggal 23 September 1963. Nama Jenderal Soedirman sendiri, diambil dari Panglima Besar Jenderal Soedirman yang merupakan pahlawan nasional, untuk mengenang jasa-jasanya pada nusa, bangsa, dan negara. Unsoed merupakan universitas tertua kedua di Jawa Tengah setelah Universitas Diponegoro, sekaligus menjadi salah satu universitas bergengsi di Indonesia dengan jumlah peminat yang relatif tinggi dalam seleksi nasional setiap tahunnya.', 'unsoed.ac.id'),
(24, 'Universitas Palangka Raya', '10 November 1963', 'Kalimantan Tengah', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UPR.png', 'Universitas Palangka Raya (UPR) adalah perguruan tinggi negeri pertama dan tertua di Provinsi Kalimantan Tengah, yang didirikan pada tanggal 10 November 1963. Universitas ini terdiri dari 8 fakultas, yaitu Fakultas Keguruan dan Ilmu Pendidikan, Fakultas Ekonomi dan Bisnis, Fakultas Pertanian, Fakultas Teknik, Fakultas Hukum, Fakultas Ilmu Sosial dan Ilmu Politik, Fakultas Kedokteran, serta Fakultas Matematika dan Ilmu Pengetahuan Alam. Menurut data yang dirilis oleh Webometrics, Universitas Palangka Raya berada di peringkat 76 Perguruan Tinggi Terbaik periode Januari-Juli 2021.', 'upr.ac.id'),
(25, 'Universitas Jember', '10 November 1964', 'Jawa Timur', 'Unggul', 'universitas', 'images/section2/logo univ/UNEJ.png', 'Universitas Jember (UNEJ) adalah perguruan tinggi negeri yang terletak di Kabupaten Jember, Provinsi Jawa Timur. Pada awal berdirinya, universitas ini memiliki 5 fakultas, yakni Fakultas Hukum di Jember, dengan cabangnya di Banyuwangi, Fakultas Ilmu Sosial dan Ilmu Politik, Fakultas Pertanian di Jember, Fakultas Ekonomi, Fakultas Sastra di Banyuwangi. Sejak lebih dari 50 tahun menyelenggarakan pendidikan tingkat tinggi, kini Universitas Jember memiliki 15 fakultas yang menyediakan program pendidikan tingkat Diploma, Sarjana, hingga Pascasarjana yang membawahi lebih dari 100 program studi.', 'unej.ac.id'),
(26, 'Universitas Lampung', '23 September 1965', 'Lampung', 'Unggul', 'universitas', 'images/section2/logo univ/UNILA.png', 'Universitas Lampung (Unila) adalah perguruan tinggi negeri pertama dan tertua di Provinsi Lampung, Indonesia. Dies Natalis Unila ditetapkan pada tanggal 23 September 1965. Unila lahir atas keinginan dan harapan masyarakat untuk memiliki perguruan tinggi di daerah mereka, karena banyak pelajar lulusan SMA di Lampung yang harus pergi ke Jawa atau Palembang untuk melanjutkan pendidikannya. Saat ini, Unila memiliki 1 Program Pascasarjana dan 8 fakultas yang menaungi 107 program studi untuk tingkat diploma, sarjana, magister, doktor, dan profesi.', 'unila.ac.id'),
(27, 'Universitas Sebelas Maret', '11 Maret 1976', 'Jawa Tengah', 'Unggul', 'universitas', 'images/section2/logo univ/UNS.png', 'Universitas Sebelas Maret (UNS) adalah perguruan tinggi negeri yang berlokasi di Kentingan, Jebres, Kota Surakarta. Universitas ini didirikan pada tanggal 11 Maret 1976 di Solo, atas dasar keinginan masyarakat Solo untuk memiliki sebuah perguruan tinggi di daerah mereka. Di tahun 2022, Webometrics Ranking of World Universities 2022 menempatkan UNS sebagai perguruan tinggi terbaik peringkat ke-6 di Indonesia dan peringkat ke-1.144 di dunia.', 'uns.ac.id'),
(28, 'Universitas Tadulako', '4 Agustus 1981', 'Sulawesi Tengah', 'Unggul', 'universitas', 'images/section2/logo univ/UNTAD.png', 'Keberadaan perguruan tinggi di Sulawesi Tengah, yang merupakan cikal bakal Universitas Tadulako ditandai dengan 3 (tiga) tahapan perjalanan sejarah yaitu periode Universitas Tadulako status swasta (1963-1966), periode status cabang (1966-1981), dan status negeri yang berdiri sendiri “Universitas Tadulako” (UNTAD), sejak tahun 1981.', 'untad.ac.id'),
(29, 'Universitas Halu Oleo', '19 Agustus 1981', 'Sulawesi Tenggara', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UHO.png', 'Universitas Halu Oleo, disingkat UHO, adalah perguruan tinggi negeri di Kendari, Sulawesi Tenggara, Indonesia, yang berdiri tahun 1964 sebagai perguruan tinggi swasta filial dari Universitas Hasanuddin Makassar. Hingga saat ini, UHO memiliki prestasi internasional di berbagai bidang, seperti robotik, desain, paduan suara, debat, olahraga, jurnal dan lainnya. Kampus ini juga emiliki teknologi dan sistem informasi pembelajaran yang sangat unggul untuk mendukung proses pembelajaran baik.', 'uho.ac.id'),
(30, 'Universitas Bengkulu', '24 April 1982', 'Bengkulu', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNIB.png', 'Universitas Bengkulu, atau disingkat UNIB, adalah salah satu perguruan tinggi negeri yang berdiri sejak 24 April 1982. Lokasi Unib terbagi menjadi 4 kampus dengan lokasi kampus yang berbeda, yakni Kampus Cimanuk, Kampus Kandang Limun (Kompleks Kampus Utama), Kampus Air Sebakul, dan Kampus Padang Harapan. Universitas Bengkulu diresmikan oleh Menteri Pendidikan dan Kebudayaan berdasarkan Keppres Nomor 17 Tahun 1982. Setelah Unib diresmikan, pada waktu yang sama dilantik Rektor Unib yang pertama, yakni Prof. Ir. Soenjoto Sumodihardjo.', 'unb.ac.id'),
(31, 'Universitas Terbuka', '4 September 1984', 'Banten', 'Unggul', 'universitas', 'images/section2/logo univ/UT.png', 'Universitas Terbuka (UT) adalah Perguruan Tinggi Negeri ke-45 di Indonesia yang diresmikan pada tanggal 4 September 1984, berdasarkan Keputusan Presiden RI Nomor 41 Tahun 1984. Universitas ini mengusung pembelajaran non tatap muka atau melalui internet. Saat ini, UT memiliki 4 Fakultas, yaitu Fakultas Ekonomi, Fakultas Ilmu Sosial dan Ilmu Politik, Fakultas Matematika dan Ilmu Pengetahuan Alam, Fakultas Keguruan dan Ilmu Pendidikan untuk jenjang Diploma dan Sarjana. Selain jenjang pendidikan tersebut, UT juga membuka jenjang Magister dan Doktor pada Program Pascasarjana.', 'ut.ac.id'),
(32, 'Universitas Negeri Padang', '23 Oktober 1954', 'Sumatera Barat', 'Unggul', 'universitas', 'images/section2/logo univ/UNP.png', 'Universitas Negeri Padang (UNP) adalah perguruan tinggi negeri yang berlokasi di Padang, Sumatera Barat, Indonesia. Universitas ini berdiri pada 23 Oktober 1954. Pada 2011, UNP menjadi salah satu dari 28 Perguruan Tinggi Negeri lainnya yang dinobatkan oleh Direktorat Jenderal Pendidikan Tinggi (Ditjen Dikti) sebagai 50 perguruan tinggi yang paling menjanjikan di Indonesia, atau 50 Promising Indonesian Universities. Tidak berhenti sampai di sana, pada tahun 2022, UNP berhasil menjadi top 50 Perguruan Tinggi Negeri (PTN) terbaik Indonesia versi Webometrics pada tahun 2022, dan top 5 Universitas Terbaik menurut Scimago Institutions Rankings 2022.', 'unp.ac.id'),
(33, 'Universitas Negeri Malang', '18 Oktober 1954', 'Jawa Timur', 'Unggul', 'universitas', 'images/section2/logo univ/UM.png', 'Universitas Negeri Malang (UM) merupakan perguruan tinggi negeri yang terletak di Malang dan Blitar, Jawa Timur, Indonesia. Universitas yang didirikan pada tanggal 18 Oktober 1954 ini, sebelumnya bernama Perguruan Tinggi Pendidikan Guru Malang, salah satu IKIP tertua di Indonesia. Universitas Negeri Malang termasuk dalam 50 universitas unggulan Direktorat Jenderal Pendidikan Tinggi. Pada tahun 2010, universitas ini berhasil meraih peringkat 6 universitas terbaik di Indonesia versi Webometric, dan pada tahun 2014, UM mendapat akreditasi A.', 'um.ac.id'),
(34, 'Universitas Pendidikan Indonesia', '20 Oktober 1954', 'Jawa Barat', 'Unggul', 'universitas', 'images/section2/logo univ/UPI.png', 'Universitas Pendidikan Indonesia (UPI) adalah perguruan tinggi negeri yang kampus utamanya berkedudukan di Kota Bandung, Jawa Barat, Indonesia. Universitas ini, pertama kali didirikan pada tahun 1954, berawal dari sebuah Perguruan Tinggi Pendidikan Guru yang telah mengalami metamorfosis hingga menjadi salah satu Perguruan Tinggi Negeri Berbadan Hukum di Indonesia. Berdasarkan data Webometrics pada Juli 2020, UPI berada di posisi ke-15 dari 50 Perguruan Tinggi Negeri (PTN) maupun Perguruan Tinggi Swasta (PTS) terbaik Indonesia. Kampus ini juga mendapat penghargaan internasional, yaitu menjadi TOP 300 Universitas di Bidang Pendidikan berdasarkan pemeringkatan oleh QS World University Ranking 2020.', 'upi.ac.id'),
(35, 'Universitas Negeri Manado', '22 September 1955', 'Sulawesi Utara', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNIMA.png', 'Universitas Negeri Manado (UNIMA) adalah Perguruan Tinggi Negeri yang ada di Tondano, Sulawesi Utara. UNIMA berdiri pada tanggal 22 September 1955. Sebelumnya, universitas ini pertama kali didirikan pada tahun 1955 sebagai Perguruan Tinggi Pendidikan Guru (PTPG), lalu mengalami perubahan bentuk menjadi Institut Keguruan dan Ilmu Pendidikan (IKIP) Negeri Manado di tahun 1965, dan resmi bertransformasi menjadi Universitas Negeri Manado (UNIMA) di tahun 2000. Hingga saat ini, UNIMA memiliki lebih dari 30 program studi kependidikan untuk jenjang Sarjana dan Pascasarjana.', 'unima.ac.id'),
(36, 'Universitas Negeri Makassar', '1 Agustus 1961', 'Sulawesi Selatan', 'Unggul', 'universitas', 'images/section2/logo univ/UNM.png', 'Universitas Negeri Makassar (UNM) adalah perguruan tinggi negeri di Makassar, Indonesia, yang berdiri pada 1 Agustus 1961. Awalnya universitas ini merupakan Fakultas Keguruan dan Ilmu Pendidikan (FKIP) dari Universitas Hasanuddin Makassar. Saat ini, Universitas Negeri Makassar telah mengalami banyak perkembangan. Universitas ini memiliki 9 fakultas yang menaungi 9 program studi untuk jenjang D3, 58 program studi untuk jenjang S1, 12 program studi untuk jenjang S2, dan 5 program studi untuk jenjang S3.', 'unm.ac.id'),
(37, 'Universitas Negeri Jakarta', '16 Mei 1964', 'DKI Jakarta', 'Unggul', 'universitas', 'images/section2/logo univ/UNJ.png', 'Universitas Negeri Jakarta (UNJ) adalah perguruan tinggi negeri yang terdapat di Kota Jakarta, Indonesia. Sebelumnya, universitas ini bernama Institut Keguruan dan Ilmu Pendidikan Jakarta (IKIP Jakarta). Lalu, berdasarkan Keputusan Presiden RI Nomor 93 Tahun 1999, tanggal 4 Agustus 1999, IKIP Jakarta ditetapkan dengan nama baru, yaitu Universitas Negeri Jakarta (UNJ). Dengan menyediakan beragam pilihan program studi, Universitas Negeri Jakarta berhasil menjadi salah satu kampus pilihan yang banyak diincar oleh para pelajar, baik dari Jakarta maupun luar kota.', 'unj.ac.id'),
(38, 'Universitas Negeri Yogyakarta', '21 Mei 1964', 'Daerah Istimewa Yogyakarta', 'Unggul', 'universitas', 'images/section2/logo univ/UNY.png', 'Universitas Negeri Yogyakarta (UNY) merupakan perguruan tinggi negeri yang didirikan pada tanggal 21 Mei 1964. Awalnya, UNY merupakan bagian dari Universitas Gajah Mada (UGM), yaitu Fakultas Pedagogik (FP) yang didirikan pada tanggal 19 September !955. Fakultas ini kemudian dipecah menjadi tiga fakultas pada tanggal 2 Februari 1962, yaitu Fakultas Ilmu Pendidikan (FIP), Fakultas Pendidikan Djasmani (FPD), dan Fakultas Keguruan dan ilmu Pendidikan (FKIP). Pada tahun 2022, UNY meraih posisi 6 dari 576 universitas terbaik di Indonesia dan peringkat 65 di tingkat Asia versi lembaga pemeringkatan perguruan tinggi tingkat internasional University Ranking (UniRank).', 'uny.ac.id'),
(39, 'Universitas Negeri Surabaya', '19 Desember 1964', 'Jawa Timur', 'Unggul', 'universitas', 'images/section2/logo univ/UNESA.png', 'Universitas Negeri Surabaya (UNESA) adalah Perguruan Tinggi Negeri yang terletak di Surabaya, Jawa Timur, Indonesia. UNESA didirikan pada tanggal 19 Desember 1964, dan sebelumnya bernama IKIP Surabaya. Saat ini, Universitas Negeri Surabaya mengelola 10 program studi jenjang Diploma, 61 program studi jenjang Strata, 16 program studi jenjang Pascasarjana (Magister), dan 6 program studi jenjang Doktor. Hingga kini, UNESA tetap menjalankan misi utamanya, yaitu menyelenggarakan program kependidikan dan program non-kependidikan, sebagai penghasil tenaga kependidikan untuk pendidikan prasekolah, pendidikan dasar, dan pendidikan menengah.', 'unesa.ac.id'),
(40, 'Universitas Negeri Medan', '23 Juni 1963', 'Sumatera Utara', 'Unggul', 'universitas', 'images/section2/logo univ/UNIMED.png', 'Universitas Negeri Medan (Unimed) adalah perguruan tinggi negeri yang didirikan pada tanggal 23 Juni 1963 di Medan, Sumatra Utara. Awalnya, universitas ini didirikan pada tahun 1956 sebagai Perguruan Tinggi Pendidikan Guru (PTPG) oleh beberapa tokoh pendidikan di Sumatra Utara. Tujuannya, untuk memenuhi kebutuhan tenaga kependidikan yang berkualitas di Sumatra Utara bagi para lulusan sekolah Menengah atas (SMA) dan sederajat. Setelah diresmikan, UNIMED telah mengalami berbagai perkembangan juga prestasi. UNIMED berhasil memperoleh Akreditasi Universitas oleh Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT) No.1067/SK/BAN-PT/Ak-PPJ/PT/XII/2021 mendapatkan peringkat Akreditasi A (Sangat Baik).', 'unimed.ac.id'),
(41, 'Universitas Negeri Semarang', '14 September 1965', 'Jawa Tengah', 'Unggul', 'universitas', 'images/section2/logo univ/UNNES.png', 'Universitas Negeri Semarang (UNNES) adalah perguruan tinggi negeri, yang kampus utamanya berlokasi di daerah Sekaran (Gunungpati), wilayah selatan Kota Semarang, Jawa Tengah, serta kampus lain yang terletak di Ngaliyan, Kelud, Bendan Ngisor, dan Kemandungan, Tegal. Sebelumnya, UNNES merupakan sebuah Perguruan Tinggi Keguruan (IKIP) Semarang. Pada tanggal 20 Oktober 2022, UNNES menjadi universitas negeri badan hukum (PTN-BH) berdasarkan Peraturan Pemerintah Republik Indonesia No. 36 tahun 2022, yang ditandatangani oleh Presiden Ir. Joko Widodo. UNNES berhasil menduduki peringkat 8 kampus terbaik di Indonesia dan 476 dunia, berdasarkan subjek pendidikan menurut Scimago Institutions Rankings (SIR) tahun 2022.', 'unnes.ac.id'),
(42, 'Universitas Sultan Ageng Tirtayasa', '1 Oktober 1981', 'Banten', 'Unggul', 'universitas', 'images/section2/logo univ/UNTIRTA.png', 'Universitas Sultan Ageng Tirtayasa (UNTIRTA) adalah perguruan tinggi negeri yang berlokasi di Provinsi Banten, Indonesia. Awal mula berdirinya, ditandai dengan beroperasionalnya Yayasan Pendidikan Tirtayasa pada tanggal 1 Oktober 1980 berdasarkan Akte Notaris No: 1 Tahun 1980. Kata Tirtayasa (Bahasa Sansekerta yang berarti Air Mengalir), diambil dari nama Pahlawan Nasional yang berasal dari Banten, yaitu Sultan Ageng Tirtayasa. Dalam perkembangan berikutnya, berdasarkan Keputusan Presiden RI Nomor: 32 tanggal 19 maret 2001, Universitas Sultan Ageng Tirtayasa secara resmi ditetapkan menjadi Perguruan Tinggi Negeri definitif.', 'untirta.ac.id'),
(43, 'Universitas Trunojoyo Madura', '23 Juli 2001', 'Jawa Timur', 'Unggul', 'universitas', 'images/section2/logo univ/UTM.png', 'Universitas Trunojoyo Madura (UTM) merupakan perguruan tinggi negeri yang terletak di Kabupaten Bangkalan, Jawa Timur. UTM didirikan pada tahun 2001 berdasarkan Keputusan Presiden Republik Indonesia Nomor 85 Tahun 2001. UTM merupakan kelanjutan dari Universitas Bangkalan Madura (Unibang), yang sebelumnya merupakan perguruan tinggi swasta. UTM memiliki luas lahan sekitar 30 hektar dan terletak di lingkungan pusat pengembangan Bangkalan sebagai perluasan kota Surabaya dalam satuan wilayah pengembangan Gerbangkertasusila. Kampus UTM dikelilingi oleh persawahan dan hutan lindung, sehingga memiliki suasana yang asri dan nyaman.', 'utm.ac.id'),
(44, 'Universitas Khairun', '15 Agustus 1964', 'Maluku Utara', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNKHAIR.png', 'Universitas Khairun (UNKHAIR) adalah Perguruan Tinggi Negeri di Provinsi Maluku Utara. Sejak berdirinya pada tahun 1964 hingga saat ini, UNKHAIR terus berperan aktif dalam mengembangkan ilmu pengetahuan, teknologi, dan seni, baik dibidang pendidikan, penelitian, dan pengabdian kepada masyarakat. UNKHAIR selalu meningkatkan kualitas pendidikannya, agar terus maju dan menghasilkan output yang berkualitas dalam berbagai aspek penyelenggaraan pendidikan.', 'unkhair.ac.id'),
(45, 'Universitas Papua', '3 November 2000', 'Papua Barat', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNIPA.png', 'Universitas Papua (UNIPA) adalah perguruan tinggi negeri yang berada di Manokwari, Papua Barat, Indonesia. Universitas Papua didirikan pada tanggal 3 November 2000, dan peresmiannya baru dilakukan oleh Direktur Jenderal Pendidikan Tinggi atas nama Menteri Pendidikan Nasional pada hari Sabtu, tanggal 28 Juli 2011. Pada tanggal 17 Oktober 2014, Universitas Negeri Papua berganti nama menjadi Universitas Papua berdasarkan Peraturan Presiden (PERPRES) Republik Indonesia Nomor 155 Tahun 2014. Saat ini, Universitas Papua memiliki 3 Kampus Unggulan di Provinsi Papua Barat.', 'unipa.ac.id'),
(46, 'Universitas Malikussaleh', '12 Juni 1969', 'Aceh', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNIMAL.png', 'Universitas Malikussaleh (UNIMAL) merupakan Perguruan Tinggi Negeri di pantai Timur-Utara Aceh, dimana kampus utamanya sekarang berada di Reuleuet, Kabupaten Aceh Utara, Aceh, Indonesia. Universitas ini didirikan dengan mengambil nama besar Raja Kerajaan Samudera Pasai pertama, yang dilandasi dari sifat kepemimpinan dan patriotismenya. Unimal terkenal dengan julukannya, The Blessing University. Julukan ini diberikan berkat komitmen kampus dalam menjalankan prinsip-prinsip kemanusiaan yang universal, berdasarkan nilai-nilai kearifan lokal dan Syariat Islam.', 'unimal.ac.id'),
(47, 'Universitas Negeri Gorontalo', '1 September 1963', 'Gorontalo', 'Unggul', 'universitas', 'images/section2/logo univ/UNG.png', 'Universitas Negeri Gorontalo (UNG) merupakan universitas yang dikembangkan atas dasar perluasan mandat (wider mandate) dari IKIP Negeri Gorontalo. Perubahan IKIP Negeri Gorontalo menjadi Universitas Negeri Gorontalo ditetapkan dengan surat Keputusan Presiden RI nomor 54 tahun 2004 tanggal 23 Juni 2004. Seiring perkembangannya, UNG kini memiliki 10 fakultas dan 1 program pascasarjana.', 'ung.ac.id'),
(48, 'Universitas Pendidikan Ganesha', '11 Mei 2006', 'Bali', 'Unggul', 'universitas', 'images/section2/logo univ/UNDIKSHA.png', 'Universitas Pendidikan Ganesha (UNDIKSHA) adalah perguruan tinggi negeri yang berlokasi di Kota Singaraja, Bali, Indonesia. Universitas ini sebenarnya baru resmi berdiri pada tahun 2006, namun sejarah perjalanannya sudah dimulai sejak tahun 1950-an, guna memenuhi kebutuhan guru di Indonesia. Hingga kini, Universitas Pendidikan Ganesha sudah mengelola 6 fakultas dan 3 program studi Pascasarjana.', 'undiksha.ac.id'),
(49, 'Universitas Bangka Belitung', '12 April 2006', 'Bangka Belitung', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UBB.png', 'Kehadiran Universitas Bangka Belitung (UBB) adalah cita-cita yang telah lama mengakar dalam diri masyarakat Serumpun Sebalai. Ide pembentukan UBB telah menjadi pre Determinant dari pembentukan Provinsi. Impian yang telah dipetakan jauh-jauh hari sebelumnya provinsi Bangka Belitung lahir dan semakin mengemuka seiring dengan pembentukan provinsi Bangka Belitung berdasarkan Undang-Undang Republik Indonesia Nomor 27 Tahun 2000 Tentang Pembentukan Provinsi Kepulauan Bangka Belitung, pada tanggal 21 November 2000.', 'ubb.ac.id'),
(50, 'Universitas Borneo Tarakan', '9 Oktober 1999', 'Kalimantan Utara', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UBT.png', 'Universitas Borneo Tarakan (UBT) merupakan Perguruan Tinggi Negeri yang berkedudukan di Kota Tarakan yang terletak di wilayah Utara Propinsi Kalimantan Timur, dan merupakan salah satu beranda Negara Kesatuan Republik Indonesia. Universitas Borneo Tarakan juga terletak pada wilayah perbatasan Indonesia dengan Malaysia-Sabah, yang secara geo-politik dan geo-ekonomi memiliki peranan penting. Faktor geografis di posisi perbatasan ini akan sangat menentukan kesan kuat bagi negara tetangga terhadap gambaran kondisi pendidikan di Indonesia.', 'ubt.ac.id'),
(51, 'Universitas Musamus Merauke', '22 November 2010', 'Papua Selatan', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNMUS.png', 'Universitas Musamus Merauke (UNMUS) adalah perguruan tinggi negeri di Kota Merauke, Provinsi Papua Selatan, yang berdiri pada tanggal 22 November 2010. Universitas ini merupakan peralihan status dari Sekolah Tinggi Teknik (STT) Merauke menjadi Universitas Musamus Merauke. Pendirian universitas ini, bermula dari adanya kebutuhan masyarakat Kabupaten Merauke akan pendidikan tinggi yang dapat meningkatkan kualitas sumberdaya manusia di wilayah Selatan Papua, khususnya Kabupaten Merauke dan sekitarnya. Tujuannya agar mampu menumbuhkembangkan potensi di wilayah Merauke.', 'unmus.ac.id'),
(52, 'Universitas Maritim Raja Ali Haji', '1 Agustus 2007', 'Kepulauan Riau', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UMRAH.png', 'Universitas Maritim Raja Ali Haji (UMRAH) adalah perguruan tinggi negeri di Kota Tanjungpinang, Provinsi Kepulauan Riau, yang berdiri pada tanggal 1 Agustus 2007. Universitas ini merupakan gabungan dari 2 perguruan tinggi swasta, yaitu Sekolah Tinggi Ilmu Sosial dan Ilmu Politik (Stisipol) Raja Haji Fisabilillah Tanjungpinang dan Politeknik Negeri Batam. UMRAH berlokasi di sebuah kampus baru di Pulau Dompak, dengan rektor pertamanya adalah Prof. Dr. Maswardi M. Amin, M.Pd.', 'umrah.ac.id'),
(53, 'Universitas Samudra', '1 Mei 1972', 'Aceh', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNSAM.png', 'Universitas Samudra (UNSAM) adalah perguruan tinggi negeri yang terdapat di Kota Langsa, Aceh, Indonesia. Universitas ini telah dirintis pendiriannya sejak tahun 1963, ketika Al-Jamiatul Wasliyah cabang Aceh Timur berinisiatif mendirikan sebuah lembaga perguruan tinggi, yaitu Fakultas Ekonomi yang berafiliasi pada Universitas Al Washliyah Medan. Berawal dari sebuah yayasan, akhirnya Universitas Samudra resmi menjadi PTN pada tahun 2013. Saat ini, Universitas Samudra memiliki 5 fakultas dan 25 program studi.', 'unsam.ac.id'),
(54, 'Universitas Sulawesi Barat', '31 November 2007', 'Sulawesi Barat', 'Baik', 'universitas', 'images/section2/logo univ/UNSULBAR.png', 'Universitas Sulawesi Barat (UNSULBAR) adalah Perguruan Tinggi Negeri yang terdapat di Majene, Sulawesi Barat. Universitas Sulawesi Barat memperoleh izin operasional melalui Keputusan Menteri Pendidikan dan Kebudayaan Nomor: 229/D/0/2007 tanggal 31 November 2007, yang dikelola oleh Yayasan Pendidikan Indonesia Sulawesi Barat, di bawah koordinasi Kopertis Wilayah IX Sulawesi. Pada tanggal 13 Mei 2013, Universitas Sulawesi Barat berubah status dari Perguruan Tinggi Swasta (PTS) menjadi Perguruan Tinggi Negeri (PTN) melalui Peraturan Presiden Republik Indonesia Nomor: 36 Tahun 2013 tentang Pendirian Sulawesi Barat.', 'unsulbar.ac.id'),
(55, 'Universitas Sembilanbelas November', '16 April 1984', 'Sulawesi Tenggara', 'Baik', 'universitas', 'images/section2/logo univ/USN.png', 'Universitas Sembilanbelas November Kolaka (USN) adalah perguruan tinggi negeri yang berlokasi di Kabupaten Kolaka, Sulawesi Tenggara. Universitas ini berdiri pada tanggal 16 April 1984, dan menjadi universitas negeri pertama di Kabupaten Kolaka. Nama USN diambil dari Peristiwa penyergapan konvoi tentara NICA, tanggal 19 November tahun 1945 yang pernah terjadi di Kolaka. Hingga kini, USN telah mengelola 4 fakultas dengan 12 program studi.', 'usn.ac.id'),
(56, 'Universitas Tidar', '17 Juli 1979', 'Jawa Tengah', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNTIDAR.png', 'Universitas Tidar (UNTIDAR) adalah Perguruan Tinggi Negeri yang telah ditetapkan berdasarkan Peraturan Presiden Republik Indonesia Nomor 23 Tahun 2014 pada tanggal 1 April 2014. Universitas ini merupakan perubahan status Universitas Tidar Magelang (UTM) yang didirikan berdasarkan Keputusan Koordinator Perguruan Tinggi Swasta Wilayah V Nomor 032/SK/Kpts/VII/1979. Hingga kini, UNTIDAR mengelola 5 fakultas dengan 30 program studi. Seluruh program studi yang diselenggarakan Universitas Tidar telah mendapatkan status terakreditasi dari Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).', 'untidar.ac.id'),
(57, 'Universitas Siliwangi', '20 Mei 1978', 'Jawa Barat', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNSIL.png', 'Universitas Siliwangi (UNSIL) adalah perguruan tinggi negeri yang berlokasi di Kota Tasikmalaya, Jawa Barat. Universitas Siliwangi menjadi universitas terbesar di Priangan Timur. Universitas Siliwangi mengalami perubahan status kelembagaan dari perguruan tinggi swasta menjadi perguruan tinggi negeri melalui Peraturan Presiden Republik Indonesia Nomor 24 Tahun 2014, yang diresmikan oleh Mantan Presiden RI, Susilo Bambang Yudhoyono.', 'unsil.ac.id'),
(58, 'Universitas Teuku Umar', '10 November 2006', 'Aceh', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UTU.png', 'Universitas Teuku Umar (UTU) adalah perguruan tinggi negeri yang berlokasi di Kota Meulaboh, Kabupaten Aceh Barat, Provinsi Aceh. Universitas ini berawal dari pembentukan Yayasan Pendidikan Teungku Dirundeng Meulaboh pada tahun 1984. Pada tanggal 14 Maret 2014, Presiden Susilo Bambang Yudhoyono menandatangani Keppres Penegerian Universitas Teuku Umar. Nama Teuku Umar sendiri, diambil dari nama seorang pahlawan nasional Indonesia yang berasal dari Meulaboh Aceh Barat.', 'utu.ac.id'),
(59, 'Universitas Pembangunan Nasional \"Veteran\" Jawa Timur', '5 Juli 1959', 'Jawa Timur', 'Unggul', 'universitas', 'images/section2/logo univ/UPNVJT.png', 'Universitas Pembangunan Nasional Veteran Jawa Timur merupakan perguruan tinggi negeri yang berada di Surabaya, Jawa Timur dan sudah berdiri sejak tahun 1959 dengan nama Akademi Administrasi Perusahaan Veteran Cabang Surabaya. UPN Veteran Jawa Timur sendiri memiliki sejarah yang cukup panjang dalam dunia pendidikan.<br/><br/>Saat ini UPN Veteran Jawa Timur telah bertransformasi menjadi perguruan tinggi yang modern dengan berbagai fasilitas kampus yang menunjang berbagai kebutuhan mahasiswa, mulai dari lapangan sepak bola, lapangan tenis bahkan kolam renang.<br/><br/>Pada pengujung tahun 2022, kurang lebih 59.112 orang sarjana telah lulus dari UPN Veteran Jawa Timur serta ada 1.243 orang lulusan program magister.', 'upnjatim.ac.id'),
(60, 'Universitas Timor', '16 Juni 2000', 'Nusa Tenggara Timur', 'Baik', 'universitas', 'images/section2/logo univ/UNIMOR.png', 'Universitas Timor (UNIMOR) adalah perguruan tinggi negeri yang terletak di Kota Kefamenanu, Kabupaten Timor Tengah Utara, Provinsi Nusa Tenggara Timur. UNIMOR berkomitmen untuk menghasilkan lulusan yang berkualitas dan memiliki daya saing tinggi yang dapat bersaing secara nasional maupun internasional. UNIMOR juga adalah universitas yang mememiliki keinginan untuk menjadi pusat ilmu pengetahuan, teknologi, humaniora dan seni yang unggul dalam bidang pertanian lahan kering yang mandiri dan bermartabat pada tingkat regional, nasional, dan internasional pada tahun 2025. UNIMOR juga berkomitmen untuk memberikan kontribusi bagi pembangunan di Provinsi Nusa Tenggara Timur.', 'unimor.ac.id'),
(61, 'Universitas Pembangunan Nasional \"Veteran\" Jakarta', '21 Februari 1967', 'DKI Jakarta', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UPNVJ.png', 'Universitas Pembangunan Nasional Veteran Jakarta atau lebih dikenal dengan sebutan UPN Veteran Jakarta merupakan salah satu universitas yang terletak di DKI Jakarta. Meskipun, beberapa fakultasnya berada di daerah Tangerang Selatan dan Depok.<br/><br/>Pada awalnya, UPN Veteran Jakarta merupakan kampus swasta. Tapi, sejak 6 Oktober 2014, UPN Veteran Jakarta telah menjadi kampus negeri.<br/><br/>UPN Veteran Jakarta memiliki banyak fasilitas yang menunjang kegiatan dan pembelajaran mahasiswa, misalnya seperti perpustakaan, pusat bahasa, mash classroom, dan lain-lain. Di samping itu, mahasiswa juga dapat mengikuti beragam Unit Kegiatan Mahasiswa (UKM) seperti basket, bulutangkis, fotografi, jujitsu, paduan suara, resimen mahasiswa, teater, dan masih banyak lagi.', 'upnvj.ac.id'),
(62, 'Universitas Pembangunan Nasional \"Veteran\" Yogyakarta', '15 Desember 1958', 'Daerah Istimewa Yogyakarta', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UPNVYK.png', 'Universitas Pembangunan Nasional \"Veteran\" Yogyakarta (UPNYK) adalah perguruan tinggi negeri yang berlokasi di Daerah Istimewa Yogyakarta. UPNYK didirikan pada tahun 1958 dengan nama Akademi Pembangunan Nasional (APN). Pada saat itu, APN hanya memiliki tiga jurusan, yaitu Akuntansi, Administrasi Negara, dan Teknik Sipil.<br/><br/>Pada tahun 1965, APN berubah status menjadi Institut Teknologi Pembangunan Nasional (ITPN). Pada tahun 1973, ITPN berubah status menjadi Universitas Pembangunan Nasional (UPN) \"Veteran\" Yogyakarta. UPNYK berkomitmen untuk mewujudkan pendidikan berkualitas dalam bidang ilmu pengetahuan, teknologi, dan bisnis. UPNYK juga fokus pada inovasi, penelitian, dan pengabdian masyarakat. Dengan fokus tersebut, UPNYK mendorong pengembangan potensi individu dan memberikan kontribusi positif bagi kemajuan Indonesia melalui semangat bela negara.', 'upnyk.ac.id'),
(63, 'Universitas Singaperbangsa Karawang', '2 Februari 1982', 'Jawa Barat', 'Baik Sekali', 'universitas', 'images/section2/logo univ/UNSIKA.png', 'Universitas Singaperbangsa Karawang (UNSIKA) adalah perguruan tinggi negeri yang berlokasi di Kabupaten Karawang, Jawa Barat. UNSIKA didirikan pada tanggal 2 Februari 1982 oleh Yayasan Pembina Perguruan Tinggi Pangkal Perjuangan. Sejak tanggal 6 Oktober 2014, UNSIKA beralih status menjadi perguruan tinggi negeri, sesuai dengan Perpres RI Nomor 123 tahun 2014 tentang Pendirian Universitas Singaperbangsa Karawang. Pada tahun 2022, Universitas Singaperbangsa Karawang berada di peringkat 84 nasional dalam Affiliations by Overall SINTA Score.', 'unsika.ac.id'),
(64, 'Institut Teknologi Bandung', '3 Juli 1920', 'Jawa Barat', 'Unggul', 'institut', 'images/section2/logo univ/ITB.png', 'Institut Teknologi Bandung (ITB) merupakan sekolah tinggi teknik pertama di Indonesia yang didirikan pada tanggal 2 Maret 1959 di Jawa Barat yang mengemban misi pengabdian ilmu pengetahuan dan teknologi untuk memajukan Indonesia. Lahir dalam suasana penuh dinamika yang dilandasi dengan semangat perjuangan Proklamasi Kemerdekaan, ITB hadir untuk mengoptimalkan pembangunan bangsa yang maju dan bermartabat.', 'itb.ac.id'),
(65, 'Institut Teknologi Sepuluh Nopember', '10 November 1957', 'Jawa Timur', 'Unggul', 'institut', 'images/section2/logo univ/ITS.png', 'Institut Teknologi Sepuluh Nopember (ITS) melekat dengan sejarah perjuangan kemerdekaan Republik Indonesia. Pendirian ITS dipelopori oleh para pejuang kemerdekaan Republik Indonesia sejak tahun 1957, melibatkan dr. Angka Nitisastro, Soedjasmono, Kyai Haji Yahya Hasyim, dan didukung oleh Roeslan Abdulgani. Motto baru untuk semangat baru', 'its.ac.id'),
(66, 'Institut Pertanian Bogor', '1 September 1963', 'Jawa Barat', 'Unggul', 'institut', 'images/section2/logo univ/IPB.png', 'IPB University, sebelumnya bernama Institut Pertanian Bogor adalah perguruan tinggi negeri yang berlokasi di Bogor, Jawa Barat. Awalnya, IPB merupakan fakultas pertanian dari Universitas Indonesia. Namun, pada tahun 1963, IPB resmi lepas dari Universitas Indonesia dan berdiri sendiri menjadi sebuah institut pertanian. IPB dibentuk dari beberapa lembaga pendidikan menengah dan tinggi pertanian serta kedokteran hewan, yaitu Middelbare Landbouwschool, Middelbare Bosbouwschool, dan Nederlandsch Indische Veeartsenschool.', 'ipb.ac.id'),
(67, 'Institut Seni Indonesia Yogyakarta', '30 Mei 1984', 'Daerah Istimewa Yogyakarta', 'Unggul', 'institut', 'images/section2/logo univ/ISI Yogyakarta.png', 'Institut Seni Indonesia Yogyakrata atau dikenal dengan ISI Jogja adalah sebuah lembaga pendidikan tinggi seni negeri yang berstatus perguruan tinggi penuh, dan memiliki kewenangan untuk menyelenggarakan pendidikan sampai ke jenjang tertinggi dan merupakan perguruan tinggi seni terbesar & terbaik di Indonesia. ISI Jogja dibentuk atas Keputusan Presiden RI No: 39/1984 tanggal 30 Mei 1984, dan diresmikan berdirinya oleh Menteri Pendidikan dan Kebudayaan, Prof. Dr. Nugroho Notosusanto, pada tanggal 23 Juli 1984.', 'isi.ac.id'),
(68, 'Institut Seni Indonesia Bali', '28 Januari 1967', 'Bali', 'Unggul', 'institut', 'images/section2/logo univ/ISI Bali.png', 'Institut Seni Indonesia Denpasar atau biasanya disingkat ISI Denpasar adalah perguruan tinggi negeri yang didirikan di kota denpasar, Bali, pada 28 Juli 2003 di bawah Kementerian Pendidikan dan Kebudayaan. ISI Denpasar merupakan hasil integrasi dari Sekolah Tinggi Seni Indonesia Denpasar (STSI) dan Program Studi Seni Rupa dan Desain (PSSRD) Universitas Udayana yang dibentuk berdasarkan Keputusan Presiden Republik Indonesia Nomor 33 Tahun 2003.', 'isi-dps.ac.id'),
(69, 'Institut Seni Indonesia Surakarta', '15 Juli 1964', 'Jawa Tengah', 'Baik Sekali', 'institut', 'images/section2/logo univ/ISI Surakarta.png', 'Institut Seni Indonesia Surakarta atau ISI Surakarta adalah sebuah perguruan tinggi negeri yang berada di Jebres, Kota Surakarta. ISI Surakarta merupakan satu dari tujuh institut seni yang ada di Indonesia. ISI Surakarta memiliki dua fakultas yaitu Fakultas Seni Pertunjukan dan Fakultas Seni Rupa dan Desain yang berlokasi di dua kampus, yakni Kampus Kentingan (Kampus Pusat dan FSP) serta Kampus Mojosongo (FSRD).', 'isi-ska.ac.id'),
(70, 'Institut Seni Indonesia Padang Panjang', '22 Desember 1965', 'Sumatera Barat', 'Baik Sekali', 'institut', 'images/section2/logo univ/ISI Padang Panjang.png', 'Institut Seni Indonesia Padang Panjang adalah perguruan tinggi negeri yang terletak di kota Padang Panjang, Sumatera Barat. Dalam rangka menciptakan lulusan yang berkualitas, ISI Padangpanjang telah berupaya membuka program studi sesuai dengan pembangunan sumber daya manusia. Hal ini bertujuan agar para lulusannya mampu berkompetisi untuk mendapatkan lapangan kerja dan mereka dituntut melakukan berbagai aktivitas dan kreativitas seni dalam rangka menantang masa depan yang semakin sulit, sehingga era globalisasi dapat menjanjikan prospek yang positif bagi sarjana seni ISI Padangpanjang pada masa-masa yang akan datang.', 'isi-padangpanjang.ac.id'),
(71, 'Institut Seni Budaya Indonesia Bandung', '31 Maret 1968', 'Jawa Barat', 'Baik Sekali', 'institut', 'images/section2/logo univ/ISBI Bandung.png', 'Institut Seni Budaya Indonesia Bandung, yang selanjutnya disebut ISBI Bandung adalah perguruan tinggi negeri yang menyelenggarakan program pendidikan akademik dan dapat menyelenggarakan program pendidikan vokasi dalam berbagai rumpun ilmu pengetahuan dan/atau teknologi, serta jika memenuhi syarat dapat menyelenggarakan pendidikan profesi.<br/><br/>Saat ini Institut Seni Budaya Indonesia Bandung memiliki 3 Fakultas dan 1 Program Pascasarjana yang menyelenggarakan pendidikan vokasi D3 dan D4, program sarjana (S1), dan program magister (S2).', 'isbi.ac.id'),
(72, 'Institut Seni Budaya Indonesia Aceh', '6 Oktober 2014', 'Aceh', 'Baik', 'institut', 'images/section2/logo univ/ISBI Aceh.png', 'Institut Seni Budaya Indonesia Aceh atau disebut ISBI Aceh adalah perguruan tinggi yang menyelenggarakan pendidikan akademik dan dapat menyelenggarakan pendidikan vokasi serta jika memenuhi syarat dapat menyelenggarakan pendidikan profesi di bidang seni dan budaya.', 'isbiaceh.ac.id');
INSERT INTO `data_kampus` (`id`, `nama`, `tanggal_berdiri`, `lokasi`, `akreditas`, `tipe`, `logo`, `deskripsi`, `website`) VALUES
(73, 'Institut Seni Budaya Indonesia Tanah Papua', '09 Oktober 2014', 'Papua', 'Baik', 'institut', 'images/section2/logo univ/ISBI Tanah Papua.png', 'Institut Seni Budaya Indonesia (ISBI) Tanah Papua adalah perguruan tinggi negeri seni yang berdiri pada tahun 2014 dan berada di bawah Kementerian Pendidikan dan Kebudayaan. Pendirian kampus ini merupakan salah satu bentuk kepedulian pemerintah dalam mengembangkan potensi bidang seni dan budaya yang sangat beragam, khususnya di wilayah Papua. Saat ini, ISBI Tanah Papua memiliki 5 program studi jenjang sarjana (S1), yakni Seni Tari, Seni Musik, Seni Rupa Murni, Desain Komunikasi Visual, dan Kriya Seni.', 'isbi-tanahpapua.ac.id'),
(74, 'Institut Teknologi Kalimantan', '6 Oktober 2014', 'Kalimantan Timur', 'Baik Sekali', 'institut', 'images/section2/logo univ/ITK.png', 'Institut Teknologi Kalimantan merupakan perguruan tinggi yang fokus dalam bidang teknologi untuk menunjang kebutuhan dunia industri. Melalui berbagai macam program pendidikan pada ITK ini, diharapkan dapat meningkatkan pengetahuan dan keterampilan SDM (mahasiswa yang mengambil studi di ITK) yang akan berdampak terhadap peningkatan penguasaan teknologidan peningkatan produktivitas modal. Selanjutnya peningkatan produktivitas modal tersebut mampu memunculkan industri-industri baru sehingga menambah jumlah industri yang ada di Kalimantan.', 'itk.ac.id'),
(75, 'Institut Teknologi Sumatera', '6 Oktober 2014', 'Lampung', 'Baik', 'institut', 'images/section2/logo univ/ITERA.png', 'Institut Teknologi Sumatera, disingkat ITERA, adalah sebuah perguruan tinggi negeri yang terdapat di Provinsi Lampung di Pulau Sumatera. ITERA didirikan berdasarkan Peraturan Presiden Nomor 124 Tahun 2014 tentang Pendirian Institut Teknologi Sumatera (Lembaran Negara Republik Indonesia Tahun 2014 Nomor 253) yang ditetapkan Presiden Republik Indonesia Dr. H. Susilo Bambang Yudhoyono pada tanggal 6 Oktober 2014 dan diundangkan tanggal 9 Oktober 2014.', 'itera.ac.id'),
(76, 'Institut Teknologi Bacharuddin Jusuf Habibie', '17 Oktober 2014', 'Sulawesi Selatan', 'Baik', 'institut', 'images/section2/logo univ/ITH.png', 'Institut Teknologi B.J.Habibie merupakan perguruan tinggi negeri yang berada di Kota Parepare, Sulawesi Selatan. Institut Teknologi B.J. Habibie memiliki tiga program studi, yaitu Matematika, Teknik Informatika dan Sistem Informasi. Saat ini, kampus ITBH telah dilengkapi dengan beberapa fasilitas yang memadai untuk menunjang kebutuhan mahasiswa, diantaranya seperti ruang kuliah, laboratorium komputer, perpustakaan dan fasilitas lainnya.', 'ith.ac.id'),
(77, 'Politeknik Manufaktur Bandung', '24 Maret 1977', 'Jawa Barat', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLMAN.png', 'Politeknik Manufaktur Bandung (Polman Bandung) adalah perguruan tinggi negeri bidang vokasi yang banyak berfokus pada praktik dibandingkan teori dan sudah berdiri sejak tahun 1976.<br/><br/>Politeknik Manufaktur Bandung memiliki keunggulan dalam penerapan sistem belajar yang berbasiskan Production Based Education (PBE) yang disini mahasiswa terlibat secara langsung dengan kegiatan produksi sesuai dengan permintaan industri yang sudah masuk dalam kurikulum pendidikan.', 'polman.ac.id'),
(78, 'Politeknik Negeri Jakarta', '20 September 1982', 'DKI Jakarta', 'Unggul', 'politeknik', 'images/section2/logo univ/PNJ.png', 'Politeknik Negeri Jakarta (PNJ) merupakan perguruan tinggi negeri pendidikan vokasi yang sudah ada sejak tahun 1982 dengan nama Politeknik Universitas Indonesia.<br/><br/>Dalam Politeknik Negeri Jakarta, metode pembelajaran yang diterapkan banyak berfokus pada praktik (rasio 60%) dibandingkan teori (rasio 40%), namun ini sudah berada pada wilayah keseimbangan antara pengetahuan dan keahlian seiring dengan era globalisasi.<br/><br/>Sampai saat ini, Politeknik Negeri Jakarta telah meluluskan sebanyak 35.934 orang, yang terdiri dari 22.764 lulusan bidang rekayasa serta 13.170 lulusan bidang tata niaga.', 'pjn.ac.id'),
(79, 'Politeknik Negeri Medan', '20 September 1982', 'Sumatera Utara', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLMED.png', 'Politeknik Negeri Medan atau Polmed merupakan salah satu kampus yang terletak di Medan, Sumatra Utara. Saat ini, Polmed memiliki mahasiswa sejumlah 6.400 orang, dengan 650 pengajar dan staff.<br/><br/>Polmed yang saat ini berada di dalam lingkungan kampus Universitas Sumatra Utara (USU) memiliki beberapa fasilitas, seperti Laboratorium Komputer di setiap Jurusan, Laboratorium Teknik Sipil, Laboratorium Teknik Mesin, Laboratorium Welding (ATB), Laboratorium Teknik Konversi Energi, perpustakaan, masjid, workshop, dan lain-lain.', 'polmed.ac.id'),
(80, 'Politeknik Negeri Bandung', '27 Januari 1979', 'Jawa Barat', 'Unggul', 'politeknik', 'images/section2/logo univ/POLBAN.png', 'Politeknik Negeri Bandung (Polban) adalah perguruan tinggi negeri vokasi yang berada di bawah naungan Kementerian Riset, Teknologi, dan Pendidikan Tinggi. Polban terletak di Kabupaten Bandung Barat, Provinsi Jawa Barat. Polban menyelenggarakan pendidikan vokasi dalam berbagai bidang ilmu pengetahuan dan teknologi, dan jika memenuhi syarat dapat menyelenggarakan pendidikan profesi.<br/><br/>Polban menyelenggarakan pendidikan vokasi yang berfokus pada keterampilan dan keahlian praktis di berbagai bidang ilmu pengetahuan dan teknologi. Pendidikan vokasi ini bertujuan untuk mempersiapkan lulusan yang siap kerja dan mampu bersaing di dunia industri.', 'polban.ac.id'),
(81, 'Politeknik Negeri Semarang', '06 Agustus 1982', 'Jawa Tengah', 'Unggul', 'politeknik', 'images/section2/logo univ/POLINES.png', 'Politeknik Negeri Semarang, atau POLINES, berada Kecamatan Tembalang, Kota Semarang, Jawa Tengah. Kampus ini menitikberatkan pada jurusan teknik, administrasi, dan akuntansi. Meskipun berstatus sebagai politeknik, institusi negeri ini menawarkan program dari jenjang Diploma 3 (D3) hingga Sarjana (S1). Terdapat 12 program diploma, 14 program sarjana, dan 1 program pasca sarjana.<br/><br/>Polines menyediakan sejumlah beasiswa tetap untuk mahasiswa, seperti Supersemar, PPA, Bantuan Belajar Mahasiswa, Toyota Astra Beasiswa TPSDP, Beasiswa Gubernur Jateng, Bantuan SPP (Polines), Beasiswa SPI, Magang PLN, dan Beasiswa Aktivis.', 'polines.ac.id'),
(82, 'Politeknik Negeri Sriwijaya', '20 September 1982', 'Sumatera Selatan', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLSRI.png', 'POLSRI, institusi pendidikan tinggi negeri, memiliki dua kampus utama di Palembang dan Banyuasin. Dengan 9 jurusan dan 25 program studi, termasuk S2 Terapan, D-IV, dan D-III, POLSRI mendapatkan akreditasi \"Baik Sekali\" hingga 2025 dari BAN-PT.<br/><br/>Didirikan pada 1982 sebagai Politeknik Universitas Sriwijaya, kampus ini aktif berkolaborasi dengan berbagai lembaga, pemerintah, industri, dan mengadakan program pertukaran mahasiswa.', 'polsri.ac.id'),
(83, 'Politeknik Negeri Lampung', '7 April 1984', 'Lampung', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLINELA.png', 'Politeknik Negeri Lampung atau POLINELA dikenal sebagai kampus yang fokus bergerak di bidang pertanian dari jenjang D-II hingga D-III. Meskipun, seiring berjalannya waktu, POLINELA juga memiliki jenjang S-1 Sarjana Terapan (S.Tr.) dan S-2 Terapan (M.Tr.).<br/><br/>Selain prodi-prodi yang berkaitan dengan pertanian, POLINELA saat ini sudah memiliki prodi Ekonomi dan Bisnis.', 'polinela.ac.id'),
(84, 'Politeknik Negeri Ambon', '5 Oktober 1987', 'Maluku', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLNAM.png', 'Politeknik Negeri Ambon (Polnam) adalah perguruan tinggi negeri yang berada di bawah naungan Kementerian Riset, Teknologi, dan Pendidikan Tinggi. Polnam berlokasi di Kota Ambon, Provinsi Maluku. Polnam juga dapat menyelenggarakan pendidikan profesi sesuai dengan ketentuan peraturan perundang-undangan. Pendidikan profesi adalah pendidikan tinggi yang dirancang untuk mempersiapkan peserta didik untuk memiliki kompetensi tertentu yang diakui oleh dunia kerja. Polnam memiliki visi untuk menjadi perguruan tinggi vokasi yang unggul dan berdaya saing di tingkat nasional dan internasional. Polnam juga berkomitmen untuk menghasilkan lulusan yang memiliki kompetensi profesional, berjiwa wirausaha, dan berintegritas.', 'polnam.ac.id'),
(85, 'Politeknik Negeri Padang', '12 Maret 1985', 'Sumatera Barat', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/PNP.jpg', 'Politeknik Negeri Padang (PNP) berlokasi di Kecamatan Pauh, Kota Padang Sumatera Barat. Politeknik Negeri Padang termasuk dalam 50 Perguruan Tinggi Unggulan/terbaik di Indonesia, yang diumumkan oleh Direktorat Jenderal Pendidikan Tinggi (DIKTI) Kementerian Pendidikan Nasional pada tahun 2006. Politeknik Negeri Padang saat ini menawarkan dua puluh empat Program Studi, terdiri dari delapan Program Sarjana Terapan D-4, lima Program Alih Jenjang Sarjana Terapan D-4, dan sebelas Program Diploma Tiga (D-3).', 'pnp.ac.id'),
(86, 'Politeknik Negeri Bali', '3 Desember 1985', 'Bali', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/PNB.png', 'Politeknik Negeri Bali (PNB) merupakan lembaga pendidikan tinggi bidang vokasi yang lebih mengutamakan praktik ketimbang teori dan menerapkan pola tersebut agar bisa menyesuaikan dengan tuntutan industri sehingga para lulusan bisa mengisi kebutuhan industri baik lokal maupun internasional.<br/><br/>Sumber informasi selengkapnya mulai dari visi dan misi kampus sampai informasi akademik dapat diakses pada website resmi Politeknik Negeri Bali.', 'pnb.ac.id'),
(87, 'Politeknik Negeri Pontianak', '3 Desember 1985', 'Kalimantan Barat', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLNEP.png', 'Politeknik Negeri Pontianak atau POLNEP merupakan perguruan tinggi negeri yang berlokasi di Kalimantan Barat. Awalnya politeknik ini bernama Politeknik Universitas Tanjungpura lalu pada tahun 1988, POLNEP mendapatkan status otonomi penuh yang kemudian berganti nama menjadi Politeknik Negeri Pontianak.<br/><br/>POLNEP memiliki 3 lokasi kampus lainnya yaitu PDD Kapuas Hulu, PSDKU Sanggau, dan PSDKU Sukamara. Saat ini terdapat 8 jurusan dengan total 372 pengajar, POLNEP menjamin penyampaian pendidikan yang berkualitas.', 'polnep.ac.id'),
(88, 'Politeknik Negeri Ujung Pandang', '10 Mei 1987', 'Sulawesi Selatan', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/PNUP.png', 'Politeknik Negeri Ujung Pandang (PNUP) adalah sebuah Perguruan Tinggi (PT) Vokasi yang terdapat di Kota Makassar, Sulawesi Selatan yang mengelola 6 Jurusan, diantaranya: Teknik Sipil, Teknik Elektro, Teknik Kimia, Teknik Mesin, Administrasi Niaga dan Akuntansi.', 'pnup.ac.id'),
(89, 'Politeknik Negeri Manado', '9 November 1987', 'Sulawesi Utara', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLIMDO.png', 'Politeknik Negeri Manado terletak di wilayah timur Indonesia, berbatasan langsung dengan negara-negara di kawasan Pasifik. Letak geografis ini dapat menjadi keunggulan bagi Politeknik Negeri Manado di masa depan. Hal ini karena Politeknik Negeri Manado dapat menjadi jembatan penghubung antara Indonesia dengan negara-negara di kawasan Pasifik. Selain itu, Politeknik Negeri Manado juga dapat menghasilkan sumber daya manusia yang berkualitas dan siap bersaing di era global. Politeknik Negeri Manado (Polimdo) adalah perguruan tinggi negeri yang berada di bawah Kementerian Riset, Teknologi, dan Pendidikan Tinggi. Polimdo terletak di Kota Manado, Sulawesi Utara. Polimdo menyelenggarakan pendidikan vokasi dalam berbagai bidang ilmu pengetahuan dan teknologi.', 'polimdo.ac.id'),
(90, 'Politeknik Perkapalan Negeri Surabaya', '1 April 1987', 'Jawa Timur', 'Unggul', 'politeknik', 'images/section2/logo univ/PPNS.png', 'PPNS selalu siap dalam menghadapi persaingan global dan terus berbenah untuk menangkap peluang yang ada. Oleh sebab itu pengembangan SDM terus dilakuan, baik tenaga pendidik maupun tenaga kependidikan melalui pelatihan dan studi lanjut ke jenjang yang lebih tinggi (S3). Peremajaan peralatan laboratorium, penambahan gedung kuliah, penambahan dan pembenahan sarana dan prasarana gedung kuliah juga dilakukan untuk menjawab kebutuhan “stake holder” akan kualitas lulusan.', 'ppns.ac.id'),
(91, 'Politeknik Negeri Banjarmasin', '23 September 1987', 'Kalimantan Selatan', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLIBAN.png', 'Politeknik Negeri Banjarmasin (POLIBAN) berdiri pada 23 September 1987. Awalnya, POLIBAN merupakan bagian dari Universitas Lambung Mangkurat (ULM) dengan nama Politeknik Unlam. Namun, pada tahun 1997, POLIBAN menjadi perguruan tinggi negeri yang mandiri, terpisah dari ULM. Sejak saat itu, POLIBAN terus menunjukkan perkembangan yang positif, menjadi salah satu politeknik terkemuka di Indonesia. Melalui dedikasi dan komitmen mereka, POLIBAN telah menghasilkan banyak alumni sukses yang aktif berkontribusi dalam berbagai bidang, baik di dalam maupun luar negeri. POLIBAN terus menerus mempertahankan komitmennya dalam memberikan pendidikan vokasi berkualitas, dengan tujuan menghasilkan lulusan yang kompeten dan siap bersaing di dunia kerja.', 'poliban.ac.id'),
(92, 'Politeknik Negeri Lhokseumawe', '5 Oktober 1985', 'Aceh', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/PNL.png', 'Politeknik Negeri Lhokseumawe (PNL) terletak di Kota Lhokseumawe, Provinsi Aceh. PNL didirikan pada tanggal 9 Mei 1997 berdasarkan Keputusan Menteri Pendidikan dan Kebudayaan Nomor 100/O/1997. PNL menyelenggarakan program pendidikan vokasi dalam berbagai bidang ilmu pengetahuan dan teknologi. Jika memenuhi syarat, PNL juga dapat menyelenggarakan pendidikan profesi. Politekni ini juga adalah Politeknik yang sudah memberikan banyak lulusan yang hebat dan kompeten di bidangnya lho, mereka tersebar di banyak perusahaan swasta dan negara yang terkemuka di Indonesia.', 'pnl.ac.id'),
(93, 'Politeknik Negeri Kupang', '11 Maret 1985', 'Nusa Tenggara Timur', 'Baik', 'politeknik', 'images/section2/logo univ/PNK.png', 'Politeknik Negeri Kupang merupakan perguruan tinggi negeri pendidikan vokasi yang berada di Kupang, Nusa Tenggara Timur. Berdiri pada tahun 1985 dan berada di area seluas 55.700 m2. Sebelumnya bernama Politeknik Undana Kupang dan berada dibawah naungan Universitas Nusa Cendana.', 'pnk.ac.id'),
(94, 'Politeknik Elektronika Negeri Surabaya', '29 Mei 1986', 'Jawa Timur', 'Unggul', 'politeknik', 'images/section2/logo univ/PENS.png', 'Politeknik Elektronika Negeri Surabaya (PENS) merupakan perguruan tinggi vokasi negeri yang berlokasi di Surabaya, Jawa Timur. Melalui pendidikan tinggi vokasi ini, tentu Politeknik Elektronika Negeri Surabaya lebih banyak mengedepankan penerapan pembelajaran praktik ketimbang teori. Politeknik Elektonika Negeri Surabaya sendiri berfokus pada bidang studi yang berkaitan dengan teknologi dan teknik.<br/><br/>Pada tahun 2023, Politeknik Elektronika Negeri Surabaya masuk dalam kategori salah satu kampus terbaik di jawa Timur, dan daftar kampus terbaik tersebut berdasarkan pada portal analitik Webometrics. PENS juga memiliki fasilitas-fasilitas untuk menunjang kebutuhan belajar mahasiswa.', 'pens.ac.id'),
(95, 'Politeknik Negeri Jember', '29 Oktober 1988', 'Jawa Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLIJE.png', 'Politeknik Negeri Jember merupakan perguruan tinggi negeri pendidikan vokasi yang berfokus pada proses belajar mengajar pada keahlian, keterampilan, dan standar kompetensi yang spesifik sesuai dengan kebutuhan dunia kerja. Politeknik Negeri Jember berada di daerah Jember, Jawa Timur. Politeknik Negeri Jember memiliki beberapa fasilitas yang disediakan dan dapat dimanfaatkan untuk menunjang kebutuhan mahasiswa.', 'polije.ac.id'),
(96, 'Politeknik Pertanian Negeri Pangkajene Kepulauan', '9 September 1990', 'Sulawesi Selatan', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/PPNP.png', 'Politani Neg. Pangkep merupakan institusi yang menyelenggarakan pendidikan tinggi vokasi jenjang D-III dan D-IV di Sulawesi Selatan yang menghasilkan tenaga ahli madya dan tenaga ahli dalam bidang perikanan dan pertanian.', 'polipangkep.ac.id'),
(97, 'Politeknik Pertanian Negeri Kupang', '7 April 1984', 'Nusa Tenggara Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/PPNK.jpg', 'Politeknik Pertanian Negeri Kupang didirikan untuk menghasilkan lulusan dengan tingkat kompetensi tinggi dalam bidang ilmu pertanian, khususnya pertanian lahan kering. Lulusannya akan dibekali dengan jiwa kewirausahaan sehingga pengetahuan dan keterampilannya dapat ditransformasikan ke dalam bentuk kegiatan ekonomi produktif. Mereka pun dituntut mampu menerapkan, mengembangkan dan menyebarluaskan ilmu pengetahuan teknologi dalam bidang pertanian bagi kesejahteraan masyarakat.', 'politanikoe.ac.id'),
(98, 'Politeknik Perikanan Negeri Tual', '18 Juli 1997', 'Maluku', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLIKANT.png', 'Politeknik Perikanan Negeri Tual adalah sebuah perguruan tinggi Negeri yang terletak di kepulauan kei, Maluku, bagian Timur Indonesia. yang merupakan satuan kerja Kemendikbud.Politeknik Perikanan Negeri Tual hingga saat ini masih merupakan satu-satunya politeknik negeri di Indonesia yang mengkhususkan diri pada pendidikan tinggi kejuruan (vokasi) dalam bidang perikanan dan dan kelautan.', 'polikant.ac.id'),
(99, 'Politeknik Negeri Malang', '27 Januari 1979', 'Jawa Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLINEMA.png', 'Polinema adalah sekolah tinggi yang ada di Malang. Mulai dibangun tahun 1982 dengan nama Program Pendidikan Diploma Bidang Teknik Universitas Brawijaya (PP DBT Universitas Brawijaya). Ini salah satu dari enam sekolah teknik pertama di Indonesia menurut perintah dari Direktorat Jenderal Pendidikan Tinggi pada tahun 1984. Polinema terus berkembang untuk jadi sekolah yang bagus dan bisa bersaing di seluruh dunia. Mereka punya cara belajar yang baru dan keterampilan yang dibutuhkan di industri, pemerintahan, dan masyarakat secara global. Polinema juga suka membantu riset dan pengabdian masyarakat di bidang ilmu pengetahuan, teknologi, dan kesejahteraan. Mereka berjanji untuk mengelola sekolah dengan baik. Polinema percaya kalau suasana belajar yang baik itu penting buat meningkatkan kualitas siswa dan pengajaran yang mendukung pembelajaran seumur hidup dan pertumbuhan jiwa kewirausahaan.', 'polinema.ac.id'),
(100, 'Politeknik Pertanian Negeri Samarinda', '28 April 1997', 'Kalimantan Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLITANI Samarinda.png', 'Politeknik Pertanian Negeri Samarinda (Politani) berdiri sejak 06 Februari 1989. Pada mulanya bernama Politeknik Pertanian Universitas Mulawarman. Berdasarkan SK. Menpan No. B-703/I/1995 tanggal 30 Juni 1995, maka secara resmi telah mandiri menjadi lembaga pendidikan vokasi di Kalimantan Timur.', 'politanisamarinda.ac.id'),
(101, 'Politeknik Pertanian Negeri Payakumbuh', '6 Februari 1989', 'Sumatera Barat', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/PPNP.png', 'Politeknik Pertanian Negeri Payakumbuh (disingkat PPNP atau Politani PYK), adalah perguruan tinggi negeri yang terdapat di Kabupaten Lima Puluh Kota, Sumatera Barat. Politeknik Pertanian Negeri Payakumbuh saat ini memiliki 3 buah jurusan yaitu Teknologi Pertanian, Budidaya Tanaman Perkebunan dan Budidaya Tanaman Pangan.', 'ppnp.ac.id'),
(102, 'Politeknik Negeri Samarinda', '3 Desember 1985', 'Kalimantan Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLNES.png', 'POLNES, perguruan tinggi negeri di Samarinda, Kalimantan Timur, berdiri sejak 1985 sebagai Politeknik Universitas Mulawarman. Dengan akreditasi institusi B dari BAN-PT, POLNES menawarkan 10 jurusan di bidang teknik, pariwisata, desain, kemaritiman, administrasi bisnis dan teknologi informasi. Polnes juga menyelenggarakan pendidikan mulai dari tingkat D-III, D-IV, S1, dan S2.', 'polnes.ac.id'),
(103, 'Politeknik Negeri Media Kreatif', '8 Oktober 2008', 'DKI Jakarta', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLIMEDIA.png', 'Politeknik Negeri Media Kreatif atau yang lebih sering disebut Polimedia adalah perguruan tinggi vokasi yang berada di Jakarta Selatan. Politeknik ini berdiri pada tahun 2008 melalui Peraturan Menteri Pendidikan Nasional Nomor 60 Tahun 2008. Polimedia adalah perguruan tinggi pertama dan satu-satunya yang dirancang khusus untuk menyediakan program studi yang sesuai dengan industri kreatif di Indonesia.', 'polimedia.ac.id'),
(104, 'Politeknik Manufaktur Negeri Bangka Belitung', '18 Oktober 2010', 'Kepulauan Bangka Belitung', 'Baik', 'politeknik', 'images/section2/logo univ/POLMANBABEL.png', 'Politeknik Manufaktur Bangka Belitung (Polmanbabel) merupakan perguruan tinggi vokasi yang berlokasi di Provinsi Kepulauan Bangka Belitung. Polmanbabel berdiri di atas lahan seluas 4,5 hektar dan memiliki kapasitas 1080 mahasiswa. Polmanbabel telah meluluskan lebih dari 2500 lulusan yang terserap di berbagai sektor industri nasional dan internasional.', 'polimanbabel.ac.id'),
(105, 'Politeknik Negeri Batam', '18 Oktober 2010', 'Kepulauan Riau', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLIBATAM.png', 'Polibatam adalah perguruan tinggi negeri yang terletak di Kota Batam, Provinsi Kepulauan Riau. Polibatam merupakan satu-satunya perguruan tinggi negeri vokasi di kawasan perdagangan dan pelabuhan bebas (KPBPB) Batam, Bintan, dan Karimun. Selain terletak di kawasan pusat pertumbuhan ekonomi nasional, Polibatam juga terletak di wilayah terdepan', 'polibatam.ac.id'),
(106, 'Politeknik Negeri Nusa Utara', '22 Juni 2011', 'Sulawesi Utara', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLNUSTAR.png', 'Politeknik Negeri Nusa Utara atau Polnustar adalah perguruan tinggi di Kabupaten Kepulauan Sangihe, Sulawesi Utara yang berdiri pada tahun 2006. Pendirian kampus ini diinisiasi oleh pemerintah daerah Kabupaten Kepulauan Sangihe-Talaud pada masa kepemimpinan Bupati A.J.Th. Makaminang (Alm) dan Wakil Bupati Winsulangi Salindeho, sebagai bagian dari komitmen untuk meningkatkan kualitas sumber daya manusia di wilayah Nusa Utara. Pada tahun 2011, Politeknik Nusa Utara berubah status dari PTS menjadi PTN.<br/><br/>Politeknik Negeri Nusa Utara memiliki beberapa program pendidikan di bidang Kesehatan, Teknologi Perikanan dan Kebaharian, serta Teknologi Informatika.', 'polnustar.ac.id'),
(107, 'Politeknik Negeri Bengkalis', '29 Juli 2011', 'Riau', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLBENG.png', 'Polbeng terletak di Kabupaten Bengkalis, Provinsi Riau. Polbeng menyelenggarakan program pendidikan vokasi dalam berbagai bidang ilmu pengetahuan dan teknologi. Jika memenuhi syarat, Polbeng juga dapat menyelenggarakan pendidikan profesi. Polbeng didirikan pada tanggal 29 Juli 2011 berdasarkan Peraturan Menteri Pendidikan Nasional Nomor 28 Tahun 2011.', 'polbeng.ac.id'),
(108, 'Politeknik Negeri Balikpapan', '9 September 2011', 'Kalimantan Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLTEKBA.png', 'Politeknik Negeri Balikpapan (Poltekba) adalah perguruan tinggi negeri vokasi yang terletak di Kota Balikpapan, Kalimantan Timur. Politeknik Negeri Balikpapan adalah perguruan tinggi vokasi, saat ini memiliki 5 Jurusan dan 9 Program Studi yang menyelenggarakan program diploma tiga dan sarjana terapan. Sistem pembelajaran di Poltekba berfokus pada praktik langsung dengan alat-alat yang difasilitasi oleh kampus. Hal ini bertujuan agar mahasiswa dapat menguasai dan memahami cara kerja alat-alat yang digunakan sesuai dunia kerja.<br/><br/>Poltekba juga telah bekerja sama dengan Management & Science University (MSU) di Malaysia. Kerja sama ini memberikan kesempatan bagi mahasiswa Poltekba untuk menimba ilmu di negeri jiran dengan sistem pembelajaran : menempuh kuliah tiga tahun di Poltekba dan satu tahun di MSU. Bahkan jika berkompeten, akan lanjut ke jenjang S2. Selain itu, Poltekba juga memberikan peluang besar bagi para calon lulusan untuk masuk ke dunia kerja. Setiap tahun, Poltekba mengadakan job fair yang menggandeng berbagai perusahaan. Tahun lalu, job fair Poltekba berhasil menggandeng 15 perusahaan.', 'poltekba.ac.id'),
(109, 'Politeknik Negeri Madura', '29 Oktober 2012', 'Jawa Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLTERA.png', 'Politeknik Negeri Madura (Poltera) terletak di Kabupaten Sampang, Provinsi Jawa Timur. Poltera menyelenggarakan pendidikan vokasi dalam berbagai bidang ilmu pengetahuan dan teknologi. Poltera didirikan berdasarkan Peraturan Menteri Pendidikan dan Kebudayaan Nomor 67 Tahun 2012 tentang Pendirian, Organisasi, dan Tata Kerja Politeknik Negeri Madura pada tanggal 29 Oktober 2012. Poltera diresmikan pada tanggal 11 November 2012.', 'poltera.ac.id'),
(110, 'Politeknik Maritim Negeri Indonesia', '19 September 2012', 'Jawa Tengah', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLMARIN.png', 'Politeknik Maritim Negeri Indonesia (PoliMARIN) merupakan pendidikan tinggi vokasi (Politeknik) khusus di bidang kemaritiman hasil transformasi Badan Pengembangan dan Layanan Pendidikan Tinggi (BPLPT). Pendirian PoliMARIN dilatarbelakangi oleh peningkatan kebutuhan tenaga laut terdidik dan armada pelaut lokal. Lulusan PoliMARIN ditargetkan mampu mengoperasikan kapal-kapal nasional dan bersaing dengan armada kapal asing. Staf pengajar PoliMARIN merupakan pelaut profesional berpengalaman dengan sertifikasi internasional sesuai standar International Maritime Organization (IMO).', 'polimarin.ac.id'),
(111, 'Politeknik Negeri Banyuwangi', '4 Oktober 2013', 'Jawa Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLIWANGI.png', 'Politeknik Negeri Banyuwangi (POLIWANGI) merupakan perguruan tinggi negeri vokasi yang terletak di Kabupaten Banyuwangi, Jawa Timur. Didirikan pada tahun 2013, POLIWANGI telah berkembang pesat menjadi salah satu politeknik terdepan di Indonesia. POLIWANGI menawarkan berbagai program studi D3 dan S1 Terapan di bidang agroindustri, teknologi informasi dan komunikasi, dan teknik manufaktur. Kampus ini memiliki fasilitas lengkap, termasuk ruang kelas modern, laboratorium terlengkap, workshop, perpustakaan, asrama, dan lapangan olahraga. Lulusan POLIWANGI memiliki daya saing tinggi di dunia kerja karena kurikulumnya up-to-date dan relevan dengan kebutuhan industri. POLIWANGI juga menjalin kerjasama dengan berbagai pihak, seperti industri, perguruan tinggi, dan pemerintah.', 'poliwangi.ac.id'),
(112, 'Politeknik Negeri Madiun', '30 Oktober 2012', 'Jawa Timur', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/PNM.png', 'Politeknik Negeri Madiun (PNM) terletak di Kota Madiun, Provinsi Jawa Timur. PNM sebelumnya bernama Politeknik Madiun (Polma) yang diselenggarakan oleh Yayasan Perguruan Tinggi Pemerintah Kota Madiun berdasarkan Keputusan Menteri Pendidikan dan Kebudayaan Nomor 99/D/0/2003 tanggal 9 Juli 2003. Politeknik Negeri Madiun (PNM) adalah perguruan tinggi negeri satu-satunya di wilayah barat Jawa Timur. Kota Madiun, tempat PNM berada, terkenal dengan makanan khasnya, yaitu nasi pecel dan brem. PNM memiliki dua kampus, yaitu Kampus I di Jalan Serayu No. 84, Kelurahan Pandean, Kota Madiun dan Kampus II di Jalan Ring Road, Kelurahan Winongo, Kecamatan Manguharjo, Kota Madiun. PNM menyelenggarakan pendidikan vokasi dalam berbagai bidang pengetahuan dan keahlian khusus. PNM menyelenggarakan pendidikan vokasi dalam berbagai bidang ilmu pengetahuan dan teknologi. Jika memenuhi syarat, PNM juga dapat menyelenggarakan pendidikan profesi.', 'pnm.ac.id'),
(113, 'Politeknik Negeri Fakfak', '30 Oktober 2012', 'Papua Barat', 'Baik', 'politeknik', 'images/section2/logo univ/POLINEF.png', 'Politeknik Negeri Fakfak adalah sebuah institusi pendidikan tinggi di Indonesia yang berfokus pada pendidikan vokasi dan teknologi. Terletak di Kota Fakfak, Papua Barat, politeknik ini menyediakan berbagai program studi dalam bidang teknik, manajemen, dan kejuruan lainnya. Tujuan utamanya adalah untuk mempersiapkan lulusannya dengan keterampilan praktis yang dibutuhkan oleh industri dan pasar kerja lokal maupun nasional. Politeknik Negeri Fakfak juga berkomitmen untuk mendukung pengembangan daerah sekitarnya melalui pendidikan dan pelatihan.', 'polinef.ac.id'),
(114, 'Politeknik Negeri Sambas', '22 Februari 2013', 'Kalimantan Barat', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLTESA.png', 'Politeknik Negeri Sambas adalah satu-satunya perguruan tinggi negeri yang ada di Sambas, Kalimantan Barat. Sebagai perguruan tinggi vokasi, metode pembelajaran di Poltesa didominasi mata kuliah praktikum dibanding mata kuliah teori. Berdiri sejak tahun 2008, Poltesa telah mendapatkan akreditasi Baik Sekali oleh BAN-PT.<br/><br/>Poltesa, memiliki fasilitas lab dan bengkel yang lengkap untuk mendukung mahasiswa dalam melakukan praktikum. Saat ini, Poltesa memiliki 3 program studi D3 dan 6 program studi D4 atau sarjana terapan.', 'poltesa.ac.id'),
(115, 'Politeknik Negeri Tanah Laut', '25 September 2009', 'Kalimantan Selatan', 'Baik Sekali', 'politeknik', 'images/section2/logo univ/POLITALA.png', 'Politeknik Negeri Tanah Laut merupakan pendidikan vokasi, yang terwujud pada tahun 2009. Tujuan didirikannya Politri adalah untuk meningkatkan kualitas Sumber Daya Manusia (SDM), menghadapi tumbuhnya industry di Kabupaten Tanah Laut untuk usaha-usaha menengah yang membutuhkan tenaga terampil.', 'politala.ac.id'),
(116, 'Politeknik Negeri Subang', '2 April 2014', 'Jawa Barat', 'Baik', 'politeknik', 'images/section2/logo univ/POLSUB.jpg', 'Politeknik Negeri Subang (POLSUB), berdiri pada 2 April 2014, adalah perguruan tinggi negeri pertama di Kabupaten Subang, Jawa Barat. Terdapat 2 kampus yang berlokasi di Jl. Brigjen Katamso No. 37 (Belakang RSUD Subang) dan Blok Kaleng Banteng Desa Cibogo. POLSUB mendapatkan akreditasi “Baik” dari BAN-PT. Politeknik ini menyelenggarakan program jenjang D-III dan D-IV.', 'polsub.ac.id'),
(117, 'Politeknik Negeri Ketapang', '8 April 2008', 'Kalimantan Barat', 'Baik', 'politeknik', 'images/section2/logo univ/POLITAP.png', 'Politeknik Negeri Ketapang (Politap) terletak di Kabupaten Ketapang, Provinsi Kalimantan Barat. Politap didirikan pada tanggal 15 Januari 2014 berdasarkan Peraturan Menteri Pendidikan dan Kebudayaan Nomor 15 Tahun 2014. Politap menyelenggarakan program pendidikan vokasi dalam berbagai bidang ilmu pengetahuan dan teknologi. Jika memenuhi syarat, Politap juga dapat menyelenggarakan pendidikan profesi.', 'politap.ac.id'),
(118, 'Politeknik Negeri Cilacap', '8 Juli 2008', 'Jawa Tengah', 'Baik', 'politeknik', 'images/section2/logo univ/PNC.png', 'Politeknik Negeri Cilacap (PNC) terletak di Kabupaten Cilacap, Provinsi Jawa Tengah. PNC didirikan pada tanggal 3 Oktober 2014 berdasarkan Peraturan Menteri Pendidikan dan Kebudayaan Nomor 102 Tahun 2014. PNC menyelenggarakan program pendidikan vokasi dalam berbagai bidang ilmu pengetahuan dan teknologi. Jika memenuhi syarat, PNC juga dapat menyelenggarakan pendidikan profesi di lingkungan akademiknya. PNC juga telah mencetak berbagai macam lulusan yang baik yang tersebar di berbagai perusahaan swasta atau negara di Indonesia.', 'pnc.ac.id'),
(119, 'Politeknik Negeri Indramayu', '8 Juli 2008', 'Jawa Barat', 'Baik', 'politeknik', 'images/section2/logo univ/POLINDRA.png', 'Politeknik Indramayu (POLINDRA) merupakan perguruan tinggi setingkat vokasi pertama yang didirikan di Indramayu, Jawa Barat. Pada tahun 2014 Politeknik Indramayu berubah status dari Perguruan Tinggi Swasta (PTS) menjadi Perguruan Tinggi Negeri (PTN) yang diresmikan pada tanggal 6 Oktober 2014, oleh Presiden Republik Indonesia Dr. Susilo Bambang Yudhoyono.<br/>Sampai saat ini, POLINDRA memiliki enam program studi, dengan rincian Teknik Mesin (D3), Teknik Informatika (D3), Teknik Pendingin dan Tata Udara (D3), Perancangan Manufaktur (D4), Rekayasa Perangkat Lunak (D4), dan Keperawatan (D3).', 'polindra.ac.id'),
(120, 'Politeknik Negeri Nunukan', '24 September 2020', 'Kalimantan Utara', 'Baik', 'politeknik', 'images/section2/logo univ/PNN.png', 'Perguruan Tinggi Negeri Politeknik Nunukan, atau PNN, merupakan institusi politeknik di Kalimantan Utara, tepatnya di Kabupaten Nunukan. Lokasinya berada di wilayah yang berbatasan langsung dengan Malaysia. PNN didirikan pada tahun 2020 dan sebelumnya merupakan bagian dari Politeknik Negeri Samarinda.', 'pnn.ac.id');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `data_kampus`
--
ALTER TABLE `data_kampus`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `data_kampus`
--
ALTER TABLE `data_kampus`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=121;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
