-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 17, 2025 at 09:04 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tubes_pwl`
--

-- --------------------------------------------------------

--
-- Table structure for table `utbk`
--

CREATE TABLE `utbk` (
  `kategori` varchar(50) NOT NULL,
  `sub_kategori` varchar(50) NOT NULL,
  `nomor` int(11) NOT NULL,
  `soal` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `utbk`
--

INSERT INTO `utbk` (`kategori`, `sub_kategori`, `nomor`, `soal`) VALUES
('Penalaran Umum', 'Pengantar Penalaran Induktif dan Deduktif', 1, 'Balikpapan adalah sebuah kota di Indonesia. Kalimat tersebut merupakan'),
('Penalaran Umum', 'Pengantar Penalaran Induktif dan Deduktif', 2, 'Tutup pintunya! Kalimat tersebut merupakan'),
('Penalaran Umum', 'Pengantar Penalaran Induktif dan Deduktif', 3, 'Badan gue gemuk banget nih. Kalimat tersebut merupakan'),
('Penalaran Umum', 'Pengantar Penalaran Induktif dan Deduktif', 4, 'Perhatikan kalimat-kalimat di bawah ini! Jawa Barat terletak di sebelah barat pulau Jawa. Waktu yang dibutuhkan Bumi untuk berotasi adalah 23 jam, 56 menit, dan 4 detik. Mengapa badan saya panas dan kepala saya pusing, ya? Bunga mawar berwarna merah, sementara bunga violet berwarna biru. Saya berharap Dharma menyukai pekerjaan barunya. Yang bukan termasuk pernyataan adalah'),
('Penalaran Umum', 'Pengantar Penalaran Induktif dan Deduktif', 5, 'Perhatikan kalimat-kalimat di bawah ini! Rebus telur selama kurang lebih 5 menit. Katakan padanya saya sedang keluar sebentar. Tidak ada bilangan prima yang tidak merupakan angka ganjil. Masa jabatan presiden Indonesia adalah 5 tahun dan dapat dipilih kembali hanya untuk satu kali masa jabatan. Akhirnya saya bisa lulus PTN tahun ini. Yang termasuk pernyataan adalah ….'),
('Penalaran Umum', 'Penalaran Deduktif', 1, 'Jika p dan q mempunyai nilai kebenaran yang berbeda, maka p ↔ q mempunyai nilai kebenaran salah.'),
('Penalaran Umum', 'Penalaran Deduktif', 2, '(a) Di mana ada kemiskinan, di sana ada kriminal. (b) Terdapat kemiskinan di Jakarta. Kesimpulan: Dengan demikian, pasti terdapat kriminal di Jakarta. Validitas kesimpulan di atas adalah'),
('Penalaran Umum', 'Penalaran Deduktif', 3, '1) “Jika tidak semua siswa memiliki akses internet, maka ada siswa yang kehilangan akses pendidikan dan pembelajaran secara daring.” 2) “Permasalahan ketimpangan pendidikan di Indonesia meningkat selama pandemi apabila ada siswa yang kehilangan akses pendidikan dan pembelajaran secara daring.” Manakah simpulan yang valid untuk premis di atas?'),
('Penalaran Umum', 'Penalaran Deduktif', 4, 'Negasi dari pernyataan \"Agus dan Sandhy lulus ujian\" adalah'),
('Penalaran Umum', 'Penalaran Deduktif', 5, 'Semua seniman kreatif. Ada ilmuan yang tidak kreatif. Simpulan yang tepat adalah'),
('Penalaran Umum', 'Penalaran Induktif', 1, '6, 7, 8, 10, 13, 18, 26, ….'),
('Penalaran Umum', 'Penalaran Induktif', 2, '6, 8, 4, 20, …, 18, 108, 112, 106, 742'),
('Penalaran Umum', 'Penalaran Induktif', 3, 'MPTJP = PUASA IZURGNY = ….'),
('Penalaran Umum', 'Penalaran Induktif', 4, 'L, B, Q, D, ..., F, A, H, F'),
('Penalaran Umum', 'Penalaran Induktif', 5, 'DJ, HN, NK, VO, …, RP, FM'),
('Penalaran Umum', 'Penalaran Kuantitatif', 1, 'Dalam sebuah acara keluarga yang dihadiri oleh kakek, nenek, paman, bibi, ayah, ibu, kaka, dan adik mereka duduk mengelilingi sebuah meja makan berbentuk bulat. Apabila kakek harus duduk di samping nenek, dan adik harus duduk di antara ayah dan ibu, maka banyaknya cara mereka duduk mengelilingi meja tersebut adalah .... cara.'),
('Penalaran Umum', 'Penalaran Kuantitatif', 2, 'Citra membeli beberapa jajanan di sebuah warung, namun karena banyak pembeli lain akhirnya sang pemilik warung salah menghitung total belanjaan milik Citra sehingga totalnya menjadi Rp69.000,00. Jajanan yang Citra beli seharusnya sebagai berikut: Dua buah roti tawar yang harganya Rp7.000,00 Satu botol air mineral yang harganya Rp3.000,00 Satu kantung keripik yang harganya Rp13.000,00 Tiga buah sosis yang harganya Rp8.000,00 Satu bungkus permen yang harganya Rp6.000,00 Jajanan manakah yang dihitung lebih banyak dari jumlah aslinya oleh sang pemilik warung?'),
('Penalaran Umum', 'Penalaran Kuantitatif', 3, 'Amir, Budi, Cantika, Diba, Edo, Fitri, dan Gina hendak memesan tiket bioskop. Mereka akan duduk di satu baris yang sama. Ada berapa cara mereka duduk di bioskop tersebut apabila Budi tidak boleh duduk di antara Cantika dan Diba?'),
('Penalaran Umum', 'Penalaran Kuantitatif', 4, 'Dhiya hendak membeli kue di toko dekat rumahnya. Harga kue yang ingin dia beli adalah Rp25.000,00 per potong dan dia pergi membawa uang pas untuk membeli sejumlah kue tersebut. Ketika sampai di toko, ternyata terdapat penawaran yaitu diskon Rp5.000,00 per potong dengan syarat pembelian minimal 8 potong kue. Akhirnya, Dhiya bisa membeli 3 potong kue lebih banyak dengan uang tersebut. Berapa potong kue yang awalnya ingin Dhiya beli?'),
('Penalaran Umum', 'Penalaran Kuantitatif', 5, 'Suatu layanan ekspedisi A menyediakan jasa pengiriman barang tanpa pemberhentian dari Tajur ke Cibinong yang memerlukan waktu selama 40 menit. Ekspedisi B menawarkan pengiriman dengan jalur yang sama namun dengan pemberhentian di tiga kecamatan yang masing-masing terpisah dengan jarak yang sama. Ekspedisi B berhenti setiap 5 menit di masing-masing kecamatan dan memerlukan waktu 1 jam 15 menit dari Tajur ke Cibinong. Jika ekspedisi A berangkat pukul 9.00 sedangkan ekspedisi B berangkat pukul 8.45, pada pukul berapa mereka akan berpapasan satu sama lain?'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Membaca Teks', 1, '(1) Dalam beberapa tahun terakhir, mulai banyak pasien anak dan remaja yang memiliki keluhan pada tulang belakang. (2) Padahal, rasa sakit seperti ini biasanya dialami orang yang berusia 40 tahun ke atas. (3) Anak dan remaja ini ternyata gemar menggunakan gadget, seperti telepon pintar, komputer, dan tablet. (4) Banyak dari mereka yang bermain gadget sambil tengkurap, membungkuk, atau lehernya ke bawah untuk menatap layar monitor, sehingga kepala membebani leher. (5) Ada pula yang badannya bersandar di kursi dengan posisi layar lebih tinggi dari pada mata. (6) Di samping itu, juga ada yang memiringkan kepala ke satu sisi untuk menjepit gadget di antara telinga dan pundak ketika menelepon. (7) Apabila ini dilakukan terus menerus, tulang belakang akan “protes” dengan mengirimkan sinyal nyeri. Apa gagasan utama paragraf pertama?'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Membaca Teks', 2, '(1) Dalam beberapa tahun terakhir, mulai banyak pasien anak dan remaja yang memiliki keluhan pada tulang belakang. (2) Padahal, rasa sakit seperti ini biasanya dialami orang yang berusia 40 tahun ke atas. (3) Anak dan remaja ini ternyata gemar menggunakan gadget, seperti telepon pintar, komputer, dan tablet. (4) Banyak dari mereka yang bermain gadget sambil tengkurap, membungkuk, atau lehernya ke bawah untuk menatap layar monitor, sehingga kepala membebani leher. (5) Ada pula yang badannya bersandar di kursi dengan posisi layar lebih tinggi dari pada mata. (6) Di samping itu, juga ada yang memiringkan kepala ke satu sisi untuk menjepit gadget di antara telinga dan pundak ketika menelepon. (7) Apabila ini dilakukan terus menerus, tulang belakang akan “protes” dengan mengirimkan sinyal nyeri. (8) Ada berbagai macam sensasi nyeri pada tulang belakang, seperti ditusuk-tusuk, kesemutan, tersetrum, dan nyeri cenat cenut seperti sakit gigi. (9) Pada nyeri yang diakibatkan gadget, biasanya sensasinya seperti tersetrum. (10) Nyeri ini memang tak berbahaya. (11) Tetapi, jika dibiarkan terus menerus, nyeri ini bisa merusak postur tulang. (12) Ada tiga tahapan nyeri pada tulang belakang, yaitu rasa nyeri yang dialami otot, kemudian menjalar ke sendi, dan terakhir mengenai tulang. Manakah pertanyaan yang jawabannya tidak terdapat dalam teks?'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Membaca Teks', 3, '(1) Buku The Malay Archipelago ditulis oleh Wallace selama 6 tahun sepulangnya dari Kepulauan Nusantara. (2) Bagian-bagian buku tersebut memberikan gambaran dari sebuah ekspedisi besar selama 8 tahun (1854—1862). (3) Dia melintasi 22.500 kilometer dan 70 kali perjalanan di lima gugus besar Kepulauan Nusantara: Sundaland (Jawa, Sumatera, Bali, Lombok, dan Borneo) termasuk semenanjung Malaya dan Singapura, Celebes (Sulawesi), Timor, Moluccas (Maluku), dan Papua. (4) Walau sudah berusia lebih dari satu setengah abad, The Malay Archipelago tetap menjadi sebuah buku klasik yang masih disitasi oleh para ilmuwan modern. (5) Di dalam bukunya, Wallace menunjukkan perbandingan jenis-jenis kupu-kupu yang dapat ditemui di Jawa, Kalimantan, dan Sulawesi. (6) Selain itu, ia juga membandingkan jumlah jenis kumbang dan burung yang ada di Sulawesi dan kawasan kepulauan lainnya. sumber: theconversation.com (dengan modifikasi) Kata itu pada kalimat (6) merujuk pada ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Membaca Teks', 4, '(1) Saat kita tidur, kita mungkin terlihat dalam keadaan diam dan tidak melakukan apa pun. (2) Padahal, sesungguhnya otak dan tubuh kita tetap aktif dan melakukan hal-hal penting saat kita tidur, misalnya mengatur sel saraf, mengatur hormon, memperbaiki sel, dan mengeluarkan racun. (3) Otak kita membantu kita dengan banyak hal saat kita tidur. (4) Contohnya adalah memproses ingatan, mencari ilham kreatif, dan belajar keterampilan baru. (5) Tidur membantu kita belajar, tumbuh, dan bersemangat; semua hal ini butuh waktu. (6) Inilah yang menjadi alasan bayi butuh tidur 14 hingga 17 jam sehari selama tiga bulan pertama. (7) Bahkan, bayi baru lahir menghabiskan lebih banyak waktu terlelap. (8) Sebagian besar anak usia sekolah butuh tidur 8 hingga 10 jam sehari. Sumber: theconversation.com (dengan modifikasi) Apa hubungan antara kalimat (3) dan (4) teks tersebut?'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Membaca Teks', 5, '(1) Semua bagian tubuh mamut ada di sana, dari tulang yang sangat besar seperti tengkorak dan tulang kaki, hingga yang lebih kecil seperti tulang belakang (2) Puing tersebut berbentuk lingkaran, sehingga para peneliti kadang menyebutnya sebagai lingkaran tulang zaman es. (3) Dalam jurnal yang dipublikasikan pada Selasa (17/3/2020), arkeolog mengatakan bahwa mereka telah menemukan puing rumah yang terbuat dari tulang belulang 60 ekor mamut yang kira-kira berasal dari 20 ribu tahun lalu. (4) Ternyata, selain diburu untuk dijadikan makanan atau dibuat mantel penahan suhu dingin, para arkeolog dari University of Exeter menemukan fakta lain mengenai pemanfaatan mamut oleh manusia zaman es di Rusia. (5) Lokasinya berada di situs arkeologi Kostenki 11 yang berjarak sekitar 560 kilometer dari Moskow Urutkan kalimat berikut agar menjadi paragraf yang padu!'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Ejaan', 1, '(1) Setiap pembaruan kurikulum, pihak dinas pendidikan dituntut untuk secara cepat melakukan penyesuaian terhadap para pelaksana di lapangan. (2) Akan tetapi, kenyataan berbicara lain yakni umumnya penanganan pengembangan tenaga pelaksana di lapangan berjalan sangat lambat. Ejaan pada kalimat (1) dan kalimat (2) di atas menjadi benar jika diperbaiki dengan cara ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Ejaan', 2, '(1) Salah satu kain tenun yang memiliki keunikan dan karakter budaya kuat adalah kain tenun asli Ternate. (2) Kain ini sudah ada cukup lama di Ternate. (3) Namun, saat ini kain tersebut sudah menjadi barang langka. (4) Suatu daerah di Ternate yang bernama Koloncucu adalah pusat pembuatannya, dan kerajinan tenun ini telah dilakukan secara turun-temurun di tempat ini. (5) Banyak pengrajin tenun Ternate yang berasal dari tempat ini dan biasanya menenun tidak hanya untuk mendapatkan uang tetapi sudah menjadi sebuah hobi untuk mengisi waktu luang. (6) Pada dasarnya, kain tenun Ternate tidak berbeda dari kain tenun lain di Indonesia. (7) Benang yang menjadi bahan dasar, peralatan, hingga teknik pembuatannya pun sama dengan kain tenun dari daerah lain di Indonesia. (8) Kain tenun Ternate biasanya memiliki berbagai motif yang berkaitan dengan keragaman Maluku Utara yang berkaitan dengan dunia laut, seperti ikan, kerang, dan burung laut. Diadaptasi dari https://indonesiakaya.com/ Penggunaan tanda baca yang salah terdapat pada kalimat ...'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Ejaan', 3, 'Sebelum tokoh Batman diciptakan oleh Bob Kane dan Bill Finger yang diterbitkan melalui DC Comics, telah ada superhero “pahlawan super” Batman yang identitas aslinya adalah dewa. Mungkin ungkapan “apa yang terjadi sekarang terinspirasi dari masa lalu” benar adanya. Hal ini terjadi karena sebelum tokoh Batman diciptakan, suku Maya telah meyakini adanya dewa kelelawar itu. Ribuan tahun yang lalu, suku Maya kuno menyembah dewa yang memiliki tubuh manusia dan kepala kelelawar. Dewa itu disebut oleh suku Maya kuno sebagai Camazotz. sumber: historia.id Perbaikan yang tepat untuk kata yang bercetak tebal adalah ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Ejaan', 4, 'Perhatikan kata serapan di bawah ini! Anggota DPR mengatakan bahwa target penerimaan pajak di 2022 sudah sesuai realitas. Diagnosa terhadap kesehatan mental tidak bisa dilakukan oleh sembarang orang. Kapitalisme adalah ideologi yang didasarkan pada nilai-nilai kapital atau permodalan. Manakah penulisan kata serapan yang paling tepat?'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Ejaan', 5, '“Mereka senang gim Indonesia temanya bukan medieval (zaman abad pertengahan), kastil, farming (pertanian), pirate (pembajak) lagi. Konten Indonesia yang segar ini dikawinkan dengan gim yang sudah bertaraf internasional dan konten yang eksotis,” ucap Andre Muslim Dubari, ketua asosiasi pegiat industri board game Indonesia. Sumber: goodnewsfromindonesia.id Alasan kesalahan ejaan pada teks adalah ....'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kata dan Pembentukannya', 1, '(1) Perubahan iklim membuat makhluk hidup harus beradaptasi, tidak terkecuali hewan. (2) Hasil studi terbaru menunjukkan bahwa hewan di seluruh dunia menumbuhkan bagian telinga, paruh, hingga ekor menjadi lebih besar. (3) Dilansir dari Independent, hal ini disebabkan oleh kondisi bumi yang semakin panas. (4) Pemantauan proses hewan beradaptasi terhadap pemanasan global dilakukan selama beberapa dekade. (5) Ada spesies yang mengalami kepunahan. (6) Awalnya, mereka merubah pola berkembang biak dan bermigrasi untuk menghindari panas. (7) Dalam beberapa kasus, ukurannya justru menyusut untuk mengatur suhu tubuh lebih baik. Sumber: nationalgeographic.grid.id (dengan modifikasi) Penggunaan kata berimbuhan yang salah dalam teks di atas terdapat dalam kalimat ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kata dan Pembentukannya', 2, '(1) Kita mungkin sudah sering mendengar pentingnya tidur 8 jam setiap malam demi tubuh yang sehat. (2) Namun, hasil penelitian menunjukkan bahwa durasi tidur itu tak berlaku untuk setiap orang. (3) Menurut rekomendasi Centers for Disease Control and Prevention (CDC), orang berusia antara 18—60 tahun perlu tidur selama 7 jam atau lebih di malam hari. (4) \"Kurang tidur dikaitkan dengan berbagai penyakit dan kondisi kronis seperti diabetes tipe 2, penyakit jantung, obesitas, dan depresi yang mengancam kesehatan kita,\" demikian keterangan CDC. (5) Sementara itu, kurang tidur dapat menyebabkan kecelakaan berkendara dan kesalahan di tempat kerja, dan memicu cedera serta kecacatan setiap tahun. (6) Nyatanya, ada orang yang tidurnya kurang dari tujuh jam tetapi tetap bisa berfungsi normal. (7) Ternyata, ada penjelasan ilmiahnya. Sumber: https://lifestyle.kompas.com/ (dengan modifikasi) Kata berimbuhan yang tepat untuk mengisi bagian rumpang pada kalimat nomor (2) paragraf pertama adalah….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kata dan Pembentukannya', 3, '(1) Kualitas pendidikan kita tidak meningkat karena para pelakunya belum bersinergi. (2) Dalam pelaksanaanya, pemerintah pun abai terhadap tuntutan standar. (3) Pelaku utama yang membentuk ekosistem dalam standar nasional pendidikan ada tiga, yaitu Badan Standar Nasional Pendidikan (BSNP) sebagai penyusun dan pengembangan SNP, Badan Akreditasi Nasional (BAN) sebagai evaluasi ketercapaian SNP, dan Lembaga Penjaminan Mutu Pendidikan (LPMP) sebagai unit teknis pemerintah untuk mendorong dan menjamin tercapainya SNP di daerah. (4) Konstruksinya ialah BSNP menyusun SNP; BAN mengevaluasi ketercapaian SNP; pemerintah sebagai pelaksana memiliki unit di daerah dalam bentuk LPMP untuk memastikan pendidikan di daerah memenuhi SNP. (5) Pengelolaan pendidikan memang memerlukan standar yang jelas sebagai acuan. Sumber: mediaindonesia.com (dengan modifikasi) Kalimat (3) dapat diperbaiki dengan cara ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kata dan Pembentukannya', 4, 'Gula dapat merangsang pelepasan hormon dopamin dan bagian otak yang disebut Nucleus accumbens yang dapat menimbulkan perasaan bahagia yang kuat. …, asupan gula juga memicu pelepasan hormon serotonin yang memberikan efek menenangkan. Konjungsi yang tepat untuk mengisi bagian rumpung pada teks tersebut adalah ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kata dan Pembentukannya', 5, 'Cermati kalimat berikut ini! Kami melihat banyak batu tertumpuk di pinggir jalan. Makna imbuhan ter- pada kata tertumpuk pada kalimat di atas memiliki makna yang sama dengan imbuhan ter- pada kalimat berikut ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kalimat', 1, 'Penjualan sisiknya untuk pengobatan tradisional Tiongkok dan dagingnya sebagai makanan lezat, telah menjadikan trenggiling sebagai mamalia yang paling banyak diperdagangkan di dunia. Kelangsungan hidup trenggiling semakin terancam, sehingga pada 2016, perdagangan komersial internasional melarang perdagangan hewan tersebut. Namun begitu, data investigasi yang disampaikan eksklusif kepada National Geographic menemukan bahwa, perdagangan sisik dan daging trenggiling masih tinggi pada 2019. Di seluruh dunia, peningkatannya lebih dari 200 persen dari lima tahun sebelumnya. Ada sekitar 128 ton yang disita oleh penegak hukum. Frasa yang tepat untuk melengkapi bagian rumpang paragraf tersebut adalah'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kalimat', 2, '(1) Globalisasi menjadi tantangan untuk semua aspek kehidupan termasuk kebudayaan. (2) Era global menuntut kesiapan kita untuk siap berubah menyesuaikan perubahan zaman dan mampu mengambil setiap kesempatan. (3) Budaya tradisional di Indonesia sebenarnya lebih kreatif dan tidak bersifat meniru, namun yang menjadi masalah adalah bagaimana mempertahankan jati diri bangsa. (4) Sebagai contoh sederhana, budaya gotong royong di Indonesia saat ini hampir terkikis habis, yang digantikan oleh sikap individual dan tidak peduli kepada orang lain. (5) Perlu dipikirkan agar kebudayaan kita tetap dapat mencerminkan kepribadian bangsa. (6) Dalam era globalisasi, kebudayaan tradisional mulai mengalami erosi. (7) Semua orang, terutama anak muda, lebih senang menghabiskan waktunya mengakses internet daripada mempelajari tarian dari kebudayaan sendiri. (8) Orang akan merasa bangga ketika dapat meniru gaya berpakaian orang Barat dan menganggap budayanya ketinggalan zaman. (9) Globalisasi akan selalu memberikan perubahan. (10) Oleh karena itu, harus meneliti apakah berbagai budaya yang masuk tersebut bersifat positif atau negatif. Kalimat yang tidak efektif dalam teks di atas adalah kalimat'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kalimat', 3, '(1) Dalam beberapa tahun terakhir, mulai banyak pasien anak dan remaja yang memiliki keluhan pada tulang belakang. (2) Padahal, rasa sakit seperti ini biasanya dialami orang yang berusia 40 tahun ke atas. (3) Anak dan remaja ini ternyata gemar menggunakan gadget, seperti telepon pintar, komputer, dan tablet. (4) Banyak dari mereka yang bermain gadget sambil tengkurap, membungkuk, atau lehernya ke bawah untuk menatap layar monitor, sehingga kepala membebani leher. (5) Ada pula yang badannya bersandar di kursi dengan posisi layar lebih tinggi dari pada mata. (6) Di samping itu, juga ada yang memiringkan kepala ke satu sisi untuk menjepit gadget di antara telinga dan pundak ketika menelepon. (7) Apabila ini dilakukan terus menerus, tulang belakang akan “protes” dengan mengirimkan sinyal nyeri. (8) Ada berbagai macam sensasi nyeri pada tulang belakang, seperti ditusuk-tusuk, kesemutan, tersetrum, dan nyeri cenat cenut seperti sakit gigi. (9) Pada nyeri yang diakibatkan gadget, biasanya sensasinya seperti tersetrum. (10) Nyeri ini memang tak berbahaya. (11) Tetapi, jika dibiarkan terus menerus, nyeri ini bisa merusak postur tulang. (12) Ada tiga tahapan nyeri pada tulang belakang, yaitu rasa nyeri yang dialami otot, kemudian menjalar ke sendi, dan terakhir mengenai tulang. Kata sambung yang salah adalah'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kalimat', 4, '(1) Dalam beberapa tahun terakhir, mulai banyak pasien anak dan remaja yang memiliki keluhan pada tulang belakang. (2) Padahal, rasa sakit seperti ini biasanya dialami orang yang berusia 40 tahun ke atas. (3) Anak dan remaja ini ternyata gemar menggunakan gadget, seperti telepon pintar, komputer, dan tablet. (4) Banyak dari mereka yang bermain gadget sambil tengkurap, membungkuk, atau lehernya ke bawah untuk menatap layar monitor, sehingga kepala membebani leher. (5) Ada pula yang badannya bersandar di kursi dengan posisi layar lebih tinggi dari pada mata. (6) Di samping itu, ada juga yang memiringkan kepala ke satu sisi untuk menjepit gadget di antara telinga dan pundak ketika menelepon. (7) Apabila ini dilakukan terus menerus, tulang belakang akan “protes” dengan mengirimkan sinyal nyeri. (8) Ada berbagai macam sensasi nyeri pada tulang belakang, seperti ditusuk-tusuk, kesemutan, tersetrum, dan nyeri cenat cenut seperti sakit gigi. (9) Pada nyeri yang diakibatkan gadget, biasanya sensasinya seperti tersetrum. (10) Nyeri ini memang tak berbahaya. (11) Namun, jika dibiarkan terus-menerus, nyeri ini bisa merusak postur tulang. (12) Ada tiga tahapan nyeri pada tulang belakang, yaitu rasa nyeri yang dialami otot, kemudian menjalar ke sendi, dan terakhir mengenai tulang. Kesalahan penggunaan tanda baca ditemukan pada kalimat'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Kalimat', 5, '1. Pariwisata merupakan penghasil devisa yang sangat diharapkan. 2. Wisatawan mencanegara merosot tajam tahun ini. 3. Teror merebak di mana-mana di seluruh tanah air. Penggabungan yang tepat adalah'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Diksi dan Makna Kata', 1, '(1) Flu singapura pada dasarnya adalah flu yang menyerang kekebalan tubuh, terutama anak-anak, yang dilakukan oleh virus RNA dari jenis Reterovirus. (2) Virus ini pertama kali ditemukan di Singapura dan itu pula yang kemudian menyebabkan flu ini dinamakan flu singapura. (3) Dalam bahasa medis internasional flu ini dinamakan HMFD atau Hand Mouth and Foot Disease. (4) Penamaan ini berdasar pusat serangan yang terfokus pada luka di kaki, tangan, dan mulut. (5) Bila kebanyakan virus flu menyerang area pernafasan dan area lendir, maka serangan virus ini cenderung lebih muncul pada kulit. (6) Kadang gejala pada kulit akan muncul pertama kali dari gejala demam dan tanda-tanda flu lain, seperti munculnya sariawan berat dan peradangan di area tenggorokan depan. (7) Proses penularannya cukup mudah, tetapi kebanyakan penularan berawal dan interaksi langsung kulit dengan media yang sudah terpapar virus RNA. (8) Penularan itu bisa melalui proses sentuhan kulit dengan pengidap flu singapura atau tersentuh benda yang sudah terkontaminasi flu singapura. (9) Aktivitas makan dan minum bercampur dengan pengidap flu singapura juga bisa menyebabkan penularan. Kata terkontaminasi pada kalimat (8) bermakna'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Diksi dan Makna Kata', 2, '(1) Para arkeolog menemukan reruntuhan tempat pemandian kuno yang bergaya Romawi. (2) Reruntuhan itu berasal dari abad ke-10 di daerah otonom Uighur Xinjiang, China Barat Laut. (3) Reruntuhan tersebut terdiri atas struktur utama batu bata yang diapit oleh beberapa sumur dan struktur batako di sisi timur. (4) Struktur utama terdiri atas dua bagian, yaitu bagian bawah tanah dan bagian permukaan. (5) Bagian bawah tanah digunakan untuk cerobong asap dan suplai panas. (6) Sementara itu, struktur di permukaan berfungsi sebagai tempat orang-orang mandi. (7) Di dalam reruntuhan itu, para arkeolog juga menemukan beberapa artefak, seperti tembikar, batu bata persegi, dan dekorasi bunga di dinding yang menunjukkan pertemuan antara budaya dataran tengah dan budaya setempat. (8) Menurut Wei Jian, profesor yang bertanggung jawab atas penggalian itu, pemandian tersebut merupakan bagian dari kota kuno yang dikenal sebagai Tang Chao Dun yang dibangun pertama kali pada awal Dinasti Tang (618—907 M). Sumber: kompas.com (dengan modifikasi) Kata yang memiliki makna yang sama dengan kata yang bercetak tebal di atas adalah ....'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Diksi dan Makna Kata', 3, 'Para relawan membantu evakuasi korban pasca tsunami. Makna kata evakuasi adalah ...'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Diksi dan Makna Kata', 4, 'Hartinah hanya menjadi benalu bagi keluarganya, tak sedikit tetangga yang merasa geram akan tingkahnya. Kata yang bercetak miring dalam kutipan di atas mengandung makna ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Diksi dan Makna Kata', 5, '(1) Pijat bayi merupakan terapi alternatif yang sudah diterapkan sejak lama. (2) Namun, sekarang pijat bayi digali kembali oleh ilmu kesehatan dan dijadikan kajian ilmiah para pakar. (3) Saat ini pijat bayi didefinisikan sebagai terapi sentuh dalam seni perawatan dan pengobatan dengan kontak tubuh berkelanjutan yang menimbulkan rasa nyaman dan aman sehingga meningkatkan kesehatan fisik dan psikologis bayi. (4) Pijat bayi membantu tumbuh kembang fisik dan emosi bayi dan mempererat hubungan ibu dan bayi. Kata seni dalam kalimat (3) bermakna ...'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Literasi Bahasa Indonesia', 1, 'Aku mengenal Kasih Kinanti setahun lalu di kios Mas Yunus, langganan kami berbuat dosa. Di sanalah kawan-kawan sesama pers mahasiswa diam-diam menggandakan beberapa bab novel Anak Semua Bangsa dan berbagai buku terlarang lainnya. Seingatku, Kinan tengah membuat fotokopi buku-buku karya Ernesto Laclau dan Ralph Miliband yang akan menjadi bahan diskusi. Sebetulnya aku pernah bertemu Kinan sekilas di beberapa acara pers mahasiswa di kampus, tapi aku hanya mengenalnya sebagai Kasih Kinanti dan ternyata dia juga sudah mengetahui namaku dari beberapa tulisanku di koran mahasiswa Aulagung. *** “Coba gambarkan peta bagaimana seseorang yang berangkat dari kampus bisa mencapai rumah ini?” [tanya Daniel]. Sebelum Kinan membuka mulutnya, Alex segera membalas dengan sigap lengkap dengan irama dan aksen Flores yang merdu. “Jalan Godean terus saja sampai pasar, lalu belok kanan ke arah utara. Lima kilometer nanti bertemu perempatan, kau akan menemukan sebatang pohon beringin. Belok kiri, 300 meter dari sana masuklah ke Desa Pete, jalan terus melalui sekolah taman kanak-kanak yang berpagar merah, terus saja mengikuti jalan yang menurun. Nanti masuk lagi ke gang yang agak sempit, terus saja, nah, rumah di sebelah kiri, dengan patokan sebuah pohon beringin lain yang jauh lebih besar dan tua dan akar yang menggapai tanah.” Jawaban Alex bukan melegakan Daniel, tapi malah membuat wajah Manado yang putih itu menjadi merah. Daniel mempersoalkan bagaimana bisa mencapai rumah hantu itu jika untuk mengucapkan arah jalannya saja sudah makan waktu 15 menit. Bagaimana caranya kami menyampaikan informasi kepada kawan-kawan bahwa kini diskusi dan sekretariat mahasiswa Winatra sudah pindah ke tengah hutan Desa Pete? “Soal jarak dan keruwetan arah….”, Kinan menatap wajah Daniel yang tampaknya belum puas, “justru itu kelebihannya. Karena rumah hantu ini tersembunyi, kita akan aman. Rasanya para lalat itu akan sukar menemukan desa ini. Kita bebas mendiskusikan buku siapa saja, apakah karya Laclau atau Ben Anderson, atau bahkan novel Pak Pramoedya akan menghirup udara merdeka di sini.” Sumber: novel Laut Bercerita karya Leila S. Chudori Apa yang dirasakan Daniel setelah mendengar jawaban Alex?'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Literasi Bahasa Indonesia', 2, 'Aku mengenal Kasih Kinanti setahun lalu di kios Mas Yunus, langganan kami berbuat dosa. Di sanalah kawan-kawan sesama pers mahasiswa diam-diam menggandakan beberapa bab novel Anak Semua Bangsa dan berbagai buku terlarang lainnya. Seingatku, Kinan tengah membuat fotokopi buku-buku karya Ernesto Laclau dan Ralph Miliband yang akan menjadi bahan diskusi. Sebetulnya aku pernah bertemu Kinan sekilas di beberapa acara pers mahasiswa di kampus, tapi aku hanya mengenalnya sebagai Kasih Kinanti dan ternyata dia juga sudah mengetahui namaku dari beberapa tulisanku di koran mahasiswa Aulagung. *** “Coba gambarkan peta bagaimana seseorang yang berangkat dari kampus bisa mencapai rumah ini?” [tanya Daniel]. Sebelum Kinan membuka mulutnya, Alex segera membalas dengan sigap lengkap dengan irama dan aksen Flores yang merdu. “Jalan Godean terus saja sampai pasar, lalu belok kanan ke arah utara. Lima kilometer nanti bertemu perempatan, kau akan menemukan sebatang pohon beringin. Belok kiri, 300 meter dari sana masuklah ke Desa Pete, jalan terus melalui sekolah taman kanak-kanak yang berpagar merah, terus saja mengikuti jalan yang menurun. Nanti masuk lagi ke gang yang agak sempit, terus saja, nah, rumah di sebelah kiri, dengan patokan sebuah pohon beringin lain yang jauh lebih besar dan tua dan akar yang menggapai tanah.” Jawaban Alex bukan melegakan Daniel, tapi malah membuat wajah Manado yang putih itu menjadi merah. Daniel mempersoalkan bagaimana bisa mencapai rumah hantu itu jika untuk mengucapkan arah jalannya saja sudah makan waktu 15 menit. Bagaimana caranya kami menyampaikan informasi kepada kawan-kawan bahwa kini diskusi dan sekretariat mahasiswa Winatra sudah pindah ke tengah hutan Desa Pete? “Soal jarak dan keruwetan arah….”, Kinan menatap wajah Daniel yang tampaknya belum puas, “justru itu kelebihannya. Karena rumah hantu ini tersembunyi, kita akan aman. Rasanya para lalat itu akan sukar menemukan desa ini. Kita bebas mendiskusikan buku siapa saja, apakah karya Laclau atau Ben Anderson, atau bahkan novel Pak Pramoedya akan menghirup udara merdeka di sini.” Sumber: novel Laut Bercerita karya Leila S. Chudori Sunu adalah salah satu mahasiswa yang tergabung dalam kelompok mahasiswa Winatra. Ia hendak kembali ke kampusnya setelah mengikuti diskusi di sekretariat yang baru. Dia berjalan seorang diri. Ketika sampai di TK yang berpagar merah, Sunu lupa arah. Manakah arah yang tepat menuju Jalan Godean dari TK tersebut?'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Literasi Bahasa Indonesia', 3, 'Orang gila itu tidak bernama, sedang duduk di pojok jalan raya…. Jauh di sana, salak senapan bersahutan seperti para serigala di malam purnama. Orang-orang penghuni kota mungil itu ribut berlarian dengan teriak-teriakan yang tidak mungkin dipahami si Orang Gila. Mereka menjinjing barang-barang yang dikemas dalam buntalan-buntalan kecil dan keluar rumah dalam gerakan-gerakan bergegas. *** Setelah beberapa hari berlalu, kini ia merasa lapar. Di kota kecil yang mati itu ia terseok sendirian, mencoba mengais sampah. Tiada juga ada makanan. Ia telah kalah gesit dengan tikus-tikus dan kucing liar. Tak ada lagi Cut Diah berbaik hati memberinya makanan. Juga tak ada Wak Haji yang kerap memberinya roti dari toko. Ia terdampar kemudian di sebuah bangunan sekolah yang separuh hangus terbakar…. Foto presiden (presiden lama yang sudah terguling, bukan karena penguasa sekolah tidak tahu keberadaan presiden yang baru, tapi hal sepele mengganti foto tidak sempat mampir di ingatannya) masih tergantung sebelum dilalap api. *** Matanya nanar menatap perkampungan dan bibirnya bergetar hebat. Di sanalah, di sanalah, otaknya bekerja dengan susah payah, di sanalah kau bisa temukan makanan untuk menunaikan tugas besar kehidupan: berperang melawan kematian. Ia tak menemukan apa-apa untuk dimakan. Apa pun isi rumah tersebut tentunya telah dibawa oleh si pemilik. Dan kalau saja ada satu hal yang tersisa, tentu telah digondol para prajurit yang menjarah… Si Orang Gila itu lapar dan tergeletaklah. Ia mulai mengerang. 1999 Sumber: Cerpen “Hikayat Si Orang Gila” karya Eka Kurniawan I. Di tengah kekacauan kota, Si Orang Gila ke sana ke mari mencari makanan. II. Di kota kecil itu terjadi keributan karena presiden lama menggulingkan presiden baru. III. Terjadi penjarahan di rumah-rumah warga yang ditinggalkan pemiliknya. IV. Kota itu bertambah kacau karena terdapat bangunan publik yang dibakar. V. Terdapat korban jiwa akibat penembakan senapan. Pernyataan yang tepat untuk menggambarkan isi cuplikan cerpen tersebut adalah ….'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Literasi Bahasa Indonesia', 4, 'Orang gila itu tidak bernama, sedang duduk di pojok jalan raya…. Jauh di sana, salak senapan bersahutan seperti para serigala di malam purnama. Orang-orang penghuni kota mungil itu ribut berlarian dengan teriak-teriakan yang tidak mungkin dipahami si Orang Gila. Mereka menjinjing barang-barang yang dikemas dalam buntalan-buntalan kecil dan keluar rumah dalam gerakan-gerakan bergegas. *** Setelah beberapa hari berlalu, kini ia merasa lapar. Di kota kecil yang mati itu ia terseok sendirian, mencoba mengais sampah. Tiada juga ada makanan. Ia telah kalah gesit dengan tikus-tikus dan kucing liar. Tak ada lagi Cut Diah berbaik hati memberinya makanan. Juga tak ada Wak Haji yang kerap memberinya roti dari toko. Ia terdampar kemudian di sebuah bangunan sekolah yang separuh hangus terbakar…. Foto presiden (presiden lama yang sudah terguling, bukan karena penguasa sekolah tidak tahu keberadaan presiden yang baru, tapi hal sepele mengganti foto tidak sempat mampir di ingatannya) masih tergantung sebelum dilalap api. *** Matanya nanar menatap perkampungan dan bibirnya bergetar hebat. Di sanalah, di sanalah, otaknya bekerja dengan susah payah, di sanalah kau bisa temukan makanan untuk menunaikan tugas besar kehidupan: berperang melawan kematian. Ia tak menemukan apa-apa untuk dimakan. Apa pun isi rumah tersebut tentunya telah dibawa oleh si pemilik. Dan kalau saja ada satu hal yang tersisa, tentu telah digondol para prajurit yang menjarah… Si Orang Gila itu lapar dan tergeletaklah. Ia mulai mengerang. 1999 Sumber: Cerpen “Hikayat Si Orang Gila” karya Eka Kurniawan Bagaimana kondisi warga di kota kecil tersebut pada saat itu?'),
('PPU, PBM, dan Literasi dalam Bahasa Indonesia', 'Literasi Bahasa Indonesia', 5, 'Orang gila itu tidak bernama, sedang duduk di pojok jalan raya…. Jauh di sana, salak senapan bersahutan seperti para serigala di malam purnama. Orang-orang penghuni kota mungil itu ribut berlarian dengan teriak-teriakan yang tidak mungkin dipahami si Orang Gila. Mereka menjinjing barang-barang yang dikemas dalam buntalan-buntalan kecil dan keluar rumah dalam gerakan-gerakan bergegas. *** Setelah beberapa hari berlalu, kini ia merasa lapar. Di kota kecil yang mati itu ia terseok sendirian, mencoba mengais sampah. Tiada juga ada makanan. Ia telah kalah gesit dengan tikus-tikus dan kucing liar. Tak ada lagi Cut Diah berbaik hati memberinya makanan. Juga tak ada Wak Haji yang kerap memberinya roti dari toko. Ia terdampar kemudian di sebuah bangunan sekolah yang separuh hangus terbakar…. Foto presiden (presiden lama yang sudah terguling, bukan karena penguasa sekolah tidak tahu keberadaan presiden yang baru, tapi hal sepele mengganti foto tidak sempat mampir di ingatannya) masih tergantung sebelum dilalap api. *** Matanya nanar menatap perkampungan dan bibirnya bergetar hebat. Di sanalah, di sanalah, otaknya bekerja dengan susah payah, di sanalah kau bisa temukan makanan untuk menunaikan tugas besar kehidupan: berperang melawan kematian. Ia tak menemukan apa-apa untuk dimakan. Apa pun isi rumah tersebut tentunya telah dibawa oleh si pemilik. Dan kalau saja ada satu hal yang tersisa, tentu telah digondol para prajurit yang menjarah… Si Orang Gila itu lapar dan tergeletaklah. Ia mulai mengerang. 1999 Sumber: Cerpen “Hikayat Si Orang Gila” karya Eka Kurniawan Si Orang Gila mencari makan ke berbagai tempat, kecuali ke ….'),
('Literasi Bahasa Inggris', 'Get to Know All the Basics', 1, 'Marissa: “Ms. Linda is on maternity leave starting from next week.” Kia: “Oh my god, does that mean her classes will be independent study?” Marissa: “I don’t think so. I heard the teachers talking about a … teacher coming soon.” Which adjective is not suitable to fill in the blank?'),
('Literasi Bahasa Inggris', 'Get to Know All the Basics', 2, 'Fill in the blank with an appropriate form of the word. My friend texted the customer service for MCalls but they didn’t reply to her quickly and were …. All they did was give her basic template replies with … she already knew.'),
('Literasi Bahasa Inggris', 'Get to Know All the Basics', 3, 'Some ads use conversational slang and terms, undoubtedly to evoke a sense of youth — a time-hallowed positioning method that immediately makes the target demographic feel like a brand identifies with them. Source: thejakartapost.com The bolded word ‘them’ refers to ….'),
('Literasi Bahasa Inggris', 'Get to Know All the Basics', 4, 'Egypt has one of the largest and most complex pantheons of gods of any civilization in the ancient world. Over the course of Egyptian history hundreds of gods and goddesses were worshipped. The characteristics of individual gods could be hard to pin down. Source: britannica.com The underlined sentence should be replaced with ….'),
('Literasi Bahasa Inggris', 'Get to Know All the Basics', 5, 'Marissa was so fascinated when we brought her to the zoo. She saw a lot of animals at the facility. I think her favorite animal was the lemur. She couldn’t stop staring at it! She said …. I also think the same, its tail was quite fascinating. Fill in the blank to continue the statement.'),
('Literasi Bahasa Inggris', 'English Level 1', 1, 'Olympic swimmer Nick D\'Arcy, 21, had pleaded guilty to a charge of recklessly inflicting grievous bodily harm on Simon Cowley in a nightclub brawl last year and was sentenced in a Sydney court today. Prosecutors had asked the court to jail D\'Arcy but his lawyers pleaded for a non-custodial sentence, arguing that D\'Arcy had already suffered enough by being excluded from the 2008 Beijing Olympics. The judge in charge of the case agreed and handed D\'Arcy a suspended sentence of 14 months and 12 days, telling the court he had \"very good prospects of rehabilitation.\" Magistrate John Favretto said: \"There is nothing to suggest that he present a continuing danger to the community.” (1) Favretto accepted that D\'Arcy had been provoked by Cowley but said his response was excessive and intended to cause harm. He placed D\'Arcy on a good behaviour bond and ordered him to undergo an unique counselling for alcohol, stress and anger management (2). Favretto said: \"While there was only one punch, it must have been with considerable force given the extent of the injury. Simon Cowley must’ve been hurted badly.\" (3) Outside the court, D\'Arcy told reporters he regretted his actions and hoped Cowley would eventually forgive him. He said: \"It was a terrible situation, which I have apologised for, and I deeply regret and I do hope one day he will can forgive me.\" (4) The decision means D\'Arcy may be free to represent Australia at this year\'s World Championships in Rome after he qualified by winning the 200 metres butterfly at this month\'s national trials. “To hurt a fellow sportsperson is the biggest mistake I have ever made,” (5) D’Arcy was quoted in the press conference, “I must strive to be a better person, and I will not repeat such vile behavior.” Source: insidethegames.biz (with modifications) What can be inferred from the passage?'),
('Literasi Bahasa Inggris', 'English Level 1', 2, 'Olympic swimmer Nick D\'Arcy, 21, had pleaded guilty to a charge of recklessly inflicting grievous bodily harm on Simon Cowley in a nightclub brawl last year and was sentenced in a Sydney court today. Prosecutors had asked the court to jail D\'Arcy but his lawyers pleaded for a non-custodial sentence, arguing that D\'Arcy had already suffered enough by being excluded from the 2008 Beijing Olympics. The judge in charge of the case agreed and handed D\'Arcy a suspended sentence of 14 months and 12 days, telling the court he had \"very good prospects of rehabilitation.\" Magistrate John Favretto said: \"There is nothing to suggest that he present a continuing danger to the community.” (1) Favretto accepted that D\'Arcy had been provoked by Cowley but said his response was excessive and intended to cause harm. He placed D\'Arcy on a good behaviour bond and ordered him to undergo an unique counselling for alcohol, stress and anger management (2). Favretto said: \"While there was only one punch, it must have been with considerable force given the extent of the injury. Simon Cowley must’ve been hurted badly.\" (3) Outside the court, D\'Arcy told reporters he regretted his actions and hoped Cowley would eventually forgive him. He said: \"It was a terrible situation, which I have apologised for, and I deeply regret and I do hope one day he will can forgive me.\" (4) The decision means D\'Arcy may be free to represent Australia at this year\'s World Championships in Rome after he qualified by winning the 200 metres butterfly at this month\'s national trials. “To hurt a fellow sportsperson is the biggest mistake I have ever made,” (5) D’Arcy was quoted in the press conference, “I must strive to be a better person, and I will not repeat such vile behavior.” Source: insidethegames.biz (with modifications) All but one of the underlined parts of the passage are grammatically incorrect. Which one is grammatically correct?'),
('Literasi Bahasa Inggris', 'English Level 1', 3, 'Mona : Happy birthday, Adrian! … you have a long life ahead of you! Adrian : Thank you so much, Mona! I hope the same goes for you! Mona : Thanks! Anyway, is your family going anywhere for your birthday? Adrian : Yeah. My brother wants …, so my family is going to the lake up north. Mona : That big lake? Are you sure about that? That lake is scarily big. Adrian : It’s not that scary. I’ve … there three times! Fill in the blanks with the most suitable words!'),
('Literasi Bahasa Inggris', 'English Level 1', 4, 'There were two striking breakthroughs in recent times in the running world: Stephanie Davis, a 30-year-old with a full-time job in finance, running a personal record (PR) of 2:27:14 to win the British Olympic Marathon Trials in London in March; and Beth Potter, a 29-year-old Scottish triathlete, running 14:41 at the Podium 5K in Lancashire, U.K., a second quicker than the previous world record. Surprisingly, unlike most of their world-class rivals, Davis and Potter are not high-mileage runners. Speaking to Runner’s World, Potter said she runs just 30 miles a week, while Davis said her hard practice averaged 88K a week (54 miles) on the buildup to the Podium 5K. Source: runnersworld.com (with modifications) What can be inferred from the passage above?'),
('Literasi Bahasa Inggris', 'English Level 1', 5, 'Skies brightened a lot in the afternoon yesterday (1). This Wednesday, we won’t be as lucky. Wet weather will arrive and it will stick around through the evening. There’s a 75% chance of rain, which can help the ongoing drought across the region (2). Thursday will end up being the brightest, most pleasant day (3) with sunshine and seasonable temperatures. It will most likely be sunny for the whole day (4). Clouds will overspread the area Thursday night. A chilly rainfall is definitely coming on Friday evening, followed by a day-long thunderstorm on Saturday (5). It looks like we will clear out in time for Mother’s Day on Sunday. Source: nbcboston.com (with modifications) Which of the underlined parts of the passage does not contain an adverb of place or time?'),
('Literasi Bahasa Inggris', 'English Level 2', 1, '... is an essential way to increase your intelligence. Fill in the blank!'),
('Literasi Bahasa Inggris', 'English Level 2', 2, '…. If it happens to you one day, don’t despair. Even if you dropped your cell phone into the sink, toilet, or bathtub, you may be able to save it. The most important thing you can do is act fast. Take it out of the water as soon as possible. Then, turn it off, take out the battery, and remove all accessories. Try to remove as much water from it as you can with either towels or a vacuum cleaner. Focus on drying both the headphone jack and the charging port. Then, put it in a bowl of instant rice or any other absorbent material for 48-72 hours before turning it on. With a little luck and fast action, your cell phone may survive its brush with death. Source: wikihow.com (with modifications) Which of the following can be inferred from the passage?'),
('Literasi Bahasa Inggris', 'English Level 2', 3, 'Two years after announcing that he had retired from comics, Alan Moore, the illustrious author of Watchmen and V for Vendetta, has signed a six-figure deal for a “groundbreaking” five-volume fantasy series as well as a “momentous” collection of short stories. Bloomsbury, which published the Harry Potter novels, acquired what it described as two “major” projects from the 67-year-old. The first, Illuminations, is a short story collection which will be published in autumn 2022 and which moves from the four horsemen of the apocalypse to the “Boltzmann brains” fashioning the universe. Bloomsbury editor Ken Hyland said it was “dazzlingly original and brimming with energy”, promising a series of “beguiling and elegantly crafted tales that reveal the full power of imagination and magic”. The second acquisition is a fantasy quintet titled Long London, which will launch in 2024. The series will move from the “shell-shocked and unravelled” London of 1949 to “a version of London just beyond our knowledge”, encompassing murder, magic and madness. Bloomsbury said it “promises to be epic and unforgettable, a tour-de-force of magic and history”. Source: theguardian.com (with modifications) Which of the following questions is answered in the passage?'),
('Literasi Bahasa Inggris', 'English Level 2', 4, 'There were two striking breakthroughs in recent times in the running world: Stephanie Davis, a 30-year-old with a full-time job in finance, running a personal record (PR) of 2:27:14 to win the British Olympic Marathon Trials in London in March; and Beth Potter, a 29-year-old Scottish triathlete, running 14:41 at the Podium 5K in Lancashire, U.K., a second quicker than the previous world record. Surprisingly, unlike most of their world-class rivals, Davis and Potter are not high-mileage runners. Speaking to Runner’s World, Potter said she runs just 30 miles a week, while Davis said her hard practice averaged 88K a week (54 miles) on the buildup to the Podium 5K. Source: runnersworld.com (with modifications) What can be inferred from the passage above?'),
('Literasi Bahasa Inggris', 'English Level 2', 5, 'Toni : Excuse me, are you Ms. Li? Ms. Li : Oh my God, Toni? Is that you? Toni : Yes, it’s me! I thought you wouldn’t remember me! Ms. Li : I never forget my students! Wow, you’ve gotten so big. Is your sister with you? Toni : Um, no, she’s not. She’s in the hospital, actually. Ms. Li : Sweet child! What happened to her? Is she OK? Toni : She had an accident last week. She’s OK now, though. What cannot be inferred from the dialogue above?'),
('Literasi Bahasa Inggris', 'English Level 3', 1, 'The collapse of the colonial empires of the past and proclamation of independence of African countries did not mean the end of an era of exploitation of former dependent countries, both from the former colonial powers, and by the other industrialized world-powers. Classic colonialism, based on military coercion and implying incorporation of colonial territories into the political system of the metropolis, has given way to neocolonialism. The latter is a latent form, not based on direct coercion and deprivation of sovereignty exploitation of developing countries by the developed world-powers. Neocolonialism included numerous specific methods of political and economic manipulation. These include the planting of corruption and outright bribery of African political elites, the system of bonded loans, the use of so-called humanitarian aid as a tool of manipulation, the use of armed force in the name of maintenance of peace, and the use of inciting tribalist conflict. Source: inafran.ru (with modifications) Which of these statements is correct according to the passage?'),
('Literasi Bahasa Inggris', 'English Level 3', 2, 'Studying the biomechanics of the vertebra, Marianne Porter of Florida Atlantic University has found the relationship between the vertebral column and band pair changes in sharks. Small, medium and large specimens of seven shark species were examined and included shortfin mako, white, porbeagle, dusky, blue, common thresher, and Atlantic angel sharks. The goal of the study was to explore the potential relationship between band pair formation, vertebral structure and body shape, and not just age. Examining different species allowed differences in the band pair deposition rates, swimming style, body shapes, and maximum sizes to be considered. source : https://www.sciencedaily.com (with modification) How many gerund phrases and present participle phrases can you find in this paragraph?'),
('Literasi Bahasa Inggris', 'English Level 3', 3, 'Tama: Perhaps we should sell this cupboard for our next week\'s expense. Hana: You know what, ... Which sentence is correct to fill the blank in Hana\'s statement?');
INSERT INTO `utbk` (`kategori`, `sub_kategori`, `nomor`, `soal`) VALUES
('Literasi Bahasa Inggris', 'English Level 3', 4, 'Restaurante Botin is a cozy, family-owned restaurant in Madrid, Spain, located next to the Plaza Mayor and known for its traditional Spanish dishes. It also holds the Guinness World Record for being the oldest restaurant in the world! The restaurant was opened in 1725 by French chef Jean Botin, initially as an inn and tavern, under unique conditions and restrictions. Throughout the 18th century, it was illegal for tavern-owners to sell food themselves. Instead, diners would bring their own meat, wine, and food, and the restaurant would prepare it for them. This was a common Spanish practice not exclusive to Botin’s establishment, but Restaurante Botin is one of the few inns and taverns that has survived to this day, eventually transitioning into a modern-day restaurant. Source: travelawaits.com Which of these statements is true according to the passage?'),
('Literasi Bahasa Inggris', 'English Level 3', 5, 'I was at my friend’s house yesterday (1). We had been playing a new video game he bought (2). Sadly, we had to stop not long after that because there was a huge thunderstorm (3). It lasted for hours (4)! I was even stuck at his house and could only go home after dinner (5). Which sentence contains the Past Perfect Continuous Tense?'),
('PK & Penalaran Matematika', 'Logika Matematika', 1, '10, 15, 12, 17, 14, 19, dan .... '),
('PK & Penalaran Matematika', 'Logika Matematika', 2, '64, 63, 65, 64, W, 65, 67, dan 66. W = ....'),
('PK & Penalaran Matematika', 'Logika Matematika', 3, '1, 2, 3, 5, 6, 7, 1, 2, 3, 5, 6, 7, .... Suku ke 666 adalah ....'),
('PK & Penalaran Matematika', 'Logika Matematika', 4, 'K, A, M, C, O, E, Q, G, ..., ....'),
('PK & Penalaran Matematika', 'Logika Matematika', 5, 'AA, YY, BB, WW, CC, ...'),
('PK & Penalaran Matematika', 'Bilangan', 1, 'Dalam suatu penilaian, skor yang diperoleh dapat bernilai negatif. Zen memperoleh skor -10, Zeni memperoleh skor 10, Ius memperoleh skor -15, dan Zeus memperoleh skor 25. Urutan dari anak yang memperoleh skor terendah hingga skor tertinggi adalah …'),
('PK & Penalaran Matematika', 'Bilangan', 2, '20 - (-10) : (-5) + 3 × (-5) = ....'),
('PK & Penalaran Matematika', 'Bilangan', 3, 'Di sebuah taman terdapat 3 lampu berwarna merah, kuning, dan hijau. Lampu berwarna merah menyala 6 menit sekali, lampu kuning menyala 9 menit sekali, dan lampu hijau menyala 12 menit sekali. Zen sampai di taman tersebut tepat pukul 19.00 dan ketiga lampu tersebut menyala bersamaan. Pukul berapa ketiga lampu tersebut akan menyala bersamaan untuk kedua kalinya?'),
('PK & Penalaran Matematika', 'Bilangan', 4, 'Hasil dari 2,24:5,6 adalah ....'),
('PK & Penalaran Matematika', 'Bilangan', 5, 'Bentuk sederhana dari (22×46):82 adalah ....'),
('PK & Penalaran Matematika', 'Aljabar 1', 1, 'Harga sebuah jam dinding Rp 30.000,00 dan harga sebuah pigura Rp 15.000,00. Farid dapat membeli 2 buah jam dinding dengan semua uangnya. Berapa jumlah pigura yang dapat dibeli Farid dengan menggunakan semua uangnya ?'),
('PK & Penalaran Matematika', 'Aljabar 1', 2, 'Dodi ingin membangun sebuah rumah. Jika ada 9 pekerja bangunan yang membangun, rumah akan selesai dalam waktu 24 hari. Ternyata pekerja bangunan yang bisa membangun rumah Dodi hanya 6 orang, berapa lama para pekerjaan selesai membangun rumah Dodi ?'),
('PK & Penalaran Matematika', 'Aljabar 1', 3, 'Seorang peternak ayam mempunyai persediaan makanan untuk 48 ekor ayam selama 8 hari. Kemudian ada tetangganya yang menitipkan ayam untuk dirawat sebanyak 16 ekor. Berapa lama persediaan makanan peternak tersebut akan habis ?'),
('PK & Penalaran Matematika', 'Aljabar 1', 4, 'Diberikan x:y=3:4. Jika x=90, maka  y='),
('PK & Penalaran Matematika', 'Aljabar 1', 5, 'Tepung jenis A dan jenis B dicampur dengan perbandingan 2÷3. Diketahui berat tepung jenis B dalam campuran tersebut adalah 12 kg. Berapakah berat tepung jenis A dalam campuran tersebut?'),
('PK & Penalaran Matematika', 'Geometri 1', 1, 'Segitiga dengan panjang sisi-sisinya 2 cm, 7 cm, 9 cm akan terbentuk ....'),
('PK & Penalaran Matematika', 'Geometri 1', 2, 'Segitiga BDC sama kaki dengan BC=DC. Titik A terletak pada garis perpanjangan CB―. Jika p=36∘ dan q=50∘, maka nilai x adalah ….'),
('PK & Penalaran Matematika', 'Geometri 1', 3, 'If the area of a circle is 64π, then the circumference of the circle is ....'),
('PK & Penalaran Matematika', 'Geometri 1', 4, 'If the diameter of a circle increases by 50 percent, by what percent will the area of the circle increase?'),
('PK & Penalaran Matematika', 'Geometri 1', 5, 'Sebuah persegi panjang mempunyai sisi dengan panjang akar a cm dan akar b cm. berapakah panjang diagonalnya?'),
('PK & Penalaran Matematika', 'Data dan Ketidakpastian 1', 1, 'Pada sebuah rak terdapat 2 kardus yang masing-masing berisi satu lusin minuman. Kardus pertama terdiri dari 8 minuman rasa jeruk dan 4 minuman rasa leci, sedangkan pada kardus kedua, kedua rasa tersebut memiliki jumlah yang sama. Apabila ada pembeli membeli minuman rasa leci, berapa peluang terambilnya minuman dari kardus kedua?'),
('PK & Penalaran Matematika', 'Data dan Ketidakpastian 1', 2, 'Suatu desa terdiri dari 238 keluarga dengan rata-rata jumlah anggota setiap keluarga adalah 4 orang dan jumlah orang dewasa seluruhnya 580 orang. Suatu saat desa itu terserang wabah virus X dengan peluang tertular adalah 0,5 bagi anak-anak. Berapa orang anak yang diperkirakan akan tertular virus itu?'),
('PK & Penalaran Matematika', 'Data dan Ketidakpastian 1', 3, 'Sepasang pengantin baru yang baru saja melangsungkan pernikahan berencana mempunyai empat anak. Si suami menginginkan dari keempat anaknya itu nanti dua anak berjenis kelamin perempuan dan dua lainnya laki-laki. Sedangkan si istri menginginkan keempat anaknya terdiri dari tiga anak berjenis kelamin sama dan satu yang lainnya berbeda. Pernyataan yang paling tepat berdasarkan masalah tersebut bahwa peluang terjadinya keinginan suami adalah ....'),
('PK & Penalaran Matematika', 'Data dan Ketidakpastian 1', 4, 'Untuk memenuhi biaya pendidikan, Budi bekerja 15 jam setiap minggu. Ia bisa memilih waktu bekerja pada hari Jumat, Sabtu dan Minggu. Jika satuan waktu bekerja dihitung dalam jam dan ia harus bekerja paling sedikit 4 jam pada setiap hari tersebut, maka komposisi lama jam kerja Budi pada hari-hari tersebut yang mungkin ada sebanyak ...'),
('PK & Penalaran Matematika', 'Data dan Ketidakpastian 1', 5, 'Untuk membuat secara lengkap satu set rak sepatu, seorang tukang kayu membutuhkan 4 potong panel kayu panjang dan 6 panel kayu pendek. Tukang kayu memiliki persediaan panel kayu panjang dengan 5 pilihan warna dan panel kayu pendek dengan 7 pilihan warna. Jika panel kayu panjang harus dipasangkan dengan warna yang sama demikian juga halnya dengan panel kayu pendek tetapi panel kayu panjang tidak harus sewarna dengan panel kayu pendek, banyak variasi warna rak sepatu yang dapat dibuat adalah ....');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
