-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 16, 2025 at 03:19 PM
-- Server version: 8.0.30
-- PHP Version: 8.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bridge`
--

-- --------------------------------------------------------

--
-- Table structure for table `visimisi_kampus`
--

CREATE TABLE `visimisi_kampus` (
  `id` bigint UNSIGNED NOT NULL,
  `nama` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `visi` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `misi` text COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `visimisi_kampus`
--

INSERT INTO `visimisi_kampus` (`id`, `nama`, `visi`, `misi`) VALUES
(1, 'Universitas Gadjah Mada', 'Universitas Gadjah Mada sebagai pelopor perguruan tinggi nasional berkelas dunia yang unggul dan inovatif, mengabdi kepada kepentingan bangsa dan kemanusiaan dijiwai nilai-nilai budaya bangsa berdasarkan Pancasila.', 'Menjalankan pendidikan, penelitian, dan pengabdian kepada masyarakat serta pelestarian dan pengembangan ilmu yang unggul dan bermanfaat bagi masyarakat.'),
(2, 'Universitas Indonesia', 'Menjadi pusat ilmu pengetahuan, teknologi, dan kebudayaan yang unggul dan berdaya saing, melalui upaya mencerdasakan kehidupan bangsa untuk meningkatkan kesejahteraan masyarakat, sehingga berkontribusi bagi pembangunan masyarakat Indonesia dan dunia.', '1. Menyediakan akses yang luas dan adil, serta pendidikan dan pengajaran yang berkualitas.</br>\r\n2. Menyelenggarakan kegiatan Tridharma yang bermutu dan relevan dengan tantangan nasional serta global.</br>\r\n3. Menciptakan lulusan yang berintelektualitas tinggi, berbudi luhur dan mampu bersaing secara global.</br>\r\n4. Menciptakan iklim akademik yang mampu mendukung perwujudan visi UI'),
(3, 'Universitas Sumatera Utara', 'Menjadi perguruan tinggi yang memiliki keunggulan akademik sebagai barometer kemajuan ilmu pengetahuan yang mampu bersaing dalam tataran dunia global.', '1. Menyelenggarakan pendidikan tinggi berbasis otonomi yang menjadi wadah bagi pengembangan karakter dan profesionalisme sumber daya manusia yang didasarkan pada pemberdayaan yang mengandung semangat demokratisasi pendidikan yang mengakui kemajemukan dengan orientasi pendidikan yang menekankan pada aspek pencarian alternatif penyelesaian masalah aktual berlandaskan kajian ilmiah, moral, dan hati nurani.</br>\r\n2. Menghasilkan lulusan yang menjadi pelaku perubahan sebagai kekuatan modernisasi dalam kehidupan masyarakat luas, yang memiliki kompetensi keilmuan, relevansi dan daya saing yang kuat, serta berperilaku kecendikiawanan yang beretika.</br>\r\n3. Melaksanakan, mengembangkan, dan meningkatkan pendidikan, budaya penelitian dan program pengabdian masyarakat dalam rangka peningkatan kualitas akademik dengan mengembangkan ilmu yang unggul, yang bermanfaat bagi perubahan kehidupan masyarakat luas yang lebih baik.'),
(4, 'Universitas Airlangga', 'Menjadi universitas yang mandiri, inovatif, terkemuka di tingkat nasional dan internasional, pelopor pengembangan ilmu pengetahuan, teknologi, humaniora dan seni berdasarkan moral agama.', '1. Menyelenggarakan dan mengembangkan pendidikan akademik, profesi, dan/atau vokasi dengan keunggulan kelas dunia berlandaskan nilai kebangsaan dan moral agama.</br>\r\n2. Menyelenggarakan penelitian dasar, terapan, dan penelitian kebijakan yang inovatif dengan keunggulan kelas dunia berlandaskan nilai kebangsaan dan moral agama untuk menunjang pengembangan pendidikan dan pengabdian kepada masyarakat.</br>\r\n3. Mendarmabaktikan keahlian dalam bidang ilmu, teknologi, dan humaniora kepada masyarakat.</br>\r\n4. Mengelola universitas secara mandiri dengan tata kelola yang baik melalui pengembangan kelembagaan yang berorientasi pada mutu dan mampu bersaing di tingkat internasional.'),
(5, 'Universitas Hasanuddin', 'Pusat unggulan dalam pengembangan insani, ilmu pengetahuan, teknologi, seni, dan budaya berbasis Benua Maritim Indonesia.', '1. Menyediakan lingkungan belajar berkualitas untuk mengembangkan kapasitas pembelajar yang inovatif dan proaktif</br>\r\n2. Melestarikan, mengembangkan, menemukan, dan menciptakan ilmu pengetahuan, teknologi, seni, dan budaya</br>\r\n3. Menerapkan dan menyebarluaskan ilmu pengetahuan, teknologi, seni, dan budaya bagi kemaslahatan Benua Maritim Indonesia'),
(6, 'Universitas Andalas', 'Menjadi Universitas Terkemuka dan Bermartabat.', '1. Menyelenggarakan pendidikan yang berkualitas dan berkarakter untuk menghasilkan lulusan yang berdaya saing global dan berjiwa kewirausahaan;</br>\r\n2. Menyelenggarakan penelitian dan pengembangan ilmu pengetahuan, teknologi, seni, dan humaniora yang bereputasi internasional ;</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat yang inovatif, sesuai dengan perkembangan ilmu pengetahuan dan teknologi untuk mendukung pembangunan nasional; dan ;</br>\r\n4. Mengembangkan dan menerapkan tata kelola yang baik dan mampu beradaptasi dan bersinergi dengan lingkungan secara berkelanjutan.'),
(7, 'Universitas Padjadjaran', 'Mencapai Universitas Bereputasi Dunia dan Berdampak pada Masyarakat.', '1. Mewujudkan academic excellence dan memperoleh rekognisi nasional dan internasional.</br>\r\n2. Meningkatnya relevansi dan inovasi pendidikan, penelitian dan pengabdian pada masyarakat.</br>\r\n3. Mewujudkan kemandirian dengan kapitalisasi sumber daya internal dan kemitraan strategis.</br>\r\n4. Meningkatkan kontribusi Unpad dalam penyelesaian masalah yang berdampak pada kesejahteraan masyarakat Jawa Barat dan Indonesia.</br>\r\n5. Membangun karakter kepemimpinan dengan budaya kolektif, profesional, dan berintegritas dalam pengelolaan keberlanjutan Universitas.'),
(8, 'Universitas Diponegoro', 'Universitas Diponegoro Menjadi Universitas Riset yang Unggul.', '1. Menyelenggarakan pendidikan sehingga menghasilkan lulusan yang unggul dan kompetitif.</br>\r\n2. Menyelenggarakan penelitian yang menghasilkan publikasi, Hak Atas Kekayaan Intelektual (HAKI) , buku ajar, kebijakan dan teknologi yang berhasil guna dan berdaya guna dengan mengedepankan budaya dan sumber daya lokal.</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat yang menghasilkan publikasi, Hak Atas Kekayaan Intelektual (HAKI) , buku ajar, kebijakan dan teknologi yang berhasil guna dan berdaya guna dengan mengedepankan budaya dan sumber daya lokal.</br>\r\n4. Mengembangkan profesionalitas, kapabilitas, akuntabilitas dalam tata kelola universitas yang baik serta kemandirian penyelenggaraan perguruan tinggi.'),
(9, 'Universitas Sriwijaya', 'Menjadi Perguruan Tinggi terkemuka dan berbasis riset yang unggul dalam berbagai bidang ilmu Pengetahuan dan teknologi.', '1. Menyelenggarakan dan mengembangkan pendidikan tinggi dalam upaya menghasilkan manusia terdidik yang dapat menerapkan, mengembangkan, dan/atau menciptakan ilmu pengetahuan, teknologi, dan/atau seni.</br>\r\n2. Menyelenggarakan dan mengembangkan penelitian dalam rangka meningkatkan kualitas pembelajaran, ilmu pengetahuan, teknologi, dan/atau seni serta memiliki nilai aplikasi dalam pembangunan.</br>\r\n3. Menyelenggarakan dan mengembangkan pengabdian kepada masyarakat dengan menerapkan ilmu pengetahuan, teknologi, dan/atau seni untuk mewujudkan kesejahteraan dan kemajuan masyarakat.</br>\r\n4. Menyelenggarakan pembinaan dan pengembangan bakat, minat, penalaran, dan kesejahteraan mahasiswa.</br>\r\n5. Menyelenggarakan kerja sama dengan lembaga lain, baik nasional maupun internasional.</br>\r\n6. Mewujudkan sistem manajemen yang profesional, efektif, efisien, dan akuntabel.'),
(10, 'Universitas Lambung Mangkurat', 'Terwujudnya ULM sebagai Universitas terkemuka dan berdaya saing di bidang lingkungan lahan basah.', '1. Menyelenggarakan Tridharma Perguruan Tinggi yang berkeadilan, berkesetaraan, berkualitas, dan relevan dengan perkembangan IPTEKS yang berfokus pada program unggulan lingkungan lahan basah.</br>\r\n2. Menyelenggarakan penguatan tata kelola universitas berdasarkan tata kelola universitas yang baik (goodgovernance), mengembangkan kelembagaan, meningkatkan kualitas SDM dan sarana prasarana.</br>\r\n3. Menyelenggarakan pendidikan yang berbasis karakter waja sampai kaputing atau wasaka (tetap bersemangat dan kuat bagaikan baja dari awal sampai akhir) dan berdaya saing internasional.</br>\r\n4. Menyelenggarakan kerjasama dengan berbagai perguruan tinggi dalam dan luar negeri, pemerintah pusat dan daerah, dunia usaha dan industri, serta pemangku kepentingan lainnya pada tingkat nasional dan internasional.'),
(11, 'Universitas Syiah Kuala', 'USK memiliki visi menjadi universitas sosio-teknopreneur yang inovatif, mandiri, dan terkemuka di tingkat global.', '1. Menyelenggarakan pendidikan tinggi berkualitas unggul untuk menghasilkan lulusan yang memiliki kompetensi dan karakter sosio-teknopreneur yang berdaya saing tinggi.</br>\r\n2. Menyelenggarakan penelitian dan pengabdian kepada masyarakat berlandaskan sosioteknopreneur yang unggul, inovatif, berdaya saing, dan berkelanjutan.</br>\r\n3. Memperkuat dan memperluas jaringan kerja sama institusional untuk mengembangkan dan melestarikan ilmu pengetahuan dan teknologi.</br>\r\n4. Menerapkan manajemen mutu terpadu di bidang akademik dan nonakademik melalui penerapan prinsip transparansi, partisipatit produktif, efektif, dan efisien serta menyelenggarakan pendidikan tinggi dengan tata kelola yang akuntabel.'),
(12, 'Universitas Sam Ratulangi', 'Bersama menata Universitas Sam Ratulangi menjadi Universitas Unggul dan Berbudaya.', 'Terdepan dalam Mengemban Tridharma Perguruan Tinggi dan sebagai Pusat Inovasi Ilmu Pengetahuan, Teknologi dan Seni-Budaya guna Peningkatan Taraf dan Kualitas Kehidupan Masyarakat.'),
(13, 'Universitas Udayana', 'Terwujudnya perguruan tinggi yang unggul, mandiri, dan berbudaya.', '1. Menyelenggarakan pendidikan tinggi yang bermutu dan menghasilkan lulusan yang memiliki moral/etika/akhlak dan integritas yang tinggi sesuai dengan tuntutan masyarakat lokal, nasional, dan internasional</br>\r\n2. Mengembangkan penelitian dan pengabdian kepada masyarakat sesuai dengan kepentingan masyarakat dan bangsa</br>\r\n3. Memberdayakan Unud sebagai lembaga yang menghasilkan dan mengembangkan pengetahuan, teknologi, dan budaya yang dapat dimanfaatkan untuk kesejahteraan masyarakat; dan</br>\r\n4. Menghasilkan karya inovatif dan prospektif bagi kemajuan Unud serta perekonomian nasional.'),
(14, 'Universitas Nusa Cendana', 'Perguruan Tinggi Berorientasi Global.', '1. Mewujudkan pendidikan tinggi bermutu, relevan dan berdaya saing.</br>\r\n2. Menjadi universitas riset dalam bidang lahan kering kepulauan.</br>\r\n3. Mewujudkan pengabdian pada masyarakat yang berorientasi kesejahteraan masyarakat.</br>\r\n4. Mewujudkan organisasi pendidikan tinggi yang sehat dalam konteks good university governance.'),
(15, 'Universitas Mulawarman', 'Universitas berstandar internasional yang mampu berperan dalam pembangunan bangsa melalui pendidikan, penelitian, dan pengabdian kepada masyarakat yang bertumpu pada sumber daya alam (sda) khususnya hutan tropis lembab (tropical rain forest) dan lingkungannya.', '1. Menghasilkan sumber daya manusia yang berkualitas, berkepribadian, dan profesional melalui penyelenggaraan pendidikan tinggi yang bertaraf Internasional.</br>\r\n2. Menghasilkan riset yang berkualitas serta berdayaguna dengan mengedepankan prinsip-prinsip kelestarian lingkungan hidup.</br>\r\n3. Menyelenggarakan kegiatan pengabdian pada kepada masyarakat dan menghasilkan karya ilmu pengetahuan, teknologi, seni, dan olahraga yang bermakna dan bermanfaat demi terwujudnya pengelolaan universitas yang akuntabel dan mandiri sesuai dengan standar nasional dan internasional.'),
(16, 'Universitas Mataram', 'Menjadi lembaga pendidikan tinggi berbasis riset berdaya saing internasional tahun 2025.', '1. Melaksanakan proses pendidikan tinggi berstandar mutu nasional dan internasional yang berbasis riset yang kuat dalam rangka untuk menghasilkan sumber daya manusia beriman dan bertaqwa kepada Tuhan Yang Maha Esa, berbudi luhur, memiliki kompetensi dalam bidang-bidangnya dan berwawasan global.</br>\r\n2. Melaksanakan kegiatan riset berstandar mutu nasional dan internasional untuk menghasilkan ilmu pengetahuan dan teknologi yang dapat menambah hasanah ilmu pengetahuan, dan menjadi rujukan pemecahan masalah di masyarakat, dalam rangka mendukung proses pembelajaran bermutu kepada mahasiswa dan pengabdian kepada masyarakat.</br>\r\n3. Melaksanakan kegiatan pengabdian kepada masyarakat yang berdasarkan pada hasil riset, dalam rangka memberikan kontribusi untuk memecahkan berbagai persoalan yang timbul di masyaraka, mendorong pertumbuhan ekonomi dan membangun sosial serta budaya masyarakat Indonesia.</br>\r\n4. Membangun jaringan kerjasama yang luas dengan berbagai pihak, instansi pemerintah dan swasta, di dalam dan di luar negeri dalam rangka untuk mendukung pelaksanaan Tri Dharma Perguruan Tinggi yang berstandar mutu nasional dan internasional.</br>\r\n5. Melaksanakan tata kelola aset keuangan dan administrasi yang memenuhi standar tata kelola Universitas yang baik, efesien, efektif, transparan dan akuntabel (good university govermance), dalam rangka untuk mendukung pelaksanaan Tri Dharma Perguruan Tinggi yang berstandar mutu nasional dan internasional.'),
(17, 'Universitas Riau', 'Menjadi Universitas Riset Unggul Bermartabat di Bidang Sains dan Teknologi di Kawasan Asia Tenggara Tahun 2035.', '1. Menyelenggarakan tri dharma perguruan tinggi yang unggul.</br>\r\n2. Melaksanakan tata kelola universitas yang bermartabat.</br>\r\n3. Mengembangkan potensi keunggulan mahasiswa.</br>\r\n4. Menciptakan sistem informasi yang handal dan menerapkan inovasi bagi kepentingan masyarakat.'),
(18, 'Universitas Cenderawasih', 'Terwujudnya Universitas Cenderawasih yang berdaya saing, berkarakter budaya dan berwawasan lingkungan pada Tahun 2025.', '1. Menyiapkan lulusan yang bermutu, cerdas dan kompetitif, berwawasan budaya dan lingkungan.</br>\r\n2. Mengembangkan Ilmu Pengetahuan Teknologi, dan Seni berbasis budaya dan berwawasan lingkungan.</br>\r\n3. Meningkatkan mutu tata kelola pendidikan tinggi yang terintegrasi.'),
(19, 'Universitas Brawijaya', 'Menjadi perguruan tinggi pelopor dan pembaharu dengan reputasi internasional dalam ilmu pengetahuan dan teknologi, terutama yang menunjangindustri berbasis budaya untuk kesejahteraan masyarakat.', '1. Menyelenggarakan pendidikan berstandar internasional yang menghasilkan lulusan yang beriman dan bertakwa kepada Tuhan Yang Maha Esa, serta memiliki moral dan akhlak yang luhur, mandiri, serta profesional, dan berjiwa kewirausahaan;</br>\r\n2. Menyelenggarakan penelitian untuk menghasilkan ilmu pengetahuan dan teknologi yang ber’manfaat bagi masyarakat;</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat untuk meningkatkan peran pergurLlan tinggi sebagai agen pembaruan, pelopor dan penyebar ilmu pengetahuan dan teknologi, serta sebagai agen pembangunan ekonomi bangsa dengan berdasar pada nilai kearifan lokal yang luhur</br>\r\n4. Menyelenggarakan pendidikan tinggi dan mengelola perguruan tinggi yang unggul, berkeadilan, dan berkelanjutan.'),
(20, 'Universitas Jambi', 'Menjadikan UNJA Sebagai A World-Class Enterprenuership University Di Bidang Agroindustri dan Lingkungan.', '1. Mengupayakan dan menjamin akses pendidikan tinggi yang berkualitas dan terjangkau bagi seluruh lapisan masyarakat dengan berlandaskan pada asas kesetaraan serta layanan prima pendidikan tinggi.</br>\r\n2. Mengembangkan dan menyebarluaskan ilmu pengetahuan, teknologi dan seni melalui pendidikan, penelitian dan pengabdian kepada masyarakat.</br>\r\n3. Melaksanakan pendidikan berkualitas serta mengembangkan kreativitas entrepreneur sesuai dengan bakat dan minat mahasiswa.</br>\r\n4. Menghasilkan para lulusan entrepreneur dari berbagai bidang keilmuan yang kompetitif serta mampu mengaplikasikan ilmu sesuai bidangnya secara professional.</br>\r\n5. Melaksanakan berbagai penelitian kreatif dan inovatif yang mendukung pelaksanaan pendidikan entrepreneur yang berkualitas untuk menghasilkan lulusan yang kompetitif, baik di tingkat nasional maupun internasional.</br>\r\n6. Meningkatkan standar mutu akademik yang berstandar Nasional dan Internasional.'),
(21, 'Universitas Pattimura', 'Menjadi Pusat Pengembangan Sumber Daya Manusia, Ilmu Pengetahuan, Teknologi dan Seni yang Unggul, Berkarakter, Berbudaya dan Berbasis Laut Pulau.', '1. Meningkatkan kualitas pendidikan untuk menghasilkan lulusan yang kompeten dan berkarakter berbasis laut pulau.</br>\r\n2. Mengembangkan ilmu pengetahuan, teknologi dan seni melalui riset berbasis laut pulau yang berkualitas internasional.</br>\r\n3. Implementasi dan diseminasi hasil-hasil kajian ilmu, teknologi dan seni untuk pembangunan masyarakat.'),
(22, 'Universitas Tanjungpura', 'Menjadi institusi preservasi dan pusat informasi ilmiah di Kalimantan Barat, serta menghasilkan luaran yang bermoral Pancasila dan mampu berkompetisi di tingkat dunia, baik ditingkat daerah, nasional, regional maupun internasional.', '1. Menyelenggarakan pendidikan tinggi untuk menghasilkan luaran yang berkualitas dan bermoral Pancasila, serta mampu mengikuti, mengembangkan dan memajukan ilmu pengetahuan dan teknologi.</br>\r\n2. Menyelenggarakan penelitian dan pengabdian kepada masyarakat untuk menjadi sebuah institusi preservasi dan pusat informasi Kalimantan Barat.'),
(23, 'Universitas Jenderal Soedirman', 'UNSOED dalam pengembangannya akan mewujudkan visi yang telah dirumuskan untuk diwujudkan pada tahun 2034 yaitu “Diakui dunia sebagai pusat pengembangan sumberdaya perdesaan dan kearifan lokal\".', '1. Menyelenggarakan pembelajaran berkualitas tinggi untuk menghasilkan lulusan yang berkarakter, berkualitas, dan berdaya saing tinggi.</br>\r\n2. Mengembangkan penelitian dan inovasi unggul untuk pengembangan ilmu dan peningkatan daya saing bangsa.</br>\r\n3. Mengembangkan program pemberdayaan masyarakat dan transfer teknologi berkualitas tinggi untuk meningkatkan kesejahteraan masyarakat.</br>\r\n4. Meningkatkan kualitas kerjasama dengan mitra untuk meningkatkan kemandirian dan partisipasi institusi pada pengembangan masyarakat.</br>\r\n5. Mengembangkan tatapamong universitas yang baik.'),
(24, 'Universitas Palangka Raya', 'Menjadi perguruan tinggi yang Unggul, Mandiri, dan Berkarakter pada tahun 2038.', '1. Menyelenggarakan proses pendidikan dan pengajaran yang unggul, untuk menghasilkan lulusan berdaya saing tinggi pada skala nasional, maupun internasional.</br>\r\n2. Menciptakan suasana akademik yang mengembangkan karakter kejujuran, kedisiplinan, kemampuan bekerjasama, integritas, loyalitas, bertanggungjawab, dan toleransi.</br>\r\n3. Menyelenggarakan penelitian dan pengembangan ilmu pengetahuan yang berorientasi pada publikasi ilmiah nasional, dan internasional bereputasi.</br>\r\n4. Menyelenggarakan pengabdian pada masyarakat berdasarkan hasil-hasil penelitian, untuk meningkatkan kualitas dan kesejahteraan masyarakat Indonesia.</br>\r\n5. Menyelenggarakan proses pendidikan yang bermutu dan dipercaya masyarakat, dengan berpedoman pada sistem penjaminan mutu perguruan tinggi nasional, maupun internasional.'),
(25, 'Universitas Jember', 'Menjadi Universitas unggul dalam pengembangan sains, teknologi dan seni berwawasan lingkungan, bisnis, dan pertanian industrial.', '1. Melaksanakan dan mengembangkan pendidikan akademik, vokasi, dan profesi yang berkualitas dan berwawasan ecotechnopreneurship.</br>\r\n2. Mengembangkan sains, teknologi, dan, seni yang inovatif, berwawasan lingkungan, bisnis, dan, pertanian industrial untuk kesejahteraan mayarakat.</br>\r\n3. Memberdayakan masyarakat agribisnis dengan menerapkan teknologi tepat guna berbasis kearifan lokal.</br>\r\n4. Mengembangkan sistem pengelolaan Universitas yang akuntabel dan bertaraf internasional.</br>\r\n5. Mengembangkan jaringan kerjasama dengan stakesholders dan lembaga lain di dalam dan d luar negeri.'),
(26, 'Universitas Lampung', 'Universitas Lampung menjadi Center of Excellence di tingkat Nasional dan Internasional sebagai Institusi yang kuat (BE STRONG) berlandaskan nilai-nilai luhur budaya Nasional dan Pancasila.', 'Menerapkan Tridharma Perguruan Tinggi yang berkualitas guna menghasilkan sumber daya manusia yang adaptif dan fleksibel terhadap perubahan serta inovasi yang bermanfaat bagi peningkatan daya saing bangsa.'),
(27, 'Universitas Sebelas Maret', 'Menjadi pusat pengembangan ilmu pengetahuan, teknologi, dan seni yang unggul di tingkat internasional dengan berlandaskan pada nilai luhur budaya nasional.', '1. Menyelenggarakan pendidikan dan pengajaran yang menuntut pengembangan diri Dosen dan mendorong kemandirian Mahasiswa dalam memperoleh pengetahuan, keterampilan, dan sikap.</br>\r\n2. Menyelenggarakan penelitian yang berbasis pada penemuan baru di bidang ilmu pengetahuan, teknologi, dan seni.</br>\r\n3. Menyelenggarakan kegiatan pengabdian masyarakat yang berorientasi pada upaya pemberdayaan masyarakat.'),
(28, 'Universitas Tadulako', 'Universitas Tadulako Menjadi Perguruan Tinggi Berstandar Internasional Dalam Pengembangan IPTEKS Berwawasan Lingkungan Hidup', '1.Menyelenggarakan pendidikan yang bermutu, modern, dan relevan menuju pencapaian standar internasional dalam pengembangan IPTEKS berwawasan lingkungan hidup.</br>\r\n2.Menyelenggarakan penelitian yang bermutu untuk pengembangan IPTEKS berwawasan lingkungan hidup.</br>\r\n3.Menyelenggarakan pengabdian kepada masyarakat sebagai pemanfaatan hasil pendidikan dan hasil penelitian yang dibutuhkan dalam pembangunan masyarakat.</br>\r\n4.Menyelenggarakan akan reformasi birokrasi dan kerja sama regional, nasional, dan internasional.'),
(29, 'Universitas Halu Oleo', 'Menjadi Perguruan Tinggi Kelas Dunia dalam Pengelolaan dan Pengembangan Wilayah Pesisir, Kelautan dan Perdesaan pada Tahun 2045.', '1. Mengembangkan pendidikan berbasis riset kolaborasi nasional dan/atau internasional dengan memanfaatkan kemajuan teknologi informasi sehingga lulusannya mampu bersaing, dan beradaptasi dalam kancah global;</br>\r\n2. Mengembangkan penelitian unggulan yang berorientasi wilayah pesisir, kelautan, dan perdesaan, serta publikasi dan perolehan kekayaan intelektual;</br>\r\n3. Menerapkan hasil penelitian dan produk intelektual yang berstandar nasional dan/atau internasional bagi kesejahteraan institusi dan masyarakat, serta kemajuan ilmu pengetahuan dan teknologi;</br>\r\n4. Menguatkan sistem tata kelola UHO yang transparan, akuntabel, dan kredibel sehingga mampu memberikan layanan prima pendidikanbermutu tinggi;</br>\r\n5. Mengembangkan potensi mahasiswa di bidang kerohanian, penalaran, olahraga, seni, budaya, dan kewirausahaan yang mendukung kecerdasan komprehensif untuk membangun atmosfer akademik; dan</br>\r\n6. Mengembangkan kampus yang bersih, indah, sejuk, aman, jujur, adil, gotong royong, adaptif, disiplin, kreatif, inovatif, toleran, dan amanah untuk mendukung penyelenggaraan tridharma perguruan tinggi;'),
(30, 'Universitas Bengkulu', 'Menjadi universitas kelas dunia pada tahun 2025.', '1. Mengembangkan pendidikan dan penelitian berkelas dunia;</br>\r\n2. Menghasilkan karya berstatus Hak atas Kekayaan Intelektual (HKI);</br>\r\n3. Melaksanakan pengabdian sesuai dengan kebutuhan masyarakat lokal, nasional, dan internasional;</br>\r\n4. Mengembangkan sistem tata kelola universitas yang baik dan bersih.'),
(31, 'Universitas Terbuka', 'Menjadi Perguruan Tinggi Terbuka dan Jarak Jauh Berkualitas Dunia.', '1. Meningkatkan daya tampung perguruan tinggi negeri.</br>\r\n2. Meningkatkan pemerataan akses pendidikan tinggi yang berkualitas dunia.</br>\r\n3. Mengembangkan budaya belajar sepanjang hayat.</br>\r\n4. Mendiseminasikan hasil kajian keilmuan dan pendidikan jarak jauh untuk mendukung pembangunan nasional dan global.'),
(32, 'Universitas Negeri Padang', 'Menjadi Universitas Bermartabat dan Bereputasi Internasional.', '1. Melaksanakan pendidikan berkualitas internasional.</br>\r\n2. Melaksanakan penelitian inovatif dan publikasi global.</br>\r\n3. Melaksanakan pengabdian kepada masyarakat untuk memecahkan masalah dan berkontribusi bagi pembangunan bangsa Indonesia.</br>\r\n4. Menerapkan tata kelola universitas kelas dunia.</br>\r\n5. Melaksanakan kerja sama internasional.'),
(33, 'Universitas Negeri Malang', 'Menjadi perguruan tinggi unggul dan rujukan bidang kependidikan, ilmu pengetahuan, teknologi, dan humaniora.', '1. Menyelenggarakan pendidikan dan pembelajaran yang unggul.</br>\r\n2. Menyelenggarakan penelitian yang unggul untuk menghasilkan temuan baru dan bermanfaat bagi masyarakat.</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat yang unggul untuk memberdayakan dan menyejahterakan masyarakat; di bidang kependidikan, ilmu pengetahuan, teknologi, dan humaniora.'),
(34, 'Universitas Pendidikan Indonesia', 'Sejalan dengan arah pengembangan, jati diri, dan tantangan ke depan, rumusan visi Universitas Pendidikan Indonesia adalah Pelopor dan Unggul (Leading and Outstanding).', '1. Menyelenggarakan pendidikan dengan membina dan mengembangkan disiplin ilmu pendidikan dan pendidikan disiplin ilmu, serta disiplin ilmu agama, ilmu sosial, ilmu alam, ilmu formal, dan ilmu terapan secara proporsional untuk memperkuat disiplin ilmu pendidikan dan pendidikan disiplin ilmu.</br>\r\n2. Mengembangkan Pendidikan Profesional Guru yang terintegrasi dalam pendidikan akademik dan profesi untuk semua jalur dan jenjang pendidikan.</br>\r\n3. Menyebarluaskan pengalaman dan temuan-temuan inovatif dalam disiplin ilmu pendidikan, pendidikan disiplin ilmu, ilmu agama, ilmu humaniora, ilmu sosial, ilmu alam, ilmu formal, dan ilmu terapan demi kemajuan masyarakat.'),
(35, 'Universitas Negeri Manado', 'UNIMA Unggul dan Inovatif Berdasarkan MAPALUS.', '1. Mewujudkan penyelenggaraan pendidikan dan pembelajaran yang bermutu dalam bidang kependidikan dan non kependidikan.</br>\r\n2. Mewujudkan penyelenggaraan penelitian dan pengembangan dalam menghasilkan inovasi bagi pengembangan IPTEK dan pemecahan masalah pembangunan.</br>\r\n3. Mewujudkan kesejahteraan masyarakat melalui transfer ilmu pengetahuan dan difusi hasil teknologi.</br>\r\n4. Mewujudkan tata kelola universitas yang baik, (university good governance) berbasis teknologi informasi dan komunikasi.</br>\r\n5. Memperkuat pilar-pilar karakter dalam meningkatkan integritas berdasarkan nilai-nilai Pancasila.'),
(36, 'Universitas Negeri Makassar', 'UNM sebagai pusat pendidikan, pengkajian dan pengembangan pendidikan, sains, teknologi, dan seni berwawasan kependidikan dan kewirausahaan.', '1. Menyelenggarakan kegiatan Tridharma untuk menghasilkan sumber daya manusia profesional dalam bidang kependidikan dan nonkependidkan yang berwawasan kewirausahaan.</br>\r\n2. Menciptakan iklim dan budaya akademik yang kondusif sesuai dengan prinsip tata kelola yang baik ( good university governance).</br>\r\n3. Mengembangkan UNM menjadi universitas penelitian dan pengajaran (teaching and research university) yang dapat memenuhi kebutuhan pembangunan bangsa.</br>\r\n4. Memberikan layanan kepada masyarakat untuk peningkatan kualitas hidup masyarakat, bangsa, dan negara.</br>\r\n5. Mengembangkan jejaring dengan pemerintah, swasta, dan/atau/institusi/lembaga/badan lain pada tingkat nasional da internasional.'),
(37, 'Universitas Negeri Jakarta', 'Menjadi universitas yang bereputasi di kawasan Asia.', 'Menyelenggarakan tridharma perguruan tinggi yang unggul dan berguna bagi kemaslahatan manusia.'),
(38, 'Universitas Negeri Yogyakarta', 'Menjadi universitas kependidikan kelas dunia yang unggul, kreatif, dan inovatif berkelanjutan.', '1. Menyelenggarakan pendidikan jalur akademik, vokasi, dan profesi yang unggul, kreatif, dan inovatif berkelanjutan.</br>\r\n2. Menyelenggarakan penelitian dan pengembangan di bidang ilmu sains dan teknologi, sosial humaniora, olahraga-kesehatan, dan senibudaya yang unggul, kreatif, dan inovatif berkelanjutan.</br>\r\n3. Menyelenggarakan kegiatan pengabdian pada masyarakat yang unggul, kreatif, dan inovatif berkelanjutan bagi pemberdayaan dan kesejahteraan masyarakat.</br>\r\n4. Menyelenggarakan dan membangun jejaring yang berkelanjutan di tingkat. nasional dan internasional.</br>\r\n5. Menyelenggarakan tata kelola kelembagaan, layanan, dan penjaminan mutu yang transparan dan akuntabel.'),
(39, 'Universitas Negeri Surabaya', 'UNESA memiliki visi menjadi universitas kependidikan yang tangguh, adaptif, dan inovatif yang berbasis kewirausahaan.', '1. Menyelenggarakan pendidikan di bidang kependidikan dan nonkependidikan yang berkarakter tangguh, adaptif, dan inovatif yang berbasis kewirausahaan.</br>\r\n2. Menyelenggarakan penelitian dan meningkatkan kualitas inovasi di bidang kependidikan dan nonkependidikan yang berbasis kewirausahaan.</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat dan menyebarluaskan inovasi di bidang kependidikan dan nonkependidikan yang berbasis kewirausahaan bagi kesejahteraan masyarakat.</br>\r\n4. Menyelenggarakan kegiatan tridharma pergunran tinggi melalui sistem multikampus secara sinergi, terintegrasi, harmonis, dan berkelanjutan dengan memperhatikan keunggulan UNESA.</br>\r\n5. Menyelenggarakan tata kelola yang efektif, efisien, transparan, dan akuntabel yang menjamin mutu secara berkelanjutan.</br>\r\n6. Menyelenggarakan kerja sarna nasional dan internasional yang produktif dalam menciptakan, mengembangkan, dan menyebarluaskan inovasi di bidang kependidikan dan nonkependidikan yang berbasis kewirausahaan.'),
(40, 'Universitas Negeri Medan', 'Menjadi universitas yang unggul di bidang pendidikan, rekayasa industri dan budaya.', '1. Menyeleng­garakan pendidikan, penelitian, dan pengabdian kepada masyarakat serta kerjasama dengan berbagai instansi dalam dan luar negeri.</br>\r\n2. Mengembangkan Unimed menjadi teaching and research institution yang unggul.</br>\r\n3. Mengembangkan rekayasa industri dan teknologi yang kreatif.</br>\r\n4. Mengembangkan budaya ilmiah dan budaya etnik, kewirausahaan.</br>\r\n5. Membina iklim organisasi dan suasana akademik yang sehat.'),
(41, 'Universitas Negeri Semarang', 'Menjadi Universitas Bereputasi Dunia dan Pelopor Kecemerlangan Pendidikan yang Berwawasan Konservasi.', '1. Menyelenggarakan pendidikan yang cemerlang dan bereputasi dunia.</br>\r\n2. Melaksanakan penelitian dalam mengembangkan ilmu pengetahuan dan teknologi.</br>\r\n3. Melaksanakan pengabdian kepada masyarakat untuk memecahkan masalah, memberdayakan, dan menyejahterakan masyarakat.</br>\r\n4. Menerapkan tata kelola yang baik dan mampu beradaptasi dan bersinergi dengan lingkungan secara berkelanjutan.</br>\r\n5. Melaksanakan kerja sama dalam membangun reputasi.'),
(42, 'Universitas Sultan Ageng Tirtayasa', 'Terwujudnya Untirta Sebagai Healthy, Integrated, Smart and Green (HITS Green) University yang Unggul, Berkarakter dan Berdaya Saing Global pada Tahun 2035.', '1. Meningkatkan kualitas, relevansi dan daya saing pendidikan serta lulusan yang unggul, berkarakter dan berdaya saing.</br>\r\n2. Meningkatkan kualitas dan kuantitas penelitian dan pengabdian kepada masyarakat yang inovatif berbasis kebutuhan nyata sesuai perkembangan zaman.</br>\r\n3. Meningkatkan daya dukung tatakelola perguruan tinggi yang baik sebagai implementasi dari Healthy, Integrated, Smart and Green (HITS Green) University.'),
(43, 'Universitas Trunojoyo Madura', 'Visi UTM adalah \"Pada tahun 2030 menjadi institusi yang mampu mewujudkan lulusan yang cerdas, berdaya saing, berakhlakul karimah dan unggul dalam pendidikan serta riset berdasarkan potensi Madura \".', '1. Menyelenggarakan layanan pendidikan yang berkualitas, relevan dan kompeten untuk penguatan ilmu pengetahuan, teknologi serta iman dan takwa;</br>\r\n2. Menyelenggarakan kegiatan penelitian dan pengabdianmasyarakat berdasarkan potensi Madura secara berkesinambungan dalam mendukung proses pembelajaran dan publikasi ilmiah;</br>\r\n3. Meningkatkan jejaring kerja sama dengan pemerintah, swasta, industri, pondok pesantren, alumni dan lembaga pendidikan di dalam dan luar negeri yang dapat menunjang pengembangan potensi Madura; dan</br>\r\n4. Meningkatkan tata kelola perguruan tinggi menggunakan prinsip kredibel, transparan, akuntabel, tanggung jawab, dan adil.'),
(44, 'Universitas Khairun', 'Menjadikan universitas yang bermutu berbasis kepulauan dan kemajemukan.', '1. Menghasilkan manusia yang bertaqwa kepada Tuhan Yang Maha Esa, berkualitas, berakhlak mulia, berbudaya, bersemangat ilmiah, dan menguasai serta mampu mempergunakan ilmu pengetahuan, teknologi, dan seni untuk meningkatkan kesejahteraan masyarakat.</br>\r\n2. Menyelenggarakan, mengembangkan, dan membina pendidikan tinggi dalam upaya menghasilkan manusia terdidik yang dapat menerapkan, mengambangkan, dan/atau menciptakan ilmu pengetahuan, teknologi, dan/atau seni.</br>\r\n3. Menyelenggarakan, mengembangkan, dan membina penelitian dalam rangka menghasilkan pengetahuan empirik, teori, konsep, metodologi, model, produk, yang memperkaya ilmu pengetahuan, teknologi, dan/atau seni.</br>\r\n4. Menyelenggarakan, mengembangkan, dan membina pengabdian kepada masyarakat dengan ilmu pengetahuan, teknologi, dan/atau seni sebagai upaya memberikan sumbangsih demi kemajuan masyarakat.</br>\r\n5. Mengembangkan organisasi dalam meningkatkan kualitas tata kelola yang baik (good university governance) yang mampu beradaptasi dengan perubahan lingkungan strategis.'),
(45, 'Universitas Papua', 'Pada Tahun 2035, Universitas Papua menjadi Perguruan Tinggi Riset yang Mandiri, Bermartabat, Berjiwa Konservasi dan Berkarakter Kewirausahaan.', '1. Menyelenggarakan Pendidikan, Penelitian dan Pengabdian pada masyarakat yang efisien, produktif dan akuntabilitas untuk menghasilkan lulusan yang mandiri berintegritas, daya saing dan mampu menciptakan pasar kerja.</br>\r\n2. Mengembangkan ilmu pengetahuan, teknologi dan seni yang berbasis potensi sumberdaya lokal Papua sebagai keunggulan dalam rangka meningkatkan kesejahteraan masyarakat.</br>\r\n3. Mengembangkan manajemen perguruan tinggi yang berkarakter keilmuan dan kemanusiaan berbasis kewirausahaan dengan taat pada asas efektif, efisien, transparan dan akuntabel.'),
(46, 'Universitas Malikussaleh', 'Menjadi Universitas Unggul di Tingkat Internasional Berbasis Potensi Lokal.', '1. Menyelenggarakan layanan pendidikan yang bermutu secara merata dengan mengikutsertakan segala potensi lokal yang ada di dalam masyarakat.</br>\r\n2. Mengembangkan aktivitas penelitian berbasis potensi lokal melalui penerapan teknologi, industri, pertanian, agribisnis, seni dan budaya, ekonomi bisnis dan syariah, sosial politik, hukum, kesehatan, dan lingkungan hidup yang mampu bersaing di tingkat Internasional.</br>\r\n3. Melaksanakan pengabdian kepada masyarakat secara merata, untuk meningkatkan pengetahuan dan keterampilan masyarakat, menuju taraf kehidupan yang lebih baik.</br>\r\n4. Meningkatkan kapabilitas, akuntabilitas, transparansi, dan otonomi dalam rangka terwujudnya perguruan tinggi yang baik serta mendukung reformasi birokrasi.'),
(47, 'Universitas Negeri Gorontalo', 'Terwujudnya Universitas Negeri Gorontalo Yang Unggul Dan Berdaya Saing Di Kawasan Timur Indonesia.', '1. Mengembangkan pendidikan dan pembelajaran dengan menggunakan digital based learning guna menghasilkan lulusan yang profesional dengan menguasai teknologi.</br>\r\n2. Meningkatkan kompetisi penelitian dan mengembangkan kompetensi peneliti untuk menghasilkan ilmu pengetahuan dan/atau teknologi yang bermanfaat dalam rangka meningkatkan kesejahteraan masyarakat, pembangunan daerahdan nasional.</br>\r\n3. Mengembangkan kegiatan pengabdian kepada masyarakat yang inovatif, menyebarluaskan dan menerapkan hasil penelitian dalam rangka mengurangi angka kemiskinan dan ketimpangan.</br>\r\n4. Meningkatkan daya saing dalam bidang kependidikan dan/atau nonkependidikan.</br>\r\n5. Menyelenggarakan tata kelola yang efektif, efisien, transparan dan akuntabel secara konsisten dan berkelanjutan.'),
(48, 'Universitas Pendidikan Ganesha', 'Menjadikan Bagian Akademik dan Statistik Universitas Pendidikan Ganesha unggul dalam memberikan layanan prima dibidang Akademik dan Statistik yang berlandaskan Tri Hita Karana.', '1. Mengembangkan dan melaksanakan pelayanan prima dibidang akademik dan evaluasi.</br>\r\n2. Mengembangkan dan melaksanakan pelayanan prima dibidang registrasi dan statistik.</br>\r\n3. Mengembangkan dan melaksanakan pelayanan prima dibidang sarana akademik.'),
(49, 'Universitas Bangka Belitung', 'Terwujudnya UBB yang dikenal dan diakui di tingkat internasional sebagai universitas riset yang menghasilkan sumberdaya dan karya-karya unggul di bidang pembangunan yang berkelanjutan didasari keunggulan moral, mental dan intelektual untuk membangun peradaban bangsa.', '1. Menyelenggarakan pendidikan tinggi yang unggul dan berbasis riset dalam pembangunan yang berkelanjutan dengan menintegrasikan keunggulan moral, mental dan intelektual bagi pembangunan sumber daya manusia.</br>\r\n2. Meningkatkan kapasitas dan kualitas riset dan mengembangkan sistem manajemen penelitian dalam mendukung pembangunan yang berkelanjutan sesuai kebutuhan masyarakat pada masa sekarangn dan masa yang akan datang.</br>\r\n3. Meningkatkan kerja sama dengan pemangku kepentingan di tingkat lokal, nasional dan internasional untuk mengembangkan, menigngkatkan promosi program, hasil dan menerapkan ilmu pengethuan dan teknologi dalam pembangunan yang berkelanjutan di masyarakat.</br>\r\n4. Memperkuat tata kelola, akuntabilitas dan pencitraan publik dengan mengembangkan kepranataan menajemen sumberdaya, menciptakan dan memelihara iklim yang mendukung prestasi riset.'),
(50, 'Universitas Borneo Tarakan', 'Menjadi Pusat Penyelenggaraan Pendidikan Tinggi Berbasis Riset Untuk Mendukung Pembangunan Dan Pengembangan Potensi Kawasan Perbatasan Dan Sumber Daya Laut Tropis Yang Berkelanjutan.', '1. Menyelenggarakan pendidikan tinggi berstandar nasional yang berorientasi pada kewirausahaan</br>\r\n2. Mengembangkan riset yang berfokus pada potensi kawasan perbatasan dan sumberdaya laut tropis yang bermanfaat bagi pembangunan nasional</br>\r\n3. Mengembangkan kegiatan pengabdian kepada masyarakat melalui penerapan IPTEKS untuk kesejahteraan masyarakat</br>\r\n4. Mendorong terwujudnya kekuatan moral dalam pembentukan masyarakat madani dan pembangunan berkelanjutan.'),
(51, 'Universitas Musamus Merauke', 'Universitas Musamus pada Tahun 2026 menjadi Perguruan Tinggi Unggulan dalam Pengelolaan Sumber Daya Alam melalui Pemanfaatan Teknologi Informasi secara Mandiri dan Kreatif di Kawasan Regional Timur.', '1. Melaksanakan Tri Darma Perguruan Tinggi yang unggul dalam pemanfaatan Teknologi Informasi serta mendukung Merdeka Belajar Kampus Merdeka (Sivitas Akademika).</br>\r\n2. Menghasilkan sumber daya manusia berkarakter, berkompoten dalam bidang-nya,dan berjiwa entrepreneurship.</br>\r\n3. Menyelenggarakan tata kelola kelembagaan yang profesional, akuntabel, unggul dan berkelanjutan.'),
(52, 'Universitas Maritim Raja Ali Haji', 'Menjadi Pusat Kecemerlangan Pendidikan Tinggi, Riset, Mari Sociopreneurship Dan Tamadun Maritim Di ASEAN.', '1. Menyelenggarakan Pendidikan Bidang Sains dan Teknologi, Social Humaniora dan Budaya berbasis Kemaritiman yang memiliki keunggulan di Tingkat Nasional dan Regional (ASEAN).</br>\r\n2. Mengembangkan Ilmu Pengetahuan dan Teknologi yang Relevan dan Selaras dengan Agenda Kelitbangan Daerah, Riset Nasional dan Regional (ASEAN) yang Bercirikan Kemaritiman.</br>\r\n3. Menyebarluaskan Hasil Riset dan Inovasi dalam Kegiatan Pengabdian Masyarakat Bersama Stakeholder dan Shareholder.</br>\r\n4. Mengembangkan Mari-socio preneur dan ventura untuk meningkatkan kesejahteraan dan kehidupan sosial masyarakat pesisir dan pulau-pulau kecil.'),
(53, 'Universitas Samudra', 'Menjadi Universitas yang Mandiri dan Unggul.', '1. Menyelenggarakan pendidikan yang berkualitas, berkarakter dan berkesinambungan.</br>\r\n2. Menyelenggarakan penelitian dan pengabdian kepada masyarakat yang inovatif untuk mendukung pembangunan daerah, nasional, dan global.</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat sebagai implementasi dan hilirisasi hasil penelitian.</br>\r\n4. Menjalin kerjasama kemitraan yang produktif dan berkelanjutan dengan lembaga pendidikan, pemerintah, dunia usaha, dan industri di tingkat daerah, nasional, dan internasional.</br>\r\n5. Mengembangkan dan mengimplementasikan sistem penjaminan mutu internal secara berkelanjutan.</br>\r\n6. Mengembangkan organisasi dalam meningkatkan kualitas tata kelola yang baik (good university governance).'),
(54, 'Universitas Sulawesi Barat', 'Pada tahun 2040 Unsulbar unggul dalam pengembangan sumber daya manusia, ilmu pengetahuan, dan teknologi berbasis budaya untuk memecahkan masalah lokal, nasional, dan global.', '1. Menyelenggarakan program pendidikan untuk menghasilkan lulusan yang berkualitas, berdedikasi tinggi, dan berakhlak mulia dalam rangka memenuhi tuntutan dan kebutuhan pembangunan.</br>\r\n2. Mengembangkan ilmu pengetahuan dan/atau teknologi berbasis budaya melalui kegiatan penelitian dan pengembangan inovasi teknologi.</br>\r\n3. Memanfaatkan ilmu pengetahuan dan/atau teknologi, dalam mewujudkan kehidupan masyarakat yang sejahtera dan berperadaban.</br>\r\n4. Membangun sistem tata kelola yang bermutu, transparan, dan bertanggung jawab.'),
(55, 'Universitas Sembilanbelas November', 'Pada tahun 2039 menjadi Perguruan Tinggi yang masuk dalam nominasi Perguruan Tinggu Terbaik di kawasan ASEAN.', '1. Memperkuat USN sebagai kampus berbasis teknologi informasi dalam pengelolaan akademik dan manajemen tatakelola organisasi, dibentuk Pusat Penelitian, Informasi dan Teknologi yang baik dan mandiri.</br>\r\n2. Meningkatkan kualitas pelaksanaan pembelajaran, penelitian, dan pengabdian masyarakat khususnya di bidang pertambangan, peternakan, perikanan, dan kelautan.</br>\r\n3. Mengaplikasikan hasil-hasil penelitian secara luas melalui pengabdian kepada masyarakat.</br>\r\n4. Melaksanakan program Pendidikan Vokasi, pendidikan pascasarjana S2/S3, dan Pendidikan Profesi.'),
(56, 'Universitas Tidar', 'Menjadi Universitas Unggul Dalam Bidang Kewirausahaan Berbasis Sumberdaya dan Kearifan Lokal.', '1. Menyelenggarakan pendidikan untuk menghasilkan lulusan yang unggul dalam bidang kewirausahaan berbasis sumber daya dan kearifan lokal.</br>\r\n2. Menyelenggarakan penelitian yang unggul dengan memprioritaskan bidang kewirausahaan berbasis sumber daya dan kearifan lokal.</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat yang unggul dengan memprioritaskan pengembangan kewirausahaan berbasis sumber daya dan kearifan lokal.</br>\r\n4. Mewujudkan tata kelola universitas yang profesional, akuntabel dan transpara'),
(57, 'Universitas Siliwangi', 'Menjadi Perguruan Tinggi Unggul Berwawasan Kebangsaan dan Berkarakter Wirausaha Pada Tahun 2030.', '1. Menyelenggarakan pendidikan tinggi yang berkualitas, berwawasan kebangsaan dan berkarakter wirausaha.</br>\r\n2. Menyelenggarakan penelitian kolaboratif inovatif untuk menghasilkan pengetahuan, teknologi dan seni budaya yang berdaya saing global.</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat sebagai implementasi hasil penelitian dan pemenuhan kebutuhan masyarakat.</br>\r\n4. Meningkatkan tata kelola organisasi yang baik, adaptif, akseleratif, dan berintegritas.</br>\r\n5. Mengembangkan jaringan kerja sama yang produktif, bermanfaat dan berkelanjutan dengan lembaga di tingkat lokal, nasional, dan internasional.'),
(58, 'Universitas Teuku Umar', 'Menjadi sumber inspirasi dan referensi dalam pengembangan ilmu pengetahuan, teknologi dan bisnis disektor industri berbasis agro dan marine (Agro dan Marine Industry) diperingkat regional (2025), nasional (2040), dan international (2060) melalui riset yang inovatif kreatif dan berdaya saing tinggi.', '1. Menyelenggarakan program pengembangan ilmu pengetahuan, teknologi, informasi dan senin budaya yang relevan dengan kebutuhan pembangunan baik regional, nasional dan international.</br>\r\n2. Menyelenggarakan riset yang inovatif dan berdaya saing tinggi untuk menunjang pembangunan dan pengembangan ilmu pengetahuan dan teknologi.</br>\r\n3. Menghasilkan dan menyebarkan hasil-hasil riset yang dapat menjadi referensi dalam pengembangan ilmu pengetahuan dan bisnis.</br>\r\n4. Menghasilkan ilmu pengetahuan dan teknologi yang relevan dengan kebutuhan pasar.</br>\r\n5. Menghasilkan lulusan yang memiliki semangat tinggi dalam berwirausaha (entepreneurship spirit).'),
(59, 'Universitas Pembangunan Nasional \"Veteran\" Jawa Timur', 'Menjadi Universitas Unggul Berkarakter Bela Negara', '1. Menyelenggarakan dan mengembangkan pendidikan berkarakter bela negara</br>\r\n2. Meningkatkan budaya riset dalam pengembangan bidang IPTEK yang bedayaguna untuk kesejahteraan masyarakat</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat berbasis riset dan kearifan lokal</br>\r\n4. Menyelenggarakan tata kelola yang baik dan bersih dalam rangka mencapai akuntabilitas pengelolaan anggaran</br>\r\n5. Mengembangkan kualitas sumber daya manusia unggul dalam sikap dan tata nilai, unjuk kerja, penguasaan pengetahuan, dan manajerial</br>\r\n6. Meningkatkan sistem pengelolaan sarana dan prasarana terpadu</br>\r\n7. Meningkatkan kerjasama institusional dengan stakeholders baik dalam dan luar negeri.'),
(60, 'Universitas Timor', 'Menjadi pusat ilmu pengetahuan, teknologi, humaniora dan seni yang unggul dalam bidang pertanian lahan kering yang mandiri dan bermartabat pada tingkat regional, nasional, dan internasional pada tahun 2025.', '1. Menyelenggarakan pendidikan yang berrkualitas untuk menghasilkan lulusan yang berkualitas dan mandiri;</br>\r\n2. Menyelenggarakan penelitian dan pengabdian yang berkualitas untuk pengembangan ilmu pengetahuan, teknologi, dan/atau seni berbasis pertanian lahan kering serta pembangunan daerah pada tingkat regional, nasional dan internasional;</br>\r\n3. Mengembangkan hubungan kerja sama dengan lembaga pendidikan maupun lembaga non-pendidikan baik di dalam dan luar negeri dalam rangka pengembangan sumber daya manusia.</br>\r\n4. Mengembangkan sistem informasi dan komunikasi seb agai perwujudan kemampuan lembaga dalam peningkatan layanan IPTEK untuk kepentingan masyarakat.</br>\r\n5. Menghasilkan sumber daya mandiri yang peduli pada ling kungan dan berpihak kepada masyarakat kecil.maupun di luar negeri dalam rangka pengembangan sumber daya manusia, kelembagaan, dan tridharma perguruan tinggi; dan</br>\r\n6. Mengembangkan sistem informasi dan komunikasi seb agai perwujudan kemampuan lembaga dalam peningkatan Layanan ilmu pengetahuan dan teknologi untuk kepentingan masyarakat.'),
(61, 'Universitas Pembangunan Nasional \"Veteran\" Jakarta', 'Menjadi Universitas Unggul berkualitas Internasional yang inovatif, berdaya saing dan berindentitas bela negara untuk pembangunan masyarakat Indonesia.', '1. Menyelenggarakan pendidikan bermutu untuk menghasilkan lulusan berdaya saing Internasional yang berindentitas bela negara.</br>\r\n2. Menyelenggarakan penelitian dan pengabdian masyarakat yang inovatif untuk pembangunan masyarakat Indonesia.</br>\r\n3. Mengembangkan iklim akademik yang berlandaskam pada nilai-nilai tradisional universitas.</br>\r\n4. Melaksanakan tata kelola universitas yang baik dengan menerapkan manajemen risiko.</br>\r\n5. Mengembangkan jejaring dan kemitraan dalam dan luar negeri.'),
(62, 'Universitas Pembangunan Nasional \"Veteran\" Yogyakarta', 'Menjadi Universitas Pionir Pembangunan yang Dilandasi Jiwa Bela Negara di Era Global.', '1. Meningkatkan kualitas lulusan yang berdaya saing global dan dilandasi jiwa bela negara melalui pelaksanaan kampus merdeka dalam rangka penguatan relevansi, kuantitas dan kualitas pembelajaran.</br>\r\n2. Meningkatkan produk inovasi melalui peningkatan kualitas luaran penelitian.</br>\r\n3.Meningkatkan kualitas pengabdian kepada masyarakat melalui pemanfaatan hasil penelitian dan sumber daya yang dimiliki.</br>\r\n4. Meningkatkan kualitas kelembagaan melalui peningkatan kualitas kerjasama, reformasi birokrasi dan menjadi PTN PK-BLU.</br>\r\n5. Wewujudkan sikap dan perilaku Bela Negara baik oleh institusi maupun pegawai dan mahasiswa melalui peningkatan pemahaman, kesadaran dan internalisasi nilai-nilai bela Negara dalam pelaksanaan Tri Dharma Perguruan Tinggi.'),
(63, 'Universitas Singaperbangsa Karawang', 'Inovatif, kompetitif, dan unggul yang dijiwai budaya bangsa.', '1. Menyiapkan sumber daya manusia yang profesional dan berakhlak mulia.</br>\r\n2. Menciptakan, menerapkan, dan mengembangkan ilmu pengetahuan, teknologi, dan seni yang berdaya guna dan berhasil guna.</br>\r\n3. Melaksanakan pengabdian pada masyarakat secara aktif untuk meningkatkan kesejahteraan masyarakat.</br>\r\n4. Menciptakan sistem pengelolaan tridharma perguruan tinggi yang akuntabel, transparan, efisien, efektif, dan responsibel.'),
(64, 'Institut Teknologi Bandung', 'Menjadi Perguruan Tinggi yang unggul, bermartabat, mandiri, dan diakui dunia serta memandu perubahan yang mampu meningkatkan kesejahteraan bangsa Indonesia dan dunia.', 'Menciptakan, berbagi dan menerapkan ilmu pengetahuan, teknologi, seni dan kemanusiaan serta menghasilkan sumber daya insani yang unggul untuk menjadikan Indonesia dan dunia lebih baik.'),
(65, 'Institut Teknologi Sepuluh Nopember', 'Menjadi Perguruan Tinggi berkelas dunia yang berkontribusi pada kemandirian bangsa serta menjadi rujukan dalam pendidikan, penelitian, dan pengabdian masyarakat serta pengembangan inovasi terutama yang menunjang industri dan kelautan.', 'Memberikan kontribusi dalam ilmu pengetahuan dan teknologi untuk kesejahteraan masyarakat melalui kegiatan pendidikan, penelitian, pengabdian kepada masyarakat dan manajemen yang berbasis teknologi informasi dan komunikasi.');
INSERT INTO `visimisi_kampus` (`id`, `nama`, `visi`, `misi`) VALUES
(66, 'Institut Pertanian Bogor', 'Menjadi perguruan tinggi berbasis riset dan terdepan dalam inovasi untuk kemandirian bangsa menuju techno-socio enterpreneurial university yang unggul di tingkat global pada bidang pertanian, kelautan, biosains tropika “ (Rencana Strategis IPB 2019-2023).', '1. Menyelenggarakan pendidikan tinggi dengan melakukan penguatan research base university agar menghasilkan lulusan techno-sociopreneur yang unggul, memiliki akhlak mulia yang berlandaskan iman dan takwa kepada Tuhan Yang Maha Esa, nasionalisme tinggi, kompetensi profesional, softskills millennium, jiwa kepemimpinan, berwawasan global dan menjadi trend setter inovasi dan perubahan.</br>\r\n2. Memelopori penelitian unggul dan terdepan dalam IPTEKS yang transformatif untuk terciptanya kualitas kehidupan berkelanjutan, serta inovasi untuk ekonomi rakyat dan industri nasional.</br>\r\n3. Mendalami ilmu-ilmu terkini di bidang pertanian, kelautan dan biosains tropika untuk menjadi penentu kecenderungan ilmu terkini di tingkat nasional dan global.</br>\r\n4. Meningkatkan layanan proaktif yang berkontribusi dan memecahkan persoalan masyarakat dan meningkatkan peran IPB dalam menentukan arah kebijakan nasional.</br>\r\n5. Memperkuat sistem manajemen PT yang mampu menjadi pedoman pengembangan sistem manajemen modern pendidikan tinggi di era 4.0.'),
(67, 'Institut Seni Indonesia Yogyakarta', 'Institut Seni Indonesia Yogyakarta menjadi pelopor perguruan tinggi seni nasional yang unggul, kreatif, dan inovatif berdasar Pancasila.', '1. Menyelenggarakan pendidikan seni yang unggul, kreatif, dan inovatif berdasarkan Pancasila.</br>\r\n2. Menyelenggarakan penelitian dan penciptaan seni yang unggul, kreatif, dan inovatif berdasarkan Pancasila.</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat dalam bidang seni yang unggul, kreatif, dan inovatif berdasarkan Pancasila.</br>\r\n4. Menyelenggarakan kerjasama nasional, regional, dan internasional yang strategis, sinergis, dan berkelanjutan.</br>\r\n5. Menyelenggarakan manajemen yang efektif, efisien, transparan, dan akuntabel (good governance).'),
(68, 'Institut Seni Indonesia Bali', 'Menjadi pusat unggulan seni budaya berbasis kearifan lokal berwawasan universal.', '1. Menyelenggarakan pendidikan tinggi yang berkualitas dengan mengembangkan pluralitas dan multikulturalitas budaya lokal dan nusantara agar memiliki daya saing dalam konstalasi global;</br>\r\n2. Menghasilkan lulusan yang bermoral, kreatif, tangguh, unggul, dan berjiwa kewirausahaan;</br>\r\n3. Mengembangkan penelitian dan pengabdian kepada masyarakat yang mendukung pendidikan dan kemajuan seni, ilmu pengetahuan, dan teknologi;</br>\r\n4. Mengembangkan kerja sama antar lembaga secara berkelanjutan; dan</br>\r\n5. Memantapkan organisasi dalam mencapai kinerja yang optimal untuk mengantisipasi perkembangan lingkungan.'),
(69, 'Institut Seni Indonesia Surakarta', 'Menjadi perguruan tinggi seni berbasis kearifan budaya nusantara yang berkelas dunia dalam sistem tata kelola yang akuntabel dan transparan.', 'Melaksanakan pendidikan, penelitian, dan pengabdian kepada masyarakat dalam rangka pelestarian dan pengembangan seni dan ilmu seni berbasis budaya nusantara yang unggul dan bermanfaat bagi masyarakat.'),
(70, 'Institut Seni Indonesia Padang Panjang', 'Menjadi Perguruan Tinggi Unggul dan Berdaya Saing Globai yang Menghasilkan Ilmuwan dan Entrepreneur Berbasis Seni Budaya tahun 2O44.', '1. Menyelenggarakan pendidikan yang berkualitas, berkarakter, berkesinambungan, dan penerapan merdeka belajar untuk meningkatkan lulusan yang bermutu;</br>\r\n2. Menyelenggarakan penelitian dan pengabdian kepada masyarakat yang bermutu, relevan, berdaya saing sesuai perkembangan ilmu pengetahuan dan teknologi yang terpublikasi secara nasional dan internasional;</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat untuk kesejahteraan masyarakat melalui transfer ilmu pengetahuan dan difusi hasil teknologi;</br>\r\n4. Melaksanakan, meningkatkan, dan mengembangkan kelembagaan;</br>\r\n5. Melaksanakan, meningkatkan, dan mengembangkan kerja sama nasional dan internasional;</br>\r\n6. Menyelenggarakan tata kelola perguruan tinggi yang baik berbasis teknologi informasi;</br>\r\n7. Mewujudkan pusat unggulan seni, budaya, dan karya inovasi;\r\n8. Mewujudkan lulusan berjiwa entrepreneut;</br>\r\n9. Mengoptimalkan kompetensi Dosen dan Tenaga Kependidikan yang profesional; dan</br>\r\n10. Membangun karakter Sivitas Akademika dan Tenaga Kependidikan berdasarkan nilai-nilai Pancasila.'),
(71, 'Institut Seni Budaya Indonesia Bandung', 'Menjadi Institusi Pendidikan Tinggi Seni Budaya yang berjati diri, berkualitas, dan berdaya saing dalam skala lokal, nasional, dan global.', '1. Menyelenggarakan Tridarma Perguruan Tinggi di bidang seni budaya yang memperkokoh karakter budaya bangsa.</br>\r\n2. Memberdayakan seni budaya secara kreatif dan inovatif.</br>\r\n3. Membangun sumber daya manusia unggul dan kompetitif.</br>\r\n4. Menjalin kerja sama seni budaya dalam tingkat lokal dan global.'),
(72, 'Institut Seni Budaya Indonesia Aceh', 'Mewujudkan Lembaga Pendidikan Tinggi Seni dan Budaya yang menghasilkan insan akademis, kreatif, mandiri, berkepribadian, dan berbudaya.', '1. Menyelenggarakan pendidikan yang bermutu di bidang seni dan budaya.</br>\r\n2. Membangun kehidupan akademik yang kondusif dan mandiri melalui sistem pendidikan yang bermutu, transparan, demokratis, dan berjiwa wirausaha.</br>\r\n3. Menciptakan civitas akademika yang berkarakter, berdaya saing, dan berkompetensi dalam penguasaan ilmu, pengetahuan, dan keterampilan seni dan budaya</br>\r\n4. Membina penelitian yang bertumpu pada pengembangan ilmu pengetahuan dan pengabdian yang berorientasi pada kepentingan dan kemajuan bangsa dan negara.</br>\r\n5. Meningkatkan peran ISBI Aceh dalam pengembangan kreatifitas seni dan budaya di tingkat lokal, nasional dan internasional.</br>\r\n6. Membangun kerja sama antar lembaga dan unsur lain yang relevan.'),
(73, 'Institut Seni Budaya Indonesia Tanah Papua', 'Pada tahun 2042 menjadi pusat unggulan seni budaya yang berbasis kearifan lokal guna memperkaya nilai-nilai kemanusiaan.', '1. Menyelenggarakan pendidikan tinggi dengan mengembangkan potensi dan pluralitas seni budaya lokal dan nasional untuk membangun jati diri masyarakat agar memiliki daya saing global;</br>\r\n2. Menyelenggarakan penelitian dan pengabdian kepada masyarakat guna mendukung pendidikan dan pegembangan seni budaya;</br>\r\n3. Melaksanakan pengabdian kepada masyarakat dalam rangka penerapan dan pengembangan keilmuan dalam bidang seni budaya; dan</br>\r\n4. Mengembangkan kerja sama antar lembaga secara berkelanjutan.'),
(74, 'Institut Teknologi Kalimantan', 'Menjadi perguruan tinggi yang unggul dan berperan aktif dalam pembangunan Nasional melalui pemberdayaan potensi daerah Kalimantan pada tahun 2025\r\n', '1. Menyelenggarakan tridharma perguruan tinggi yang bermutu guna mengoptimalkan potensi daerah Kalimantan;</br>\r\n2. Menghasilkan lulusan yang unggul, berkualitas, dan berbudi luhur serta dapat berperan aktif dalam pembangunan nasional; dan</br>\r\n3. Membangun kerja sama dengan pemangku kepentingan untuk memberdayakan potensi daerah Kalimantan.'),
(75, 'Institut Teknologi Sumatera', 'Menjadi perguruan tinggi yang unggul, bermartabat, mandiri, dan diakui dunia, serta berkontribusi dalam perubahan yang mampu meningkatkan kesejahteraan bangsa Indonesia dan dunia dengan memberdayakan potensi yang ada di wilayah Sumatera dan sekitarnya.', 'Berperan aktif pada pemberdayaan potensi yang ada di wilayah Sumatera khususnya, dan Indonesia serta dunia melalui keunggulan dalam pendidikan, penelitian, dan pengabdian pada masyarakat dalam bidang ilmu pengetahuan, teknologi, seni, dan ilmu kemanusiaan.'),
(76, 'Institut Teknologi Bacharuddin Jusuf Habibie', 'Menjadi Institut yang unggul, memiliki daya saing, berstandar internasional yang menjunjung tinggi martabat kemanusiaan, berwawasan lingkungan dan berbasis enterpreneurship.', '1. Menghasilkan lulusan yang profesional, berjiwa wirausaha, berkarakter dan berstandar Internasioanal</br>\r\n2. Menghasilkan karya nyata bidang ilmu pengetahuan yang inovatif dan berguna bagi masyarakat;</br>\r\n3. Menyelengarakan pendidikan teknologi yang berkualitas;</br>\r\n4. Terciptanya manajemen yang handal untuk tatakelola transparan dan terpercaya;</br>\r\n5. Melakukan Pembinaan sumberdaya manusia yang berkesinambungan dalam menunjang pengembangan profesionalisme.'),
(77, 'Politeknik Manufaktur Bandung', 'Menjadi institusi terdepan dalam pendidikan,pengembangan dan penerapan teknologi manufaktur yang diakui dunia.', 'Menyiapkan sumber daya manusia yang menguasai teknologi manufaktur, inovatif, tanggap terhadap tantangan lokal, serta mampu bersaing dalam pasar global dengan membangun dan mengembangkan pendidikan, pelatihan, rancang bangun dan produksi.'),
(78, 'Politeknik Negeri Jakarta', 'Menjadi Politeknik Unggul Bertaraf Internasional Untuk Mendukung Daya Saing Bangsa.', '1. Menyelenggarakan Pendidikan Vokasi yang berbasis ilmu pengetahuan, teknologi, rekayasa dan seni yang menghasilkan lulusan berkarakter dan bertakwa kepada Tuhan Yang Maha Esa.</br>\r\n2. Mengembangkan penelitian, peningkatan, dan penerapan ilmu pengetahuan, teknologi, rekayasa dan seni serta produk inovasi berkualitas guna meningkatkan daya saing bangsa.</br>\r\n3. Mengembangkan institusi yang efsien, efektif dan akuntabel berbasis teknologi informasi dan komunikasi.'),
(79, 'Politeknik Negeri Medan', 'Menjadi institusi Pendidikan vokasi yang profesional dan unggul', '1. Memajukan Pendidikan untuk menghasilkan tenaga vokasi yang profesional</br>\r\n2. Melaksanakan penelitian di bidang ilmu terapan untuk pengembangan ilmu pengetahuan dan teknologi</br>\r\n3. Menerapkan ilmu pengetahuan dan teknologi untuk memajukan kewirausahaan, meningkatkan kesejahteraan masyarakat bangsa dan Negara.</br>\r\n4. Menyelenggarakan tata kelola perguruan tinggi dengan prinsip efisien, efektif, akuntabel dan transparan'),
(80, 'Politeknik Negeri Bandung', 'Menjadi institusi yang unggul dan terdepan dalam pendidikan vokasi yang inovatif dan adaptif terhadap perkembangan ilmu pengetahuan dan teknologi terapan.', '1. Menyelenggarakan pendidikan untuk menghasilkan lulusan yang kompeten, memiliki semangat terus berkembang, bermoral, berjiwa kewirausahaan dan berwawasan lingkungan;</br>\r\n2. Melaksanakan penelitian terapan dan menyebarluaskan hasilnya untuk mengembangkan ilmu pengetahuan dan teknologi;</br>\r\n3. Melaksanakan kegiatan pengabdian kepada masyarakat melalui pemanfaatan ilmu pengetahuan dan teknologi untuk mendukung peningkatan mutu kehidupan; dan</br>\r\n4. Menyelenggarakan dan mengembangkan tata kelola yang efisien, akuntabel, trasnparan, dan berkeadilan untuk mendukung tercapainya visi dan tujuan Polban.'),
(81, 'Politeknik Negeri Semarang', 'Polines Menjadi Perguruan Tinggi Terapan yang diakui scara nasional dan internasional, mampu bersaing, akuntabel, berkarakter, dan beretika dalam bidang teknologi dan bisnis.', '1. Melaksanakan pendidikan tinggi vokasi bidang teknologi dan bisnis terapan yang unggul, berkarakter dan beretika</br>\r\n2. Melaksanakan dan mengembangkan penelitian terapan dan pengabdian kepada masyarakat dalam bidang teknologi dan bisnis</br>\r\n3. Meningkatkan kualitas manajemen institusi, melalui perbaikan berkelanjutan berdasarkan prinsip tata kelola yang baik</br>\r\n4. Menghasilkan sumber daya manusia yang profesional, berkarakter dan beretika</br>\r\n5. Mengembangkan kerjasama dengan pemangku kepentingan (stakeholders)'),
(82, 'Politeknik Negeri Sriwijaya', 'Menjadi lembaga pendidikan vokasi yang unggul dan terkemuka.', '1. Meningkatkan penyelenggaraan pendidikan dalam bidang rekayasa dan non rekayasa yang berkualitas dengan berbasis pada sistem penjaminan mutu;</br>\r\n2. Mengembangkan, menyebarluaskan, dan menerapkan ilmu pengetahuan, teknologi, dan seni serta hasil penelitian terapan bermutu untuk dimanfaatkan dalam kegiatan produktif dan peningkatan kualitas kehidupan masyarakat;</br>\r\n3. Mengembangkan organisasi dan meningkatkan mutu pengelolaan sumber daya Polsri untuk mewujudkan kinerja secara efektif, efisien, dan berkelanjutan;</br>\r\n4. Meningkatkan kemitraan dengan pihak lain yang saling menguntungkan dalam rangka peningkatan kualitas penyelenggaraan Tri Dharma Perguruan Tinggi.'),
(83, 'Politeknik Negeri Lampung', 'Menjadi politeknik yang bermutu, inovatif, dan unggul dalam ilmu pengetahuan dan teknologi terapan.', '1. Mewujudkan Pendidikan Tinggi Vokasi yang berorientasi pada akhlak mulia, terampil, disiplin, mandiri, dan kompetitif;</br>\r\n2. Mewujudkan kajian keilmuan dalam penelitian terapan dan pengabdian kepada masyarakat melalui transfer ilmu pengetahuan dan teknologi terapan;</br>\r\n3. Mewujudkan budaya akademik, organisasi, dan kerja yang berkarakter dan beretika;</br>\r\n4. Mewujudkan kerjasama kelembagaan dengan stakeholder secara berkelanjutan.'),
(84, 'Politeknik Negeri Ambon', 'Menjadikan Politeknik Negeri Ambon Sebagai Lembaga Pendidikan Tinggi Vokasi yang Profesional, Unggul dan Berintegritas Berorientasi Kepulauan.', '1. Menyelenggarakan sistem pendidikan tinggi vokasi yg menghasilkan lulusan berkualitas, inovatif dan berdaya saing.</br>\r\n2. Menyelenggarakan penelitian terapan dan pengabdian kepada masyarakat yg bermanfaat bagi pengembangan IPTEKS sebagai bentuk pemberdayaan untuk meningkatkan kesejahteraan pada masyarakat kepulauan</br>\r\n3. Menyelenggarakan sistem pengelolaan pendidikan yang didasarkan pada prinsip-prinsip tata pamong dan tata kelola'),
(85, 'Politeknik Negeri Padang', 'Pada tahun 2025 Menjadi institusi pendidikan vokasional terbaik di Asia Tenggara, bermartabat, dan berwawasan internasional.', '1. Menyelenggarakan pendidikan vokasional yang sesuai dengan perkembangan ilmu pengetahuan dan teknologi yang berwawasan internasioanal;</br>\r\n2. Menyelenggarakan penelitian yang inovatif dan adaptif untuk pengembangan ilmu pengetahuan dan teknologi;</br>\r\n3. Menerapkan ilmu pengetahuan dan teknologi dalam rangka memecahkan masalah dan meningkatkan taraf hidup masyarakat;</br>\r\n4. Menjalin kerjasama yang produktif dan berkelanjutan dengan lembaga pendidikan, pemerintah, dan dunia usaha ditingkat nasional dan internasional.'),
(86, 'Politeknik Negeri Bali', 'Menjadi Lembaga Pendidikan Tinggi Vokasi Terdepan Penghasil Lulusan Profesional Berdaya Saing Internasional Pada Tahun 2025.', '1. Menyelenggarakan pendidikan vokasi yang dapat diakses secara merata dan merata bagi masyarakat</br>\r\n2. Menyelenggarakan pendidikan vokasi yang berkarakter bangsa dengan standar mutu nasional dan regional di Asia-Pasifik</br>\r\n3. Menyelenggarakan penelitian bertaraf internasional di bidang ilmu dan teknologi terapan</br>\r\n4. Menyelenggarakan pengabdian kepada masyarakat berbasis penerapan ilmu pengetahuan dan teknologi</br>\r\n5. Menyelenggarakan kerjasama di kawasan ASPAC</br>\r\n6. Mengembangkan sistem tata kelola yang inovatif, transparan, dan akuntabel yang didukung oleh sumber daya berstandar internasional</br>\r\n7. Membangun keunggulan institusi berorientasi pariwisata'),
(87, 'Politeknik Negeri Pontianak', 'Pada tahun 2045 Politeknik Negeri Pontianak menjadi lembaga pendidikan tinggi vokasi yang berdaya saing di tingkat nasional dan internasional.', '1. Menyelenggarakan pendidikan tinggi vokasi yang didukung sumber daya berstandar nasional dan internasional;</br>\r\n2. Menyelenggarakan penelitian terapan yang kreatif dan inovatif yang hasilnya dapat dimanfaatkan langsung oleh industri, dunia usaha, dan dunia kerja (IDUKA), dan menyelenggarakan pengabdian kepada masyarakat untuk pemberdayaan dan kesejahteraan masyarakat.</br>\r\n3. Menjalin dan mengembangkan kerjasama dengan berbagai kelembagaan, institusi pemerintahan dan swasta baik dalam maupun luar negeri.</br>\r\n4. Mewujudkan tata kelola lembaga secara transparan dan akuntabel melalui pembangunan Zona Integritas menuju Wilayah Bebas dari Korupsi (WBK) dan Wilayah Birokrasi Bersih dan Melayani (WBBM).'),
(88, 'Politeknik Negeri Ujung Pandang', 'Menjadi Perguruan Tinggi Vokasi yang Unggul di Indonesia dan Berdaya Saing Global', '1. Menghasilkan lulusan kompetitif, berjiwa kewirausahaan dan berakhlak mulia.</br>\r\n2. Menghasilkan penelitian dan pengabdian pada masyarakat yang berkontribusi signifikan terhadap kebijakan pemerintah, pengembangan industri dan peningkatan kesejahteraan masyarakat.</br>\r\n3. Mewujudkan tata pamong dan Kelola yang baik dan produktif (good and corporate govermance) melalui penerapan akhlak mulia'),
(89, 'Politeknik Negeri Manado', 'Menjadikan politeknik negeri manado sebagai perguruan tinggi vokasional unggul dan berstandar internasional', '1. Meningkatkan dan memperluas akses dan layanan prima bagi masyarakat untuk mendapatkan pendidikan bermutu;</br>\r\n2. Meningkatkan mutu, relevansi dan daya saing semua program studi;</br>\r\n3. Menciptakan lulusan berkualitas secara komprehensif meliputi aspek knowledge, skill dan attitude;</br>\r\n4. Menciptakan dan mengembangkan manajemen institusi berdasarkan prinsip good governance secara berkelanjutan;</br>\r\n5. Meningkatan kualitas hasil penelitian berbasis teknologi terapan;</br>\r\n6. Membangun kemitraan yang kokoh dengan pemerintah pusat dan daerah sesuai dengan amanah Masterplan Percepatan Dan Perluasan Pembangunan Ekonomi Indonesia (MP3EI);</br>\r\n7. Membangun kolaborasi dengan pihak industri dalam menghasilkan karya produktif dan inovatif yang berdampak peningkatan kualitas hidup masyarakat;</br>\r\n8. Membangun kerjasama pendidikan dan penelitian dengan institusi/ perguruan tinggi nasional dan internasional.'),
(90, 'Politeknik Perkapalan Negeri Surabaya', 'Menjadi politeknik unggul bereputasi global', '1. Melaksanakan program pendidikan vokasi dan penelitian terapan di bidang teknologi kemaritiman, teknologi penunjang kemaritiman, serta teknik keselamatan & kesehatan kerja (professionalism-sustainability);</br>\r\n2. Berperan dalam kegiatan kemasyarakatan secara aktif dan produktif, untuk mengembangkan teknologi kemaritiman, teknologi penunjang kemaritiman, serta teknik keselamatan dan kesehatan kerja (good governance-professionalism);</br>\r\n3. Membangun masyarakat akademis berkualitas yang mampu berkompetisi secara global (sustainability-professionalism);</br>\r\n4. Membentuk jejaring kerja dengan sektor industri kemaritiman serta berbagai institusi terkait untuk merealisasikan sistem pendidikan yang komprehensif (good governance-sustainability).</br>\r\n5. Mengintegrasikan pengembangan kepribadian dalam proses pembelajaran dan atau kegiatan ekstra kurikuler untuk meningkatkan keimanan dan ketakwaan pada Tuhan Yang Maha Esa serta kemuliaan akhlak (moral value).'),
(91, 'Politeknik Negeri Banjarmasin', 'Menjadi Lembaga Pendidikan Tinggi Vokasi yang Berkualitas dan Unggul Dalam Sains Terapan.', '1. Menyelenggarakan pendidikan vokasi yang berkualitas dengan di dukung oleh suasana akademik yang kondusif bagi peningkatan mutu sumber daya manusia</br>\r\n2. Melaksanakan penelitian dan pengabdian kepada masyarakat yang memberi kontribusi bagi ilmu pengetahuan dan teknologi serta masyarakat</br>\r\n3. Melaksanakan tata kelola dan tata pamong yang menjamin peningkatan kualitas perguruan tinggi secara berkelanjutan'),
(92, 'Politeknik Negeri Lhokseumawe', 'Politeknik Negeri Lhokseumawe sebagai Institusi Pendidikan Tinggi Vokasi yang Mandiri dan Unggul di Tingkat Global pada Tahun 2024.', '1. Menyelenggarakan Pendidikan Vokasi dengan penguatan keterampilan;</br>\r\n2. Mengembangkan penelitian dan pengabdian kepada masyarakat berorientasi teknologi inovatif;</br>\r\n3. Meningkatkan peran serta PNL dalam merespon isu global dengan memperhatikan kearifan lokal; dan</br>\r\n4. Menyelenggarakan sistem pengelolaan tridharma perguruan tinggi dengan prinsip tata kelola yang baik.'),
(93, 'Politeknik Negeri Kupang', 'Terwujudnya pendidikan tinggi vokasional berwawasan global, inovatif dan berdaya saing dalam bidang rekayasa, tataniaga dan pariwisata.', 'Mewujudkan Pendidikan Tinggi Vokasi yang berkualitas dan berstandar industri yang berkelanjutan dengan dukungan infrastruktur dan teknologi.'),
(94, 'Politeknik Elektronika Negeri Surabaya', 'Menjadi pusat unggulan pendidikan teknologi rekayasa di bidang emerging technology dalam skala nasional maupun internasional', '1. Menyelenggarakan pendidikan dengan menyediakan lingkungan dan suasana akademik yang berkualitas untuk menghasilkan lulusan yang profesional, berpikiran terbuka, kreatif dan berjiwa pemimpin, yang siap bersaing di era global.</br>\r\n2. Sebagai sumber daya politeknik nasional, berperan aktif dalam pengembangan dan peningkatan sistem pendidikan politeknik di Indonesia.</br>\r\n3. Melaksanakan penelitian yang berorientasi penemuan, pengembangan, kombinasi, atau integrasi dari beberapa teknologi yang sudah ada sebelumnya, menjadi teknologi baru yang membawa kemaslahatan masyarakat.</br>\r\n4. Membangun dan mengimplementasikan nilai-nilai etika moral akademis dan sosial masyarakat.'),
(95, 'Politeknik Negeri Jember', 'Mendukung Visi Dan Misi Kementerian Pendidikan Dan Kebudayaan Dengan Mewujudkan Pendidikan Tinggi Vokasi Yang Unggul Dan Berdaya Saing Dibidang Teknologi Terapan Yang Menghasilkan Lulusan Berkarakter.', '1. Meningkatkan Pendidikan Terapan Yang Inovatif Dan Berdaya Saing;</br>\r\n2. Meningkatkan Penelitian Terapan, Pengabdian Kepada Masyarakat Dan Kewirausahaan Untuk Menghasilkan Nilai Tambah Produk Inovasi</br>\r\n3. Mewujudkan Tata Kelola Polije Yang Lebih Baik Dalam Rangka Reformasi Birokrasi (Good Polije Governance);</br>\r\n4. Mengembangkan Kerjasama Tingkat Nasional Maupun Internasional.'),
(96, 'Politeknik Pertanian Negeri Pangkajene Kepulauan', 'Menjadi Perguruan Tinggi Vokasi Nasional yang Inovatif, Unggul dan Berbudaya menuju Perguruan Tinggi Kelas Dunia pada Tahun 2030.', '1. Menyelenggarakan pendidikan vokasi untuk menghasilkan lulusan yang kompeten, berkarakter jujur, cerdas, peduli dan tangguh, memiliki etos kerja, serta mampu berwirausaha mandiri.</br>\r\n2. Melaksanakan penelitian dan mendesiminasi hasil-hasilnya untuk mengembangkan Ilmu Pengetahuan, Teknologi dan Seni (IPTEKS) terapan.</br>\r\n3. Melaksanakan kegiatan pengabdian kepada masyarakat melalui pemanfaatan IPTEKS terapan untuk mendukung peningkatan kesejahteraan.</br>\r\n4. Membangun kerjasama dalam dan luar negeri.'),
(97, 'Politeknik Pertanian Negeri Kupang', 'Politeknik Pertanian yang bermutu dan berdaya saing dalam bidang pertanian semi ringkai', '1. Meningkatkan kualitas dan kuantitas pelaksanaan Tri Dharma Perguruan Tinggi yang memenuhi standar.</br>\r\n2. Meningkatkan mutu tata kelola kelembagaan yang responsif, partisipatif, transparan dan akuntabel.'),
(98, 'Politeknik Perikanan Negeri Tual', '1. Unggul. Kata unggul mengandung pengertian atau tafsir secara terminologi “yang terbaik” dalam penyelenggaraan tridharma dan tata kelola baik kegiatan pendidikan, riset maupun hilirisasinya. Keunggulan dalam bidang pendidikan mempunyai target akreditasi unggul. Keunggulan mutu lulusan, pendidik dan tenaga kependidikan yang mempunyai kualitas baik dan terukur sesuai standar mutu pendidikan. Keunggulan dalam bidang penelitian dan pengabdian mampu berkolaborasi secara global untuk meningkatkan kesejahteraan masyarakat dan income bagi negara. Keunggulan dalam tatakelola, dimana pengelolaan lembaga sudah baik dan menjadi tujuan masyarakat serta rujukan perguruan tinggi vokasi lainnya.</br>\r\n2. Dalam Bidang Perikanan dan Kelautan. Keunggulan tersebut dibatasi pada bidang perikanan dan kelautan.</br>\r\n3. Tahun 2035. Mengandung pengertian bahwa penyelenggaraan Polikant dalam jangka waktu 30 tahun (dimulai dari 2005 saat penegerian) akan menjadi unggul secara nasional.', '1. Menyelenggarakan pendidikan berkualitas dan pembelajaran vokasional berbasis industri dan kewirausahaan dengan mengoptimalkan pemanfaatan sumberdaya perairan dan iptek.</br>\r\n2. Menyelenggarakan penelitian terapan dalam ruang lingkup perikanan dan kelautan secara luas yang berorientasi bagi pengembangan ilmu dan kepentingan masyarakat.</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat yang berorientasi pada hilirisasi penelitian dan kepakaran untuk kepentingan institusi dan masyarakat.</br>\r\n4. Menyelenggarakan tata kelola institusi yang otonom, akuntabel, dan transparan yang menjamin peningkatan kualitas pelayanan secara berkelanjutan.'),
(99, 'Politeknik Negeri Malang', 'Visi Polinema adalah menjadi lembaga pendidikan vokasi dalam jaringan pendidikan global, dengan reputasi di bidang ilmu pengetahuan dan teknologi terapan.', '1. Membentuk suasana akademik yang kondusif dalam rangka peningkatan mutu proses pembelajaran dan sumber daya manusia, yang mendorong pola pembelajaran seumur hidup, dan tumbuhnya jiwa kewirausahaan;</br>\r\n2. mengembangkan pendidikan vokasi secara berkelanjutan melalui peningkatan kualitas pendidikan dan pengajaran, penelitian dan pengabdian kepada masyarakat, serta kerjasama dengan industri/lembaga pemerintah maupun swasta dari dalam negeri dan luar negeri; dan</br>\r\n3. mengembangkan etos kerja dan sistem informasi manajemen yang berorientasi pada otonomi perguruan tinggi.'),
(100, 'Politeknik Pertanian Negeri Samarinda', 'Menjadi institusi pendidikan tinggi vokasi yang unggul secara komparatif dan kompetitif bertaraf Nasional dan Internasional.', '1. Menghasilkan lulusan yang bermoral, tangguh, terampil, unggul, dan berjiwa wirausaha.</br>\r\n2. Mendorong kemajuan penelitian terapan yang menopang pendidikan dan kemajuan ilmu, teknologi bidang pertanian.</br>\r\n3. Meningkatkan pengabdian kepada masyarakat atas dasar tanggung jawab sosial.</br>\r\n4. Menjalin kerjasama secara berkelanjutan dengan lembaga pendidikan, lembaga penelitian terapan, pemerintah, dunia usaha, dan masyarakat.</br>\r\n5. Mengembangkan organisasi POLTANESA yang sesuai dengan tuntutan zaman serta meningkatkan manajemen yang transparan dan berkualitas secara berkelanjutan.'),
(101, 'Politeknik Pertanian Negeri Payakumbuh', 'Menjadi Perguruan Tinggi Vokasional Bidang PertanianYang Berdaya Saing Internasional Pada Tahun 2040 Serta Mendukung Pembangunan Pertanian Berkelanjutan', '1. Menyelenggarakan dan mengembangkan pendidikan vokasi bidang pertanian yang berkualitas, inovatif, dan berdaya saing internasional sesuai kebutuhan industri, lembaga pemerintah, dan masyarakat;</br>\r\n2. Menyelenggarakan penelitian dan pengabdian masyarakat yang bermanfaat bagi pengembangan ilmu pengetahuan dan teknologi serta kesejahteraan masyarakat;</br>\r\n3. Menyelenggarakan dan mengembangkan tata kelola pendidikan yang efisien, akuntabel, transparan dan berkeadilan;</br>\r\n4. Membangun suasana akademik yang kondusif untuk meningkatkan mutu sumber daya manusia yang berkarakter, kreatif, inovatif dan berjiwa wirausaha.'),
(102, 'Politeknik Negeri Samarinda', 'Menjadi Perguruan Tinggi Vokasi yang Unggul di bidang Rekayasa dan Tata Niaga pada tingkat nasional.', '1. Menyelenggarakan pendidikan vokasi yang bertumpu pada peningkatan kualitas, perluasan akses dan lulusan berdaya saing tinggi.</br>\r\n2. Menyelenggarakan sistem tata kelola yang sehat, transparan, berkualitas, dan akuntabel sebagai wujud penyelenggaraan organisasi yang sehat.</br>\r\n3. Menyelenggarakan pengembangan dan peningkatan kualitas hasil karya intelektual yang aplikatif melalui kegiatan dan pengabdian pada masyarakat.</br>\r\n4. Menyelenggarakan jaringan kerja sama (networking) dan pencitraan publik.'),
(103, 'Politeknik Negeri Media Kreatif', 'Menjadi lembaga pendidikan tinggi vokasi terkemuka dan unggul di bidang industri kreatif pada tahun 2030 di Asia Tenggara.', '1. Menyelenggarakan program pendidikan vokasi di bidang industri kreatif guna meningkatkan pengetahuan, keterampilan, dan kemampuan penerapannya;</br>\r\n2. Membangun dan mengembangkan sumber daya manusia yang kreatif, inovatif, kompetitif, dan berakhlak mulia serta berwawasan kebangsaan;</br>\r\n3. Membentuk program-program Pendidikan Vokasi yang relevan dengan bidang industri kreatif yang berbasis kompetensi produksi dan kompetensi kewirausahaan;</br>\r\n4. Mengembangkan, menerapkan, dan menyebarluaskan teknologi di bidang industri kreatif yang berbasis pada kearifan lokal dan kebutuhan masyarakat serta dunia usaha dan industri; dan</br>\r\n5. Menyelenggarakan dan mengembangkan tata kelola pendidikan yang efisien, akuntabel, transparan, dan berkeadilan.'),
(104, 'Politeknik Manufaktur Negeri Bangka Belitung', 'Terwujudnya politeknik yang bermutu dengan kemampuan ilmu pengetahuan terapan, teknologi, dan inovasi untuk mendukung daya saing bangsa.', '1. Meningkatkan mutu, relevansi dan akses pendidikan untuk menghasilkan sumber daya manusia yang berkualitas;</br>\r\n2. Meningkatkan kemampuan penelitian dasar dan terapan untuk menghasilkan nilai tambah produk inovasi; dan</br>\r\n3. Meningkatkan kegiatan pengabdian kepada masyarakat dengan memanfaatkan ilmu pengetahuan terapan, teknologi, dan inovasi.'),
(105, 'Politeknik Negeri Batam', 'Menjadi politeknik generasi baru yang bermutu, adaptif, inovatif, dan bermitra erat dengan industri dan masyarakat untuk mendukung Indonesia Maju dan Sejahtera 2045.', 'Aktif dalam proses kreasi, penyebaran dan penerapan sains dan teknologi melalui layanan pendidikan tinggi vokasi dan penelitian terapan yang bermutu, terbuka, relevan, dan berkolaborasi erat dengan masyarakat dan industri dengan penerapan tata kelola institusi yang baik untuk kehidupan bangsa yang lebih baik.'),
(106, 'Politeknik Negeri Nusa Utara', 'Menjadi Politeknik Modern yang berwawasan Kebaharian, yang Mandiri, Unggul dan Berdaya saing.', '1. Menghasilkan lulusan yang bertaqwa kepada Tuhan Yang Maha Esa, berakhlak, berbudaya, bersemangat tinggi, tanggap, berkinerja tinggi, mampu menerapkan ilmu pengetahuan, teknologi, dan seni di daerah/lingkungan laut dan pulau-pulau kecil, mampu mengembangkan kemampuan diri, serta dapat berperan dalam proses produksi dan perlindungan sumberdaya.</br>\r\n2. Menghasilkan ilmu pengetahuan dan teknologi baru serta dapat memutahirkan kemampuan untuk menerapkan ilmu pengetahuan, teknologi dan seni, untuk kemajuan dan kesejahteraan masyarakat.</br>\r\n3. Menyebarkan hasil-hasil penelitian terapan, kaji-tindak maupun paket teknologi tepat guna untuk dimanfaatkan dalam kegiatan produksi bagi peningkatan taraf hidup masyarakat.'),
(107, 'Politeknik Negeri Bengkalis', 'Menjadi perguruan tinggi vokasi terkemuka berstandar nasional dan internasional.', '1. Melaksanakan pengembangan kemampuan intelektual, keterampilan dibidangnya, keseimbangan emosi dan penghayatan spiritual melalui proses belajar mengajar yang berkualitas.</br>\r\n2. Menghasilkan lulusan yang kompeten, berkarakter, berdaya saing, berjiwa kewirausahaan dan berwawasan lingkungan.</br>\r\n3. Melaksanakan penelitian dalam rangka pengembangan iptek dan menyebarluaskan hasil-hasilnya.</br>\r\n4. Melaksanakan pengabdian kepada masyarakat melalui pemanfaatan iptek guna mendukung peningkatan mutu kehidupan.</br>\r\n5. Membudayakan kewirausahaan dan kerjasama yang berkelanjutan dengan institusi dalam dan luar negeri.'),
(108, 'Politeknik Negeri Balikpapan', 'Menjadi institusi pendidikan tinggi vokasi yang berkarakter, unggul, dan berdaya saing global.', '1. Menyelenggarakan dan mengembangkan pendidikan tinggi vokasi yang bermutu, relevan, dan berdaya saing tinggi melalui pelaksanaan pendidikan, penelitian dan pengabdian kepada masyarakat, yang didukung dengan kurikulum dan sumber daya pendidikan yang sesuai dengan standar yang berlaku;</br>\r\n2. Menyelenggarakan manajemen kelembagaan yang efisien, produktif, akuntabel, dan transparan serta berkeadilan untuk menjamin terselenggaranya pelayanan prima dan meningkatnya kepercayaan publik;</br>\r\n3. Mengembangkan dan menghasilkan karya dan produk intelektual yang inovatif.'),
(109, 'Politeknik Negeri Madura', 'Menjadi politeknik yang unggul di bidang teknologi kemaritiman dan berdaya saing internasional', '1. Menyelenggarakan dan mengembangkan pendidikan vokasi di bidang teknologi kemaritiman yang berkualitas, inovasi, dan berdaya saing internasional;</br>\r\n2. Menyelenggarakan dan mengembangkan penelitian yang berrmanfaat bagi pengembangan ilmu pengetahuan dan teknologi;</br>\r\n3. Menyelenggarakan pengabdian masyarakat untuk meningkatkan kesejahteraan masyarakat;</br>\r\n4. Menyelenggarakan system pengelolaan tridharma perguruan tinggi dengan prinsip tatakelola yang baik;</br>\r\n5. Membentuk suasana akademik yang kondusif untuk meningkatkan mutu sumber daya manusia dan proses pembelajaran yang mendorong pola pembelajaran seumur hidup dan tumbuhnya jiwa kewirausahaan;</br>\r\n6. Mengembangkan sistem informasi yang menunjang penyelenggaraan tridharma perguruan tinggi dan tata kelola Poltera.'),
(110, 'Politeknik Maritim Negeri Indonesia', 'Menjadi perguruan tinggi negeri vokasi maritim terkemuka di Indonesia. ', '1.Menghasilkan lulusan yang kompeten di bidang maritim.</br>\r\n2.Mendukung pembangunan ekonomi maritim nasional.</br>\r\n3.Berkontribusi pada kemajuan bangsa di bidang kelautan. '),
(111, 'Politeknik Negeri Banyuwangi', 'Menjadi Lembaga Pendidikan Tinggi vokasional yang bermutu, berkemampuan ilmu pengetahuan dan teknologi, inovatif, dan berdaya saing.', '1. Menyelenggarakan pendidikan yang bermutu sesuai standar nasional pendidikan tinggi untuk menghasilkan lulusan yang kompeten dan profesional</br>\r\n2. Melaksanakan penelitian terapan dan pengabdian kepada masyarakat dalam rangka meningkatkan kualitas Sivitas Akademika sesuai dengan permasalahan industri dan masyarakat</br>\r\n3. Meningkatkan akses, relevansi, kemampuan ilmu pengetahuan dan teknologi dan invoasi untuk sumber daya manusia yang berkualitas.'),
(112, 'Politeknik Negeri Madiun', 'Menjadi Pendidikan Tinggi Vokasi yang Berkualitas, Berbasis IPTEK, Inovasi dan Berdaya Saing Nasional', '1. Meningkatkan akses dalam penyelenggaraan Pendidikan Vokasi yang relevan, inovatif, dan berkualitas untuk menghasilkan lulusan yang berdaya saing nasional;\r\n2. Meningkatkan kapasitas penelitian terapan dan pengabdian kepada masyarakat yang bermanfaat bagi ilmu pengetahuan dan teknologi dan kesejahteraan masyarakat;\r\n3. Meningkatkan penguatan kerja sama dalam mendukung keberlanjutan pemanfaatan sumber daya manusia terampil;\r\n4. Mewujudkan tata kelola perguruan tinggi bermutu melalui perbaikan berkelanjutan.'),
(113, 'Politeknik Negeri Fakfak', 'Menjadi Perguruan Tinggi Vokasi yang unggul dan berdaya saing di kawasan Indonesia Timur pada Tahun 2030', '1. Menyelenggarakan Pendidikan Vokasi yang unggul di Kawasan Indonesia Timur;</br>\r\n2. Menyelenggarakan penelitian terapan dan pengabdian yang berbasis kemitraan dengan industri dan masyarakat;</br>\r\n3. Mewujudkan karakter lulusan yang berjiwa entrepreneurship, kompetitif dan berdaya saing;</br>\r\n4. Membangun tata kelola organisasi yang handal, akuntabel dan transparan dengan memanfaatkan transformasi digital;</br>\r\n5. Membangun pusat unggulan berbasis potensi sumber daya lokal.'),
(114, 'Politeknik Negeri Sambas', 'Menjadi Institusi Pendidikan Vokasi Yang Unggul di Tingkat Nasional dan Internasional Pada Tahun 2034.', '1. Mewujudkan Pendidikan Vokasi berkelanjutan melalui peningkatan mutu tridharma perguruan tinggi serta kerja sama pendidikan.</br>\r\n2. Meningkatkan kualitas lulusan yang berdaya saing nasional dan internasional.</br>\r\n3. Mewujudkan tata kelola yang baik (good governance) menuju tercapainya standar internasional.'),
(115, 'Politeknik Negeri Tanah Laut', 'Menjadi Politeknik Unggulan dan Berdaya Saing Nasional', '1. Menyelenggarakan pendidikan dan pembelajaran bermutu.</br>\r\n2. Melaksanakan kegiatan penelitian yang dapat di integrasikan dengan kegiatan pengabdian masyarakat, yang mendapatkan nilai tambah (added value) serta menghasilkan kemanfaatan (benefit).</br>\r\n3. Meningkatkan tata kelola institusi berbasis IT dan sistem yang terintegrasi (integrated system), secara efektif dan efesien serta akuntabel.</br>\r\n4. Melakukan penguatan kemitraan dengan perguruan tinggi vokasi (applied sience) dan dengan pihak ketiga (dunia usaha dan dunia industri) serta pihak lainnya.</br>\r\n5. Pemenuhan sarana dan prasarana infrastruktur, dan peralatan pendukung secara berkelanjutan, bagian dari pembangunan yang sudah ada.'),
(116, 'Politeknik Negeri Subang', 'Pada tahun 2030 menjadi salah satu politeknik terbaik di Indonesia.', '1. Menyelenggarakan pendidikan tinggi vokasi yang berkualitas;</br>\r\n2. Menyelenggarakan penelitian yang berorientasi pada teknologi terapan;</br>\r\n3. Menyelenggarakan pengabdian kepada masyarakat yang berorientasi pada teknologi tepat guna;</br>\r\n4. Mengembangkan sistem manajemen yang andal untuk tata kelola yang transparan dan terpercaya;</br>\r\n5. Menjalin kerja sama dengan pemangku kepentingan.'),
(117, 'Politeknik Negeri Ketapang', 'Mewujudkan pelayanan teknis dan administrasi yang profesional, kooperatif serta informatif dalam bidang akademik dan kemahasiswaan dalam rangka mendukung tercapainya layanan prima demi kemajuan Politeknik Negeri Ketapang yang unggul dan kompetitif.', '1. Terselenggaranya pelayanan teknis dan administrasi dalam bidang akademik dan kemahasiswaan</br>\r\n2. Tersedianya data dan informasi yang akurat dan komprehensif dalam bidang akademik dan kemahasiswaan.</br>\r\n3. Terwujudnya sistem informasi akademik yang mudah diakses dan adaptatif.</br>\r\n4. Terselenggaranya pelayanan teknis dan administrasi yang berkualitas unggul profesional di bidang akademik dan kemahasiswaan.'),
(118, 'Politeknik Negeri Cilacap', 'Menjadi perguruan tinggi vokasi yang unggul dan berkontribusi bagi masyarakat.', '1. Menyelenggarakan Pendididikan Vokasi berbasis teknologi yang bermutu, bermoral dan berkeadilan sosial</br>\r\n2. Menyelenggarakan penelitian dasar dan/atau terapan, serta menyebarluaskan hasil penelitian</br>\r\n3. Menyelenggarakan kegiatan pengabdian untuk membantu meningkatkan taraf hidup masyarakat</br>\r\n4. Membentuk jiwa kewirausahaan berbasis teknologi (technopeneurship)'),
(119, 'Politeknik Negeri Indramayu', 'Politeknik Terdepan Tingkat Nasional Berdaya Saing Global.', '1. Meningkatkan mutu, akses, dan relevansi pendidikan politeknik untuk menghasilkan lulusan sesuai kebutuhan pekerjaan;</br>\r\n2. Melakukan penelitian terapan dan pengabdian masyarakat untuk mengatasi persoalan industri dan masyarakat.'),
(120, 'Politeknik Negeri Nunukan', 'Menjadi institusi pendidikan tinggi vokasional terkemuka dan luar biasa di Kalimantan pada tahun 2024.', '1. Menginovasi fleksibilitas kurikulum</br>\r\n2. Membangun kegunaannya</br>\r\n3. Memberdayakan semua sumber daya');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `visimisi_kampus`
--
ALTER TABLE `visimisi_kampus`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `visimisi_kampus`
--
ALTER TABLE `visimisi_kampus`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=121;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
